### ISSUE TITLE
Add documentation for parallel tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#100]
@CharliePoole commented on [Fri Sep 26 2014](https://github.com/nunit/nunit.org/issues/5)

**Comment by aolszowka** [comment]
Hey Charile,

Thank you for the entire NUnit.org team's work on NUnit and their progress with NUnit 3.0; I've just started evaluating upgrading to NUnit 3.0 to take advantage of the Parallel Testing ability and found the documentation a bit lacking; specifically with regards to examples. I was going to open an issue but found this one via search.

Would it be possible to make the documentation a little bit clearer on how the Parallel attributes are expected to be applied? I created the following test application and after a bit of fiddling I believe I've grasped the intent, however be it either though my own ignorance or possible bug (I'll file a report next) I do not think this is working completely as intended.

First here's the code:

```
namespace NUnit3Parallel
{
	using System.Collections;
	using NUnit.Framework;

	// This will run at the same time as ParallelTest2
	[Parallelizable(ParallelScope.Fixtures)]
	[TestFixture]
	public class ParallelTest
	{
		[TestCaseSource( typeof( SleeperTests ) )]
		public void ParallelTests( int sleepTime )
		{
			System.Threading.Thread.Sleep( sleepTime );
			Assert.True(true);
		}
	}

	// This will run at the same time as ParallelTest
	[Parallelizable( ParallelScope.Fixtures )]
	[TestFixture]
	public class ParallelTest2
	{
		[TestCaseSource( typeof( SleeperTests ) )]
		public void ParallelTests( int sleepTime )
		{
			System.Threading.Thread.Sleep( sleepTime );
			Assert.True( true );
		}
	}

	// Because these tests can't be run in parallel mark them as such
	[Parallelizable( ParallelScope.None )]
	[TestFixture]
	public class ParallelTest3
	{
		[TestCaseSource( typeof( SleeperTests ) )]
		public void ParallelTests( int sleepTime )
		{
			System.Threading.Thread.Sleep( sleepTime );
			Assert.True( true );
		}
	}

	internal class SleeperTests : IEnumerable
	{
		public IEnumerator GetEnumerator()
		{
			yield return new TestCaseData( 1000 ).SetName( "1000ms Sleep" );
			yield return new TestCaseData( 2000 ).SetName( "2000ms Sleep" );
			yield return new TestCaseData( 3000 ).SetName( "3000ms Sleep" );
			yield return new TestCaseData( 4000 ).SetName( "4000ms Sleep" );
			yield return new TestCaseData( 5000 ).SetName( "5000ms Sleep" );
		}
	}
}
```

As you can see we've got 3 Test Fixtures; all of which run essentially the same test; they sleep for various amounts of time.

Running these tests serially we'd expect a run-time of around 45 seconds. However we've decorated both `ParallelTest `and `ParallelTest2 `with the `Parallelizable `Attribute, giving them a scope of `ParallelScope.Fixtures`, the third TestFixture (`ParallelTest3`) we've decorated with the `Parallelizable `Attribute with a scope of `ParallelScope.None` meaning these test should not be run in Parallel with anything.

Executing this test shows that indeed our runtime has been reduced from ~45 Seconds to ~30 Seconds.

So far so good where the confusion for me comes in is a couple fold:
* In searching for examples online it appears that you're able to set this as an attribute of the assembly to serve as a default, using the syntax `[assembly: Parallelizable(ParallelScope.Fixtures)]` the documentation seems to indicate that this can be overwritten at the TestFixture Level as needed, this seems to work as expected (but was confusing at first). Perhaps an example showing that would help? (I'd be happy to post the modified example using the above as source)
* The documentation on the meaning of `ParallelScope.Children` vs `ParallelScope.Fixtures` at least according to the current documentation _when applied at the TestFixture level_ seems to imply that they should behave identically (at least until the ability to parallel test at the TestCase/Method level is implemented). Testing does not seem to show that is the case (in the above example change ParallelTest2 to `ParallelScope.Children` and attempt to execute). **This is probably a bug?** I'd assume that for today I'd want developers to set this attribute for Children always with the expectation that at some point in the distant future it will behave with running each TestCase/Method in parallel in the fixture, but that for now it will run at the same level as TestFixtures.
* What does setting the `ParallelScope.Children` at the TestFixture level mean? I interpreted it to mean as I have documented above, that each TestCase/Method in the fixture should be allowed to run in Parallel. If that interpretation is correct, what is the meaning of setting ParallelScope.Self at the TestFixture level?

Sorry if any of these questions are elementary, but I hope I've given enough context to maybe make an improvement on the documentation.

Thank you

**Comment by CharliePoole** [comment]
@nunit/core-team @nunit/framework-team @nunit/engine-team 

I have created two new pages to document parallel test execution, linked from the Usage Notes page. They are https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution and https://github.com/nunit/docs/wiki/Engine-Parallel-Test-Execution

I also removed the existing specification pages related to parallel execution.

Comments please?

**Comment by jnm2** [comment]
> `ParallelScope.Fixtures` indicates that test fixtures that are the descendants of the test may be run in parallel with one another.

I think my mental model is incomplete. I didn't know it was possible for a test fixture to be a descendant of a test.

**Comment by CharliePoole** [comment]
@jnm2  For example...

```
Assembly
   Namespace
        Namespace with SetUpFixture
              Namespace
                    Test Fixture
                          Parameterized Test Suite
                                Test Case
```

Each line is a "test"

**Comment by CharliePoole** [comment]
However, you are justified in being confused since we typically overload "test" to mean test case. 😸

**Comment by jnm2** [comment]
Okay. In my mind test equated to "Parameterized Test Suite" (or "Test Method" if not parameterized).
So, in order to specify a ParallelScope on an ancestor of a test fixture, I'd have to specify it at the assembly level, right? There is no way to specify it at a namespace level and a test fixture cannot be the descendant of another test fixture, right?

I need to read up on SetUpFixtures apparently. I didn't realize they played a part in the hierarchy.

**Comment by CharliePoole** [comment]
You can specify an attribute at the namespace level only by putting a SetUpFixture there first. However, it can be an empty SetUpFixture, with neither one-time setup nor one-time teardown methods involved. See my recent comment on issue nunit/nunit#1474 for an example.

**Comment by CharliePoole** [comment]
Obviously, we needed docs for this. :smile:

**Comment by CharliePoole** [comment]
In terms of design, the xunit (generic term, not the competing framework) architecture is fundamentally based on the Composite pattern, with everything in the hierarchy treated as a test.

**Comment by jnm2** [comment]
> In terms of design, the xunit (generic term, not the competing framework) architecture is fundamentally based on the Composite pattern, with everything in the hierarchy treated as a test.

Seriously, that would go great in the docs!

The multiple levels of parallelization are very abstract. Concrete examples would help me.

**Comment by CharliePoole** [comment]
How about a concrete example of something that needs a concrete example? 😄

**Comment by CharliePoole** [comment]
@jnm2 That was actually intended more seriously than it probably seemed with the smiley... I'm not clear for which parts of the document you would like to see concrete examples.

**Comment by jnm2** [comment]
@CharliePoole I guess what I'm trying to say is that there so many dimensions and ways to combine things, how do I know which combinations are meaningful and what each can do for me?

| | Assembly | Class (SetUpFixture) | Class (TestFixture) | Method (SetUp) | Method (Test) |
|-|-|-|-|-|-|
| None | ? | ? | ? | ? | ? |
| Self | ? | ? | ? | ? | ? |
| Children | ? | ? | ? | ? | ? |
| Fixtures | ? | ? | ? | ? | ? |

Assembly (4 choices) ×
&emsp;SetUpFixture (4 choices) ×
&emsp;&emsp;Test Fixture (4 choices) ×
&emsp;&emsp;&emsp;Parameterized Test Suite (4 choices)
&emsp;&emsp;&emsp;&emsp;Test Case

I'm not trying to be clever or anything here, just trying to grasp the boundaries.

So for example, what does this do?

Assembly (Self) ×
&emsp;SetUpFixture (None) ×
&emsp;&emsp;Test Fixture (Children) ×
&emsp;&emsp;&emsp;Parameterized Test Suite (Fixtures)
&emsp;&emsp;&emsp;&emsp;Test Case

**Comment by CharliePoole** [comment]
I like the table idea if we filled it in intelligently. I would leave out none, however, since we want to drive people to the NonParallelizable attribute.

To your questions...

Self does nothing on the assembly. I think we give an error if you use it.

None on the SetUpFixture us just the default of no parallelism.

Children on the fixture tells test cases to run in parallel.

I'm not sure you can get it to apply to a parameterized test suite. I think fixtures should be an error on it anyway.

I think you may need to try some of this to see if we have some bugs in the corner cases.

I already closed the issue but if you want to set up a table like you showed I can help fill it in.

**Comment by jnm2** [comment]
I think it would be amazing if test cases ran in parallel down the road. The use case for this is when I nede to run a single long-running parameterized suite over and over.

**Comment by CharliePoole** [comment]
Are you saying it isn't working? Please file a bug if that's the case.

If you're just reacting to my comment, I was only replying to the specific example you gave, which didn't set the test cases to run in parallel.

**Comment by jnm2** [comment]
@CharliePoole Eh, let me clear some time to dive into test-driving this before I say anything else. I thought that work had been put off.

**Comment by CharliePoole** [comment]
@jnm2 OK. See http://github.com/nunit/docs/wiki/Framework-Release-Notes

I suppose there can be some confusion in the use of "test", "test case" and "test method". "Test case" is used for both parameterized test methods and individual tests using the Test attribute. When you place the Parallelizable attribute on a test method, it impacts the test case or cases that use that method.
