### ISSUE TITLE
Complete the Constraints page

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#102]
What's needed:
- First let's decide if we want both tables. Having both means duplicating summary info on the page and may make it harder to update. Would one be sufficient or is it worth the extra effort to have both? If just one, which one? [Note that the second table is not complete yet.]
- Then fill in brief descriptions for each constraint.

**Comment by SeanKilleen** [comment]
🧹 Closing this older issue -- at a glance, all Constraints appear to be documented and have at least brief descriptions. We can handle any needed updates on a case by case basis.
