### ISSUE TITLE
TestCase Attribute should support a name parameter for Properties

### ISSUE THREAD

**Issue by utcntt** [nunit/docs#103]
Right now, TestCase Attribute doesn't support any name parameter for Properties. In case users want to set a property for a test case, they have to use TestCaseData (https://github.com/nunit/docs/wiki/TestCaseData). In my company, we are going to use a Property to link a test case with an issue number => Developers fix an issue, we can execute all related test cases to make sure that the issue is really fixed.

**Comment by CharliePoole** [comment]
This is the documentation repository, for use in filing issues with the documentation. I'm moving your issue to the nunit repository.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit #1747](https://github.com/nunit/nunit/issues/1747) via [**ZenHub**](https://www.zenhub.com/)
