### ISSUE TITLE
Request: Example or documentation for a custom data source in NUnit3

### ISSUE THREAD

**Issue by paul-nelson-baker** [nunit/docs#105]
According to the wiki, we can define custom data-sources (https://github.com/nunit/docs/wiki/Framework-Extensibility). However, when I go to the custom attributes page, it states that it is under construction (https://github.com/nunit/docs/wiki/Custom-Attributes). 

Definitely understandable as I'm sure there is a lot of work that must be covered to explain how this is done. In the mean-time, are there any classes or places I can look to figure out how this is done?

**Comment by rprouse** [comment]
All of the NUnit attributes are written the same way as you would write your own custom attributes. Check out our source code, copy an attribute that is close to what you want and use it as a template.

There is also an example custom ExpectedExceptionAttribute in the C# samples repo.

**Comment by paul-nelson-baker** [comment]
Following up on this, I believe what I ended up doing was just that and looking at those examples you pointed out to me. Bonus points for the fact there appears to have been a lot of documentation added since then too!

Closing for hygiene 🙂
