### ISSUE TITLE
The calling thread must be STA, because many UI components require this.

### ISSUE THREAD

**Issue by john1726** [nunit/docs#107]
Presently, when I run some unit tests, I get this error:

```
System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The calling thread must be STA, because many UI components require this.
  Source=PresentationCore
  StackTrace:
       at System.Windows.Input.InputManager..ctor()
       at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
       at System.Windows.Input.Keyboard.ClearFocus()
```
       
So far, I have tried to use `RequiresSTAAttribute `as suggested here https://stackoverflow.com/questions/1256329/problem-with-runnig-nunit-tests-under-sta?rq=1, but this does not work for NUnit 3.0.  Does anyone have any suggestions?  TIA

**Comment by jnm2** [comment]
[`[Apartment(ApartmentState.STA)`](https://github.com/nunit/docs/wiki/Apartment-Attribute)

The [Attributes reference](https://github.com/nunit/docs/wiki/Attributes) is a good starting point for stuff like this.

**Comment by john1726** [comment]
Could you please tell me, where is the Apartment attribute is located?  When I put the code in you suggested, I get this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ApartmentAttribute' could not be found (are you missing a using directive or an assembly reference?)	38	Active
```

When I search for "C# .NET ApartmentAttribute" it takes me to this page:

https://msdn.microsoft.com/en-us/library/system.stathreadattribute%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

**Comment by rprouse** [comment]
The ApartmentAttribute you want is the NUnit 3 version, https://github.com/nunit/docs/wiki/Apartment-Attribute

It is in the NUnit.Framework namespace.

**Comment by CharliePoole** [comment]
@john1726 Are you actually using NUnit? You may be in the wrong place with your question. :-)

**Comment by john1726** [comment]
I'm so sorry, I had assumed we were using NUnit 3.0.  The version of the nunit.framework is 2.6.4.14350.  That's why Apartment wasn't found.

**Comment by CharliePoole** [comment]
The corresponding attribute in NUnit V2 is RequiresSTAAttribute. Early versions allowed use of System.STAThread for a while, because it was a common mistake made by users. We subsequently decided it was silly to add features to compensate for user errrors.
