### ISSUE TITLE
Document installing Engine Extensions

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#11]
Document how to install extension packages

**Comment by ChrisMaddock** [comment]
From #205, by @ArsenShnurkov 
> On the page
https://github.com/nunit/docs/wiki/Console-Runner
please add a hyperlink to the page which describes how to install that driver (what is it's dll name, how it should be built, and so on)

**Comment by ChrisMaddock** [comment]
From #137, by @DannyCork,

> I'd like to run nunit 2.6.4 test using the nunit3 console. The docs state

 > > If the NUnit V2 framework driver is installed, test assemblies may be run based on any version of the NUnit framework beginning with 2.0. Without the V2 driver, only version 3.0 and higher tests may be run.

> Where do I find the V2 driver?

This is on the console command line page. Both these places should probably be linked to a new page detailing how to install engine extensions.
