### ISSUE TITLE
Make it easer to find Assert.That documentation.

### ISSUE THREAD

**Issue by Bummibaer** [nunit/docs#113]
For example I've searched for Assert.That -> no hit.

**Comment by rprouse** [comment]
Basic specification of what?

**Comment by Bummibaer** [comment]
O.K.
I go to the wiki->Nunit User Docs -> Assertions
There are shortly stated two "Models", And then 3 Examples with Assert.That.
I'm searching for an (Doxygen?)-Syntax Description.
With Intellisense, I found the right parameter, but where do I find the documentation?
regards
Steffen

**Comment by CharliePoole** [comment]
Is this page what you are looking for? https://github.com/nunit/docs/wiki/Constraint-Model

It's linked from the Assertions page, but I admit it's not an obvious choice if you want docs for `Assert.That()`.  I have renamed this issue accordingly.

**Comment by Bummibaer** [comment]
Hey,
thank you for your lightning fast answer and solution:)
Would it make sense, to push also the doxygen-docu? 
I've seen the comments are there.
I'm going to look after that on the weekend.

**Comment by SeanKilleen** [comment]
Hi @Bummibaer! I know this was a long time in the making, and we've since launched a new docs site, but I wanted to mention that the Constraint model now also includes `Assert.That` in its title, which should make it easier to surface going forward.
