### ISSUE TITLE
nunit3-console.exe eats a path character when a lots of test assemblies passed as parameters

### ISSUE THREAD

**Issue by omusienk** [nunit/docs#114]
Hi guys!
I use an NUnit.ConsoleRunner.3.4.1 package to run unit tests in a pretty big .NET solution (up to ~60 tests assemblies).
I collect list of them all by MsBuild target in it's item group and pass to execution by expanding in the exec task like this: `<Exec	 Command="$(NUnit3Exe) @(NUnitTestsAssemblies, ' ')" />`.
So, from logs I see that the item group is expanded correctly, f.e. 
`e:\develop\packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe e:\develop\SomeTestProject\bin\Debug\SomeTestProject.Tests.dll 
.... 
e:\develop\OtherTestProject\bin\Debug\OtherTestProject.Tests.dll <- somewhere in the middle of the list
.... 
e:\develop\YetAnotherTestProject\bin\Debug\YetAnotherTestProject.Tests.dll`

But the nunit3-console.exe says that:
`NUnit Console Runner 3.4.1 
Copyright (C) 2016 Charlie Poole
Runtime Environment
OS Version: Microsoft Windows NT 6.3.9600.0
CLR Version: 4.0.30319.42000
Test Files
e:\develop\SomeTestProject\bin\Debug\SomeTestProject.Tests.dll 
.... 
e:\develop\OtherTestProject\bin\Deug\OtherTestProject.Tests.dll <- missed "b" in the full path
.... 
e:\develop\YetAnotherTestProject\bin\Debug\YetAnotherTestProject.Tests.dll`

And finally all's finished with a fail message:
`File not found: e:\develop\OtherTestProject\bin\Deug\OtherTestProject.Tests.dll`

**Comment by ChrisMaddock** [comment]
I can't reproduce this with 100 assemblies, can you supply a full command line where a character is dropped, which is reproducible using nunit3-console on the command line? Fake files is fine. :smile: 

I'll also move this over the the nunit-console repository - this one's just for documentaion. :+1:

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit-console #57](https://github.com/nunit/nunit-console/issues/57) via [**ZenHub**](https://www.zenhub.com/)
