### ISSUE TITLE
TestCaseSource: "Too many arguments provided" for IEnumerable<> parameter type

### ISSUE THREAD

**Issue by debugosaurus** [nunit/docs#115]
It appears that NUnit has started treating Array and Enumerable TestCaseSource parameters differently. I noticed this behaviour when upgrading from 3.0 to 3.4.1.0 (sorry that covers a lot of ground).

Say I declare some test data:

```
protected static IEnumerable<IEnumerable<string>> EnumerableOfStrings => new[] 
{ 
    new[] { "one", "two" }
};
```

The following test will pass:

```
[Test, TestCaseSource(nameof(EnumerableOfStrings))]
public void AcceptsArrayOfStrings(string[] array)
{
}
```

However this test will fail with the message **"Too many arguments provided"**:

```
[Test, TestCaseSource(nameof(EnumerableOfStrings))]
public void AcceptsEnumerableOfStrings(IEnumerable<string> enumerable)
{
}
```

It seems with the second test that NUnit is attempting to unbox the enumerable and pass each element as an argument rather than passing the enumerable as a single parameter.

**Comment by ChrisMaddock** [comment]
I can reproduce this - agreed it seems to be a bug. (Great bug report, by the way! :+1:)

I'll also move this issue over to the NUnit framework repo - this ones just for doc issues. :smile:

**Comment by ChrisMaddock** [comment]
Issue moved to [nunit/nunit #1792](https://github.com/nunit/nunit/issues/1792) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jnm2** [comment]
@CharliePoole issue template thingy to point people to the nunit repo?
My theory is that people always have docs pages open and then they click issues, just like they would do if they were in a wiki on a repo. At least that's why I did it.

**Comment by CharliePoole** [comment]
@jnm2 I guess you mean CONTRIBUTING.md? I filed #116 to create one.

**Comment by rprouse** [comment]
@CharliePoole we could also create an issue template, but that would require users who enter actual docs issues to delete the template. That said, the template could be something that indicates that this repo is only for documentation issues. Something like, 

--
What is the problem with the documentation?

What is the URL of the Documentation?

**Comment by CharliePoole** [comment]
I'm good either way.
