### ISSUE TITLE
Update Packaging-NUnit page

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#117]
https://github.com/nunit/docs/wiki/Packaging-NUnit

This will need some updates with the new nunit-distribuition repo, and the repository split. 

@rprouse - I can update the page re: nunit-distribution, but don't have enough overview of the whole process to do the rest, will leave that to yourself. :) 

(This issue is split out of nunit/nunit#1716)

**Comment by rprouse** [comment]
@ChrisMaddock no problem, I always edit the page as I am doing the release to keep it up to date. It will just require a bit of extra editing this time 😄

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: Closing, as this documentation currently exists and the issue is over 4 years old.
