### ISSUE TITLE
on your help page you  mentioned that clr.bat exist in the bin directory but that file is not there

### ISSUE THREAD

**Issue by yonisym** [nunit/docs#118]
http://www.nunit.org/index.php?p=consoleCommandLine&r=2.2.5
Specifying the Version of the CLR

Most applications are written to run under a specific version of the CLR. A few are designed to operate correctly under multiple versions. In either case, it is important to be able to specify the CLR version to be used for testing.

When only one version of the CLR is used, the config files for nunit-gui and nunit-console may be set up to specify that version. As a more convenient alternative when switching CLRs, you may use the provided clr.bat command to specify the version under which NUnit should run.

**Comment by CharliePoole** [comment]
You are looking at the documentation for NUnit 2.2.5, which is __really__ old! Do you really use that version? Or do you want the current docs? The repository where you are typing this issue includes the current documentation in it's wiki... :-) 

Specifically, the page for the console command line is at https://github.com/nunit/docs/wiki/Console-Command-Line

You should only use the docs for the version of NUnit you are actually using.

**Comment by yonisym** [comment]
yes I need to use the older version of NUnit as one of the plug in that I use from Jenkins the Nunit3 XML format, it only support the older format. So I am forced to downgrade. Can you please point me to the clr.bat file mentioned in your site?

**Comment by CharliePoole** [comment]
"Older" is too general. Are you actually using 2.2.5, which is from 2005? It seems unlikely. Running the console with -h will tell you both the version and what the command-line options are.

**Comment by rprouse** [comment]
@yonisym NUnit 3 can also output the test results in the NUnit 2 XML format. That might be an easier fix.

**Comment by yonisym** [comment]
I tried that but I didn't get any clear instruction on how to output in Nunit2 format.  can you give me an example of a command line ?

The version that I am using is NUnit 2.6.3 basically the help page that I have provided at the beginning of this thread mention that the solution for running console with this version is by using clr.bat from bin directory but I am not able to find the clr.bat file.

**Comment by rprouse** [comment]
If you read the documentation for 2.6.3, you will see that it does not talk about CLR.BAT, but gives different instructions, http://www.nunit.org/index.php?p=consoleCommandLine&r=2.6.3. You are looking at the 2.2.5 documentation.

For NUnit 3, if you run the console with the `--help` option, it gives you all of the information you need.

```
--result=SPEC          An output SPEC for saving the test results.
```

Then further down it explains what a SPEC is,

```
      Several options that specify processing of XML output take
      an output specification as a value. A SPEC may take one of
      the following forms:
          --OPTION:filename
          --OPTION:filename;format=formatname
          --OPTION:filename;transform=xsltfile

      The --result option may use any of the following formats:
          nunit3 - the native XML format for NUnit 3.0
          nunit2 - legacy XML format used by earlier releases of NUnit

      The --explore option may use any of the following formats:
          nunit3 - the native XML format for NUnit 3.0
```

Combine that and you get `--result=TestResult.xml;format=nunit2`

**Comment by yonisym** [comment]
Thanks a lot!!!  let me go through your suggestions/ direction.

**Comment by yonisym** [comment]
I tried the nunit2 option on the result but I am getting unknown format , is there any thing which I need to do to make it work ?

"C:\TestToolAndData\Nunit\nunit3-console.exe"  "C:\eCor
eRepository\internalportal\Test\InternalPortalSeleniumTest\InternalPortalSeleniu
mTest\bin\Debug\InternalPortalSeleniumTest.dll"  --result=TestResult.xml;format=nunit2
ERROR 
NUnit Console Runner 3.4.1
Copyright (C) 2016 Charlie Poole

Unknown result format: nunit2

**Comment by rprouse** [comment]
How did you install the NUnit console? It looks like `nunit.v2.driver.dll` is missing from the addins folder or `nunit.engine.addins` is missing from the the root folder or incorrect. Your folder should look like this,

![image](https://cloud.githubusercontent.com/assets/493828/18891447/4655de5e-84d3-11e6-8a05-5154068e2988.png)

**Comment by yonisym** [comment]
I was installing it from nugget manager , however now I just build the solution locally on my local box the command now accepts the nunit2 format. Man thanks for your help. I wish if you  guys put some kind of documentation for this so that others don't suffer. The funny thing is this thing also work from the following package location   \\packages\NUnit.ConsoleRunner.3.4.0\tools

**Comment by rprouse** [comment]
The docs for the runner are at https://github.com/nunit/docs/wiki/Console-Command-Line
