### ISSUE TITLE
Document Assert.Zero and Assert.NotZero

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#120]
Should go on the Classic Model page.

**Comment by mikkelbu** [comment]
@CharliePoole. I've have added two new pages: https://github.com/nunit/docs/wiki/Assert.Zero and https://github.com/nunit/docs/wiki/Assert.NotZero and linked to them from https://github.com/nunit/docs/wiki/Classic-Model.

**Comment by CharliePoole** [comment]
Looks good to me. I corrected the label to match.

**Comment by ChrisMaddock** [comment]
The content looks good, but the pages have picked up with wrong sidebar. 🙁 

@mikkelbu - compare your pages to [Assert.True](https://github.com/nunit/docs/wiki/Assert.True) - you see the sidebars different? I'm assuming you created these pages using the "New Page" button on the web interface?

Unfortunately that button doesn't really work with out directory structure. 👎 To fix this, you'll need to clone the wiki repo to your local machine, like a normal git repo (https://github.com/nunit/docs/wiki.git). Once you've done that, you'll see your new pages are in the root directory. If you move them to `/nunit/` and push, they will instead pick up the sidebar in the `/nunit/` subdir, which is what you see on all the other assertion pages.

You won't need to change any links - subdirectories are ignored in the linking structure. Also, don't worry about branching/PRs or whatever - there's no PR system for wiki's, so everything just gets pushed to master. It's not the best system, for changes like this, unfortunately.

Let us know if you have any problems, and I can fix it. 🙂

**Comment by mikkelbu** [comment]
@ChrisMaddock The problem should be solved now. Should I just close the issue or should somebody verify the file movement?

**Comment by CharliePoole** [comment]
It looks good. In general, we are very informal about the wiki so you can feel free to close an issue once you think it's fixed, or just ask someone to review if you feel it is necessary.

**Comment by ChrisMaddock** [comment]
Great - thanks for that! 😊
