### ISSUE TITLE
Test order doesn't work if tests in one category but in different classes

### ISSUE THREAD

**Issue by Stezinak** [nunit/docs#127]
It can be not an issue, but I find it very inflexible.
I have different classes with tests. Both classes have same test category, tests have orders.
When I run test category test order breaks so test with order = 7 was running first.
Sure I can move tests in one class but it isn't convenient for me.
Any ideas?

**Comment by rprouse** [comment]
@Stezinak I doubt we will allow ordering between methods in different classes, but if we allowed ordering of fixtures you could set one fixture to run after another then set their internal orders. Would that be what you are looking for?

Are the test classes different enough that they need to be different classes, or could you use one partial class split between the two files?

**Comment by rprouse** [comment]
I am going to mark this as a question and close it because we won't be changing the framework to work this way, but please continue to post questions to the issue, I would like to understand your use case better so that when we do expand the use of the Order attribute or create a Dependency attribute, we can take your use case into account.

**Comment by Stezinak** [comment]
I am using nunit for selenium tests.
I have some classes for creating data on server from scratch. For example, in one class I make firm, departments and all that relates to firm structure. In another class I make employees and all for employees (using cars and something like this). Sure, when I am creating employees I have to have firm and departments at this moment. Real structure is more difficult.
I agree with you, that I can add all in one class or create partial classes. Dependency is really usefull. Can it be not only between methods? For example, between categories: if I run on CI test with category "Hire employee" with dependency to "Initialize database" first of all test will check do I have all mandatory fields in database. 
As I said it's only example. Thanks for your answers and your work!

**Comment by rprouse** [comment]
@Stezinak I think adding an order attribute to fixtures would solve your problem. Your classes would be executed in order, then the methods within them would have their order.  We have an issue for this, nunit/nunit#345

Thanks for writing out your use case.
