### ISSUE TITLE
Visual Studio can be set up to match the coding standards by importing the nunit.vssettings file from this repository. This file will only change the C# indentation and formatting settings. It will not modify any other Visual Studio settings. It can be imported into Visual Studio 2010 and later by going to Tools | Import and Export Settings...

### ISSUE THREAD

**Issue by oznetmaster** [nunit/docs#129]
The link in the line is invalid :(

No way to find the settings file.

**Comment by CharliePoole** [comment]
Please give a link to where the page with the bad link may be found.

**Comment by HeSitates** [comment]
It is in dev/notes/Coding-Standards.md (line 17)

[nunit.vssettings](https://github.com/nunit/dev/blob/master/nunit.vssettings) is the culprit

**Comment by ChrisMaddock** [comment]
Thanks @HeSitates - I've fixed the link. 👍
