### ISSUE TITLE
Nunit console runner - setting baseurl at runtime

### ISSUE THREAD

**Issue by dichiser** [nunit/docs#131]
I have a couple different environments to test, each with a different URL.  Is there a way to pass the BaseURL to nunit3-console.exe on the command line?

**Comment by CharliePoole** [comment]
Yes, using the `--params` option. See https://github.com/nunit/docs/wiki/Console-Command-Line for passing the option and https://github.com/nunit/docs/wiki/TestContext for retrieving it in your tests.
