### ISSUE TITLE
How to interact with extensions?

### ISSUE THREAD

**Issue by nvborisenko** [nunit/docs#136]
Hello,

Imagine I have 3 dedicated projects:
1) Extension1.dll
2) Extension2.dll
3) Tests.dll

Extension1 and Extension2 implements *ITestEventListener* interface. How can I get access from **Tests** to **Extension1**, or from **Extension2** to **Extension1**. I want to get an access to the object of the extension which is constructed by NUnit Engine.

My case is extensions implement ITestEventListener, and have events, I want to subscribe to events in the  extensions.

Only 1 solution I see to resolve my issue: in Tests.dll inherit from Extension and make this inherited extension as primary (using *.addin file).

What is the best way you suggest to resolve my situation? Thank you in advance.

**Comment by CharliePoole** [comment]
In the design of nunit, your tests are expected to be completely isolated from the mechanisms used to run them. The test has no way to even know that the engine exists much less to communicate with it. So what you describe is not possible.

If you can explain what you are trying to accomplish, it may be possible to make alternative suggestions.
