### ISSUE TITLE
Logger does not work in newly created AppDomain

### ISSUE THREAD

**Issue by y-skindersky** [nunit/docs#142]
Could you please comment the issue described here:
http://stackoverflow.com/questions/20886118/logger-does-not-work-in-newly-created-appdomain#comment38763630_24940179

I call XmlConfigurator.Configure(); in each app domain and it works correctly in running application but it doesn't work if the same code is running under NUnit

**Comment by CharliePoole** [comment]
Using the R# runner is __not__ "running under nunit". It's up to whatever application sets up the test AppDomain. If the error occurs under nunit3-console then we can open an issue.
