### ISSUE TITLE
Cannot generate unit test in the same project as production assembly

### ISSUE THREAD

**Issue by vnvizitiu** [nunit/docs#143]
When trying to generate unit tests in the same project, a error message box shows up and lets me know that it cannot add a reference as it will create a "self-reference"

I know it is a bad practice to have unit tests in production assemblies, but that is coding model the group i work with has adopted and won't change it, though the create dialog box does allow me to choose that project and even finds the test file i have setup

**Comment by CharliePoole** [comment]
@vnvizitiu Is this intended to be an issue against the nunit-vs-testgenerator project? If so I can move it.

**Comment by vnvizitiu** [comment]
ouch, yeah, my bad, saw that there were other generator related issues in the backlog, please move it then

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-vs-testgenerator #19](https://github.com/nunit/nunit-vs-testgenerator/issues/19) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CharliePoole** [comment]
No big deal. It happens a lot now that we have separated code projects and a combined set of docs.
