### ISSUE TITLE
Xml Documentation in the Nuget packages

### ISSUE THREAD

**Issue by cinnamon25** [nunit/docs#146]
Can you please, include the XML Documentation in the nuget packages, so that Visual Studio shows the documentation, when I hover on a method...

**Comment by CharliePoole** [comment]
I assume you mean in the nuget package for the framework?

**Comment by cinnamon25** [comment]
Yes

**Comment by rprouse** [comment]
@cinnamon25 we do include the XML Docs for the NUnit framework in the package. Is there another project that it is missing from or are you seeing problems?

Here is a screenshot of the 3.5 release in NuGet Package Explorer

![image](https://cloud.githubusercontent.com/assets/493828/21081796/1d63feb4-bf9c-11e6-8c50-dc71500d4856.png)

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit #1922](https://github.com/nunit/nunit/issues/1922) via [**ZenHub**](https://www.zenhub.com/)
