### ISSUE TITLE
Review of updated page

### ISSUE THREAD

**Issue by SamJongenelen** [nunit/docs#148]
Please review my Wiki changes and fill in where I put question marks in the table.

Wiki [Tips and tricks ](https://github.com/nunit/docs/wiki/Tips-And-Tricks/)

**Comment by SeanKilleen** [comment]
Closing this as these items have moved to the docs.nunit.org site: https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html 

We continue to welcome contributions here!
