### ISSUE TITLE
Modifiers for CollectionContainsConstraint Contains HTML

### ISSUE THREAD

**Issue by lundmikkel** [nunit/docs#15]
On https://github.com/nunit/docs/wiki/CollectionContainsConstraint#modifiers, the **Modifiers** section contains HTML tags:
```
...Using(IComparer comparer)
...Using&lt;t&gt;(IComparer&lt;T&gt; comparer)
...Using&lt;t&gt;(Comparison&lt;T&gt; comparer)
```
Should probably be
```
...Using(IComparer comparer)
...Using<T>(IComparer<T> comparer)
...Using<T>(Comparison<T> comparer)
```

Notice also that the type parameter is currently written in lower case.

**Comment by CharliePoole** [comment]
Thanks for pointing that out!
