### ISSUE TITLE
Question: Is there a method that allows some code to be run only once before all TestFixtures

### ISSUE THREAD

**Issue by sisillV** [nunit/docs#150]
Hi,
I need a way to run a code once before all TestFixtures.

**Comment by CharliePoole** [comment]
Yes, you can use a SetUpFixture.

**Comment by sisillV** [comment]
Hi CharliePoole,
SetUpFixture runs the code in it before every TestFixture. But I want the code to be run only once before all TextFixtures.

**Comment by ChrisMaddock** [comment]
See https://github.com/nunit/docs/issues/151
