### ISSUE TITLE
Question: SetUpFixture runs the code before every TestFixture. Is there a way to run a code once before all TestFixtures?

### ISSUE THREAD

**Issue by sisillV** [nunit/docs#151]
Hi,
I need a way to run a code once before all TestFixtures.

CharliePoole commented 15 hours ago
Yes, you can use a SetUpFixture.

Hi CharliePoole,
SetUpFixture runs the code in it before every TestFixture. But I want the code to be run only once before all TextFixtures.

**Comment by ChrisMaddock** [comment]
You need to use a `[OneTimeSetUp]` rather than a `[SetUp]` inside your `[SetUpFixture]`.

I'll close this issue now - but feel free to comment further if you need more help, we'll still be notified.

**Comment by sisillV** [comment]
Hi ChrisMaddock,
[OneTimeSetUp] is running once for the TestFixture. But I want to run the code before all TestFixtures. 
So if I have [OneTimeSetUp] in Base class the code in it will be run before every TestFixture, but I want to run the code only once before the first first TestFixture and not to be run again.

**Comment by ChrisMaddock** [comment]
Sorry @sisillV - I misread. 

I think you'll need a common base class with the setup method, and to have all your other classes inherit from that. I'm not sure there is a native feature to do what you're after.

**Comment by ChrisMaddock** [comment]
Hi @sisillV,

Are you using a `[SetUpFixture]` too? What you want should be possible by using a `[OneTimeSetUp]` in a `[SetUpFixture]` test class. e.g.

```
using System;
using NUnit.Framework;

namespace NUnit.Tests
{
  [SetUpFixture]
  public class MySetUpClass
  {
    [OneTimeSetUp]
    public void RunBeforeAnyTests()
    {
      // ...
    }

    [OneTimeTearDown]
    public void RunAfterAnyTests()
    {
      // ...
    }
  }
}
```

**Comment by sisillV** [comment]
Write now I do this very ugly... I have one TestFixture named "A" which don't inherit my base class. It is named "A" to be sure that it will be run the first. And this TestFixture "A" is not running in Parallel. In this TestFixture "A" I have [OneTimeSetUp] and I am sure that this will be run only one time and first - before all Real TestFixtures. In this TestFixture "A" I have only one test with Pass assert in it with message the code that must be run once  pass.
Then in the base class I have other  [OneTimeSetUp] and all my real TestFixrtures inherit this Base class.
So this code is running before every TestFixture.

But I don't like this situation. And I am wonder if there is a Method in Nunit that the code in it will be run once before any TestFixture even Start and not to be run again. 
I hope you understand me now....

**Comment by ChrisMaddock** [comment]
Hi @sisillV,

Look at the `[SetUpFixture]` attribute in my example above. That sounds like what you are looking for - have you tried it?

Have a look at the docs page here: https://github.com/nunit/docs/wiki/SetUpFixture-Attribute

**Comment by sisillV** [comment]
Thank you!!!
It works perfect!
