### ISSUE TITLE
Question: Failed and Pass statuses count at the end of the test

### ISSUE THREAD

**Issue by sisillV** [nunit/docs#152]
Hi NUnit Team,
Is there a way to record pass and failed steps without stop the test like it is happened when we use Assert.Failed.
I need NOT to stop the test every time on error but at the same time to record the errors somewhere. 
Now I have a custom validate method that collects all error in List<string>
But I want to know is there a way do this with NUnit method?

**Comment by ChrisMaddock** [comment]
Sounds like you're looking for the new Multiple Asserts feature. This will be available in NUnit Framework 3.6, which should be released by the end of the week. It will work with all versions of runners, however it will provide a more user friendly output in the next version of the console (3.6) - which should be released in the next couple of weeks also. The VS adapter will be updated in the same way at some point in the future. 

There's no official docs yet, but there's a technical spec which should contain enough information here: https://github.com/nunit/docs/wiki/Multiple-Asserts-Spec

I'll close this question now - although feel free to ask more if needed, we'll still see it. 😄

**Comment by sisillV** [comment]
I think that this is not what I search...
Imagine that you have an application that you must test the labels in 2 different languages. So I check all labels in one page then in other... and collect pass and failed and in the teardown I check the results and make an report from collected data.
I can not put all in one Multiple Assert. I need not to stop after fail.  If I want to fail the test I will use Assert.Failed...

**Comment by CharliePoole** [comment]
If there are any failures in a multiple assert block, then the test fails immediately on exit. If you want to make further checks, you will have to extend the multiple assert block. In the extreme, all the code of your test method can be in a single block. Any assert failures will be listed separately when the test is reported.

If you don't want the test to fail at all, then you should use the new Warning result via `Warn.If(...)` or `Warn.Unless(...)`. However, for visibility, it seems like the test should eventually fail if it contained failing asserts.

If this doesn't make sense in your context, perhaps you could add a bit of pseudo-code showing what you want to do.

**Comment by CharliePoole** [comment]
Perhaps this is a source of confusion... the specification example makes it appear as if only Asserts can be inside the multiple assert block. That's not so - any C# code at all may be in the block. I'll make that clear in the final docs.
