### ISSUE TITLE
Release notes contain wrong dates

### ISSUE THREAD

**Issue by dbenzhuser** [nunit/docs#156]
In the release notes, both the 3.5 and the 3.6 release are marked as being released in 2015.

(Hints on how to make the change myself or make it easier for other are welcome.)

**Comment by dbenzhuser** [comment]
Was fixed by @JustinRChou.

**Comment by ChrisMaddock** [comment]
Thanks @dbenzhuser, good spot. I've also made the change at source in the framework repo.

> (Hints on how to make the change myself or make it easier for other are welcome.)

Unfortunately we don't currently have that capacity for the docs - we're hoping to improve that in the future however. This is the best method of contributing such things, for now. 😄
