### ISSUE TITLE
Update Author Attribute

### ISSUE THREAD

**Issue by JustinRChou** [nunit/docs#157]
Update page for multiple use of Author Attribute.

Add in TestCase(Author = "name") usage? Or add it into TestCase's page?

**Comment by CharliePoole** [comment]
I would just update this page: https://github.com/nunit/docs/wiki/Author-Attribute and I wouldn't bother with TestCase for now. I'm wondering if we really want to keep it - it makes sense to me that we have authors for the code but not for the cases. I'd need to look back to see how long we have had it though.

**Comment by JustinRChou** [comment]
I couldn't trace it back to an issue.

But the doc update should happen after the release?

**Comment by CharliePoole** [comment]
Yes.

**Comment by mikkelbu** [comment]
@nunit/framework-team Please review https://github.com/nunit/docs/wiki/Author-Attribute

(I was looking into nunit/docs#279, and I noticed that the page was not correct and therefore updated it, afterwards I noticed this issue 😄 )

**Comment by CharliePoole** [comment]
Looks good to me.
