### ISSUE TITLE
Installing NunitConsole 3x via nuget

### ISSUE THREAD

**Issue by harshana5** [nunit/docs#158]
Hi,

I use the nunit console 2.x on my CI to execute my tests. The way I used installed nunit console previously was by running `nuget.exe install nunit.runners` (
https://www.nuget.org/packages/NUnit.Runners/) at the setup step of my tests jobs. As I understand this method is depreciated and I should be using `nuget.exe install NUnit.Console`. However when I run this command I see the nuget package is installed but cant see `tools\nunit3-console.exe`. Am I missing something here ? or is this an issue being looked at ?

**Comment by ChrisMaddock** [comment]
The NUnit.Console package doesn't contain any assemblies of it's own, but instead installs 6 different, smaller NuGet packages - the main console runner, and 5 commonly used extensions. You'll find the console runner in the NUnit.ConsoleRunner package, under `nunit.consolerunner.3.6.0\tools\nunit3-console.exe`.

I'll close this issue as not-a-bug, but feel free to post further if you hit any other problems - the team will still be notified. 😄

**Comment by michaelkauflin** [comment]
Will the NUnit.Runners NuGet tool package always be created as soon as there is a new NUnit.Console version available? In other words: NUnit.Runners is an aggregator for the other packages such as NUnit.Console and NUnit.Extension

I can always update NUnit.Runners and the underlying packages are installed?

**Comment by michaelkauflin** [comment]
Hi Chris
Thanks for the reply - I have seen on Nuget.org the answer you just gave me now :smile:
