### ISSUE TITLE
Broken Link to Collection Constraints

### ISSUE THREAD

**Issue by lundmikkel** [nunit/docs#16]
The **See also** link at the bottom of the [Assert.Contains page](https://github.com/nunit/docs/wiki/Assert.Contains) doesn't work. I can't even find the page that it should point to.

**Comment by lundmikkel** [comment]
Should it be this one: [https://github.com/nunit/docs/wiki/CollectionContainsConstraint](https://github.com/nunit/docs/wiki/CollectionContainsConstraint)?

**Comment by CharliePoole** [comment]
Yes, I  changed it to that one.
