### ISSUE TITLE
TestList with Where clause

### ISSUE THREAD

**Issue by kappa10j** [nunit/docs#160]
Should these work together?  I wanted to have a master list file that orders the tests and then specify an attribute per run to select specific tests (from the ordered list).  It seems the where clause has priority over the testlist.

**Comment by CharliePoole** [comment]
They do work together, just not in the way you want.

The tests selected by --test, --testlist and --where are combined using a logical OR operation. It's assumed that you definitely want to run tests you have named explicitly.

If you want to use some other logic, then you have to include the list of names in the where clause itself. Use of the @filename syntax will help avoid an overly long command-line in that case.

**Comment by CharliePoole** [comment]
I noticed that the @filename syntax was not documented and added it. See https://github.com/nunit/docs/wiki/Console-Command-Line

I suggest using something like --where @tsl.txt. The file tsl.txt could contain something like

```
(test==somename || test==someothername || ...) && cat==mycategory
```

Unfortunately, you will have to put the entire tsl expression on one line. 😞
