### ISSUE TITLE
Throw for invalid TestCase Data

### ISSUE THREAD

**Issue by Epibatidin** [nunit/docs#161]
Hi 

recently i found a test which was not run for month because the testcase arguments where wrong.

some month ago we had : 

[TestCase(1, true)]
[TestCase(2, true)]
public void Foo(int i, bool whatever)

then some day i refactored the underlying interface and forgot to change the required parameters so we get : 

[TestCase(1, true)]
[TestCase(2, true)]
public void Foo(int i)

Nunit never complained and - okay it was my fault and i should have seen this - didnt run this test for month. 

It would be nice if there would be a TestRunner configuration option to throw exceptions in case the attribute data seems invalid for the method.

Mfg

**Comment by CharliePoole** [comment]
The example you give should result in an error. What test runner are you using? What version of the NUnit framework?

**Comment by Epibatidin** [comment]
The project where the above occured uses 

Nunit : 2.6.3
with Ncrunch as TestRunner 

a different project uses Nunit 3.5 with VS NunitTestAdapter
which throws a TargetParameterCountException. 
OldStuff < NewStuff 

Thanks - No Todo

**Comment by JasonBock** [comment]
Side note: if the nunit.analyzers were included, one of the analyzers would've caught this at compile-time :)

**Comment by CharliePoole** [comment]
@JasonBock My understanding is that the analyzers only work with NUnit 3+ Am I wrong?
