### ISSUE TITLE
How to get up to speed testing the framework on Mono with Linux

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#163]
Can we have a guide linked from https://github.com/nunit/docs/wiki/Developer%20FAQ to get Windows devs like me running Mono tests on a recommended Linux distro in as few steps as possible?

I can try to hack my way through setting up a testing environment on Windows Subsystem for Linux (would be way cool) or Ubuntu on my own, but I'd like to take advantage of the knowledge that already exists.

**Comment by frankschmitt** [comment]
I second this request - I just started using F# with NUnit on Mac OS X, and it's quite cumbersome (mostly due to lack of good tutorials / step-by-step instructions).

**Comment by CharliePoole** [comment]
@jnm2 Do you mean for developers of NUnit or for general users? My feeling has generally been that it's beyond our scope - as well as our resources - to teach general things, separate from NUnit. So I can imagine a guide to using NUnit that is aimed at Linux developers, but helping Windows devs switch to Linux might be too big a job and better done by the Linux community. OTOH, I could invision a mini-guide for testing NUnit under Linux, if that's what you mean. What would your ideal guide's table of contents look like?

@frankschmitt Sad to say, we are not able to provide step-by-step instructions for using NUnit with F# for a rather simple reason: none of us are really F# developers. I've several times invited specific F# folks to join our team because I think we should be deeper (well, our depth is now measured in inches!) in that area. Unfortunately, nobody has wanted to accept, I suppose because NUnit is written in C#.

I've played around with F# myself, but that's the most I can say and I wouldn't consider myself capable of writing such a guide. My tests look like C# translated to F#. 😄 What it takes is a very experienced F# user, with solid developer chops, who is willing to work with us both in creating guidance docs and helping us improve the interface of NUnit to F#.

Same question to you though: what would the TOC of your hypothetical tutorial look like?

**Comment by frankschmitt** [comment]
@CharliePoole For my purposes, something simple like this would suffice (similar to http://www.davesquared.net/2013/03/hello-world-testing-in-fsharp.html): 

# Installation
- download Mono
- install additional packages (FsUnit, NUnit, ...)

# A sample application
- sayHello: F#'s version of Hello, world
- compile + run sayHello

# Writing your first test
- testSayHello: a very simple testcase
- compile + run the test with the console runner

But when I look at this TOC, I realize it's probably out of scope for a NUnit tutorial - sounds more like a "Getting started with TDD in F# using the Mono command-line tools" tutorial. Or do you think this would fit into the NUnit documentation? (I'm just getting started with F#, but I would give it a try if you think that's sensible).

**Comment by jnm2** [comment]
@CharliePoole I'm just curious what the @nunit/framework-team does to run Linux Mono tests. I was thinking someone could step in and list a series of known steps that new @nunit/framework-team members can follow. Or doesn't anyone run tests on Linux? Maybe you just use Travis for that.

I just tried the Windows Subsystem for Linux route and ran into https://github.com/Microsoft/BashOnWindows/issues/1265, so that's not an option yet.

Next up: Ubuntu on Hyper-V.

**Comment by ChrisMaddock** [comment]
I just rely on Travis.

**Comment by CharliePoole** [comment]
Aside from relying on travis, we have always tried to work in a way that didn't require every developer to work on every platform. This was very noticeable in the past when we had compact framework in a separate solution. Most contributors didn't test under CF, so one of us had to do that integration. 

The same thing has been true to a certain degree with Linux. My own main machine is a Linux box, so I have done a lot of testing when it became necessary or when the issue was primarily on Linux. However that machine has been offline for a while and I only got it back up the other day.

IOW, I suggest getting things working on the platforms you have and then asking somebody else to look at the onces you don't have. 😄

**Comment by jnm2** [comment]
I finally got somewhere!

For those that like this approach:

 1. Install Docker
 2. Create file `build-mono-docker.ps1` with these contents:
    ```ps1
    if (($script = Get-Content build.sh -raw).IndexOf("`r`n") -ne -1) {
        $script | % {$_ -replace "`r`n", "`n"} | Set-Content -NoNewline build.sh
    }
    
    docker run --rm -it -v ${pwd}:/nunit -w=/nunit mono bash build.sh $args
    ```
   3. Run `./build-mono-docker.ps1 -t test` etc just like you would with `./build.ps1`.

It's seriously insane how painless this is!

**Comment by rprouse** [comment]
@jnm2, I like your docker approach. I've always tended to use an Ubuntu Hyper-V image, but it is very heavy. Lately I've been using the Windows subsystem for Linux which works well, but I worry that it is different enough that it may cause problems. I've been planning on setting up a docker container and experiment with that, but haven't had time yet. I am going to give your approach a try.

Why did you need to replace CR/LF in the build.sh script? Didn't you checkout the source from an interactive prompt from within the docker container? If that was the case, wouldn't it already be checked out with LF? Or did you mount your external source folder?

**Comment by jnm2** [comment]
I would use the Windows subsystem for Linux too except NuGet couldn't download anything (https://github.com/Microsoft/BashOnWindows/issues/1265) Did you run into that?

I replaced CRLF because I mounted the external source folder so I could run Windows and Linux tests on the same code edits both at once without having to push and pull a temporary branch every time I wanted to run tests.

It's all in this line: `docker run --rm -it -v "${pwd}":/nunit -w=/nunit mono bash build.sh $args`

| Part | |
|-----|-|
| `docker run` | Create and start a randomly named container (I didn't give it a name)
| `--rm` | Delete the container when the given command exits
| `-it` | Run the given command interactively (`-i`) with TTY (`-t`)
| `-v "${pwd}":/nunit` | Mount powershell's current directory as `/nunit` inside the container
| `-w=/nunit` | Set the given command's working directory to `/nunit`
| `mono` | Use the [`mono` base image](https://hub.docker.com/r/library/mono/)
| `bash build.sh $args` | The command to run inside the container

**Comment by jnm2** [comment]
@rprouse We could get rid of the `\n` -> `\r\n` replacement by adding this to the repo's .gitattributes file:

```
*.sh eol=lf
```

That way it gets checked out with unix line endings no matter what.

**Comment by ChrisMaddock** [comment]
@jnm2 - Is this something we could add to the cake build script? Possibly as a specific target, rather than something which is run every time.

But it'd be pretty sweet if I could to `build -t TestMono`. Like I say - I normally leave the CI to catch it!

**Comment by jnm2** [comment]
@ChrisMaddock Hmm, only if Docker is installed. The idea here is that `build-mono.docker.ps1` takes the same arguments that you used to pass to `build`. You could add a build.cake target which ran the docker command, but then you'd have to hard code which target to run in Linux. So if you ran `build -t TestMono` in Windows that could kick off Docker running the `Test` Cake target, but you'd have no way to specify that you wanted to run just the `test45` cake target in Docker instead.

**Comment by jnm2** [comment]
@ChrisMaddock What about `build -t Test -mono` and `build -t Test45 -mono`? The Cake script could check for the presence of the `-mono` argument and pass the remaining arguments to Docker.

**Comment by jnm2** [comment]
That said, I feel like Docker is only one of many approaches. If the WSL bug is fixed, I'd probably prefer that over Docker even. That's why I thought the separate `build-mono-docker.ps1` was ideal. We'd also have a `build-mono-wsl.ps1` eventually.

**Comment by jnm2** [comment]
Apparently `"${pwd}"` is no longer working, but `${pwd}` does work even with spaces and commas in the path so I updated. Together with https://github.com/nunit/nunit/issues/2136, `build-mono-docker.ps1` now becomes:

```powershell
docker run --rm -it -v ${pwd}:/nunit -w=/nunit mono bash build.sh $args
```

**Comment by jnm2** [comment]
[Added helpful behavior when Docker is not found.](https://github.com/nunit/docs/issues/163#issuecomment-297080366)

**Comment by jnm2** [comment]
Dunno, could do a whole Chocolatey bootstrapper thingy.

**Comment by ChrisMaddock** [comment]
Sure - Docker would be a requirement - but we traditionally have other builds which are just skipped if the pre-requisites aren't installed. That's what we did for Silverlight and .NET CF. 🙂 

I agree though - WSL does sound nicer, maybe we should wait and see what happens there!

**Comment by CharliePoole** [comment]
Not sure I really understand the problem you are trying to solve here. To clarify, I'll outline my understanding of how things work with Linux versus Windows.

1. Devs who use Windows develop and test on Windows. Devs who use Linux develop and test on Linux. Some of us, who use both, pick the system we want to use on a per-issue basis.
 
2. Whichever was used by the developer, the CI runs and tests under both.

3. Both locally and in the CI build, the same OS checks out the repo, builds it and runs the tests. Text files end up having the proper line endings automatically on each system.

4. Some issues are OS-specific and need to be debugged on the proper OS. Those issues are taken on by people who have the proper OS available.

This approach has always applied for me whether working on real systems or virtual systems.

I realize that the above not what you @jnm2 is trying to  do, but I wanted to outline the status quo up to this point and ask "What are you trying to change?" In the past, I have gotten into trouble trying to shortcut the process by using a direct transfer from a Linux system to a Windows system or vice versa, with the checkout only done on one of the systems. I stopped doing that for good reason.

Is there some drawback to working through Git that I am not seeing? I know we sometimes get out of sync when one of us simply doesn't understand what problem another is trying to solve.

**Comment by jnm2** [comment]
@CharliePoole Here's the series of events that I'm trying to address without the noise of committing and pushing and pulling slowing everything down:

 * Having code open in Visual Studio,
 * Making a small experimental change which affects both platforms
 * Running tests in both platforms at the same time to see what happens
 * Making a small experimental change which affects both platforms
 * Running tests in both platforms at the same time to see what happens
 * Making a small experimental change which affects both platforms
 * Running tests in both platforms at the same time to see what happens
 * etc.

**Comment by CharliePoole** [comment]
I've been in that situation over the years but only quite rarely. There are really very few things we do that require worrying about alternate platforms because CIL works the same on all of them.

However, it has come up a time or two, which is why I experimented with direct transfers - which failed. Up to now, I just created extra commits to my branch and generally squashed them away when I was done.

An alternative you might try would be to use Git on the Linux system to clone from the Windows system. That __might__ straighten out the line endings correctly, although I don't know since I haven't tried it. It's possible it won't work when you identify the source with a file path rather than a url.

Anyway, I understand your use case now. :smile:

**Comment by rprouse** [comment]
I really like the idea of using Docker for testing or working on various issues that only appear under Linux. Docker is much lighter than booting into a VM and I don't have to keep multiple machines and VMs up to date. It also allows me to test changes on both operating systems at the same time without checking in and pushing for CI to test.

I also think it will be useful tracking down issues like nunit/nunit-console#211. It will allow me to run multiple versions of Mono easily and quickly and quickly test changes.

**Comment by CharliePoole** [comment]
I think it's a good idea too and only have a hesitancy if we are starting to think of a dev strategy where every developer has to build and test under every OS. We know that doesn't scale. We should rely on our CI and on each other and continue to recruit developers who work in different platforms. In the case contributors who want to stick with one OS, we should be prepared to help them out, perhaps splitting the Linux part of the issue they are working on out separately.

**Comment by jnm2** [comment]
@CharliePoole It might be good to clarify that in the contributor documentation. Maybe we can add `build-mono-docker.ps1` to master and document that it's only for convenience and typically you'd rely on CI, so that people are aware of it but don't feel obligated to use it.

**Comment by CharliePoole** [comment]
I think that's a good idea. I recall that some folks used to get discouraged when they caused failures in the compact framework build, for example. We don't have that any more but there are other things that can't easily be tested by everyone - apple for example or windows if you are a linux user. I'd like them to know that such failures are really just a part of the process of getting things right as a team - a concept that may be foreign to some devs who have only worked by themselves in the past.

**Comment by jnm2** [comment]
Made it work independently of the current directory:

```powershell
trap [Management.Automation.CommandNotFoundException] {
  Write-Error 'Docker cannot be found. Make sure it is installed and added to the path.'
  Start-Process -FilePath 'https://docs.docker.com/docker-for-windows/install/'
  continue;
}

docker run --rm -it -v ${PSScriptRoot}:/nunit -w=/nunit mono:latest bash build.sh $args
```

Once https://github.com/nunit/nunit/pull/2140 is in master, that'll be the up to date version from then on.

**Comment by ChrisMaddock** [comment]
@jnm2 - Are you happy this is covered by your changes to https://github.com/nunit/nunit/blob/master/BUILDING.md? Or do you think there should be a separate change in docs? 🙂

**Comment by jnm2** [comment]
Yes, this is all I need for now. Once NuGet runs in Windows Subsystem for Linux, we should add docs on that as an alternative to Docker. With WSL you'll be able to test on any combination you like of Ubuntu, SUSE and Fedora.
