### ISSUE TITLE
Order Attribute missing

### ISSUE THREAD

**Issue by saydo17** [nunit/docs#166]
I'm trying to set up an order for some tests but the attribute is nowhere to be found.  It shows in the documentation [https://github.com/nunit/docs/wiki/Order-Attribute](url) and I see it in the source on here but not in Visual Studio 2013.  I added Nunit 3 from NuGet and the NUnit Test Adapter as well.

```
  [Test, Order(1)]
  public void ShouldReturnTrueForValidLicense()
```

**Comment by rprouse** [comment]
Did you close because you figured it out?
