### ISSUE TITLE
bQuestion: Can I run specific TestFixture from nunit3-console;

### ISSUE THREAD

**Issue by sisillV** [nunit/docs#167]
Hi Nunit team,
I try to run specific testFixture using Nunit Console Runner 3.4.1

D:\NUnit.org\nunit-console>nunit3-console /fixture:XXX.YY.AAAAAA.UITestAutomation.TestFixtureName  D:\TFSSpace\TeamSpaces\docs\QAUsers\UserName\XXX.YY.AAAAAA.UITestAutomation.TC\bin\Debug\XXX.YY.AAAAAA.UITestAutomation.TC.dll

And I see error:
Invalid argument: /fixture:XXX.YY.AAAAAA.UITestAutomation.TestFixtureName

**Comment by CharliePoole** [comment]
The /fixture option is from NUnit v2. Please use the NUnit 3 docs for NUnit 3: https://github.com/nunit/docs/wiki

In this case, you want the /test option.

**Comment by CharliePoole** [comment]
What are you typing at command-line? What is the result?

**Comment by facusantillo** [comment]
"C:\Repos\TestingFramework\testingframework\packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" "C:\Repos\TestingFramework\testingframework\TestingFramework\bin\Debug\TestingFramework.dll" --params=Browser=Chrome --where "cat == Regression and test == FixtureName" --result:C:/Results/xml/Regression_Chrome.xml

The point is I want to retrieve only the test having [TestFixture("FixtureName")] on the class name. I read the documentation and it's not clear about TestFixtures

**Comment by mikkelbu** [comment]
If you type `[TestFixture("FixtureName")]` then you are passing the argument `FixtureName` to the TestFixture. Instead you can filter on the class name `... --where 'cat == Regression and class =~ "My.Namespace.ClassName"'...` (see https://github.com/nunit/docs/wiki/Test-Selection-Language for more info)

**Comment by CharliePoole** [comment]
An argument to test fixture is an argument to the test fixture constructor. It creates what we call a parameterized fixture. Usually, people parameterize a fixture by passing in something like the type of browser to be used. You appear to be using it solely to give the fixture a changeable name and select the fixture. There are better ways to do that.

When a fixture has a parameter, the name of the test is something like Full.Path.To.ClassName("PARAMETER"). Of course, you can use that to select the test, but it's much simpler to give the fixture Category and select on that basis UNLESS you have a real reason for parameterizing the fixture (not just selection). 

Of course, if your fixtures are entirely unrelated, as is normal, you can simply give each of them a separate name - that is, the name of the class.
