### ISSUE TITLE
Unknown specifier on Test Name Generation Spec page

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#169]
https://github.com/nunit/docs/wiki/Generation-of-Test-Names-Spec

At the bottom of this page, there is the note:

> Note that in this usage, it will generally only make sense to use {m}, {a} or {o} specifiers. 

The `{o}` option doesn't seem to exist, either in spec of code. Was this intended for something, or is ok just to remove the reference? @CharliePoole? I think you generally have the best memory for such history!

While I was here, it looks like this page is pretty docs-ready - a couple of things perhaps want rewording to move from spec to docs, but as far as I'm aware, the actual info is complete. I can move it over and remove the 'in progress' notice - is anyone aware of anything missing?

**Comment by ChrisMaddock** [comment]
(Just found #38 for the move to docs - given my specific question here, I'll keep both issues open for now, and tidy up when it's done.)

**Comment by CharliePoole** [comment]
The `{0}` refers to an earlier way of designating individual arguments: `{o1}`, `{o2}`, etc. I fixed it.

**Comment by CharliePoole** [comment]
I put your name on #38.
