### ISSUE TITLE
Unclear Documentation for CollectionContainsConstraint

### ISSUE THREAD

**Issue by lundmikkel** [nunit/docs#17]
I'm very unsure of the actual behavior of the [CollectionContainsConstraint](https://github.com/nunit/docs/wiki/CollectionContainsConstraint) after reading the documentation.

The note at the bottom says the following:

> For references, `Has.Member` uses object equality to find a member in a collection. To check for an object equal to an item **[in?]** the collection, use Has.Some.EqualTo(...)`.

I'm not able to say how these two differ. When I first read it, I though that `Has.Member`used reference equality, but that is wrong – this is however clear from **Examples of Use**.

So how do they differ? And how do you check if the collection contains an object that is reference equal to the provided object?

**Comment by CharliePoole** [comment]
Your right, the note is just a bit of ancient history. See the new note I created.
