### ISSUE TITLE
Added some missing braces on the EqualConstraint wiki page

### ISSUE THREAD

**Issue by lennartb-** [nunit/docs#170]
[patch.diff.txt](https://github.com/nunit/docs/files/792851/patch.diff.txt)

Since you can't PR wiki pages, I attached a diff. There were some closing braces missing in the Assert examples

**Comment by SamJongenelen** [comment]
I've processed your changes on the page. Thank you

**Comment by CharliePoole** [comment]
@lennartb- I invited you as a contributor, which would give you the ability to edit the wiki. If you change anything substantial, please post an issue to ask one of us to review it.

**Comment by lennartb-** [comment]
Will do, thanks!
