### ISSUE TITLE
Multiple .net core tests projects means some tests don't appear

### ISSUE THREAD

**Issue by jessewhite007** [nunit/docs#171]
Appears to be this issue which was fixed at some point?
https://github.com/nunit/dotnet-test-nunit/issues/58

**Comment by dougkpowers** [comment]
This was fixed in dotnet-test-nunit Beta-3

There was a similar issue (https://github.com/nunit/dotnet-test-nunit/issues/87) that has been fixed, but not released.  Maybe we can nudge @rprouse for a final release of dotnet-test-unit while we await all the newest tooling via VS17
