### ISSUE TITLE
Clarify use of IgnoreAttribute with TestCaseAttribute

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#172]
@darthKwisatzHaderach commented on [Thu Sep 17 2015](https://github.com/nunit/nunit/issues/815)

Hi,

I have six test cases. I want to ignore two of them. When I do it as described below, I get error "Duplicate Ignore attribute.

```
[TestCase("03/03/20166"), Ignore("PRX-1000")]
[TestCase("03 03/2016"), Ignore("PRX-1000")]
[TestCase("0303/2016")]
[TestCase("033/03/2016")]
[TestCase("03/033/2016")]
[TestCase("03/03/201")]
public void InvalidDeadlineDateFormat(string dateFormat) {}
```

I am not exactly understand how to ignore these tests. Maybe it is a bug?

NUnit Version 3 3.0.0-beta-4

Best regards, Dmitrii

---

@rprouse commented on [Thu Sep 17 2015](https://github.com/nunit/nunit/issues/815#issuecomment-141094831)

Sounds like a bug to me :)

---

@darthKwisatzHaderach commented on [Thu Sep 17 2015](https://github.com/nunit/nunit/issues/815#issuecomment-141113190)

The same situation with NUnit 2.6.4.14350

---

@CharliePoole commented on [Thu Sep 17 2015](https://github.com/nunit/nunit/issues/815#issuecomment-141127973)

Actually, it's not a bug, but I'll warrant it's confusing. Here is what happens:

The textual layout of your attributes means nothing to .NET. When you use

``` C#
   [TestCase("03/03/20166"), Ignore("PRX-1000")]
   [TestCase("03 03/2016"), Ignore("PRX-1000")]
   [TestCase("0303/2016")]
```

it's just the same as

``` C#
   [TestCase("03/03/20166")]
   [Ignore("PRX-1000")]
   [TestCase("03 03/2016")]
   [Ignore("PRX-1000")]
   [TestCase("0303/2016")]
```

Or even...

``` C#
   [TestCase("03/03/20166")]
   [TestCase("03 03/2016")]
   [TestCase("0303/2016")]
   [Ignore("PRX-1000")]
   [Ignore("PRX-1000")]
```

The ignore attributes apply to the method and so would cause every test case to be ignored. But since you had two of them, you got a compiler error instead.

Since you are trying to ignore the individual test cases, you want this:

``` C#
   [TestCase("03/03/20166", Ignore="PRX-1000")]
   [TestCase("03 03/2016", Ignore="PRX-1000")]
   [TestCase("0303/2016")]
```

Here, the "Ignore" is a named property of the TestCase attribute. We made the named property match the name of the IgnoreAttribute because they serve the same purpose, but I can see that this creates confusion as well.

---

@rprouse commented on [Thu Sep 17 2015](https://github.com/nunit/nunit/issues/815#issuecomment-141128469)

@CharliePoole, good catch, I totally missed the fact that the Ignore wasn't inside the TestCase.

---

@darthKwisatzHaderach commented on [Thu Sep 17 2015](https://github.com/nunit/nunit/issues/815#issuecomment-141129718)

Thanks for the detailed explanation!

---

@mateusz-dobrowolny commented on [Mon Feb 27 2017](https://github.com/nunit/nunit/issues/815#issuecomment-282766849)

Please add this example to the documentation:
   [TestCase("03 03/2016", Ignore="PRX-1000")]
https://github.com/nunit/docs/wiki/Ignore-Attribute

It is hard to search here for the solution, and the usage is far from obvious... :)
Thanks!

---

@CharliePoole commented on [Mon Feb 27 2017](https://github.com/nunit/nunit/issues/815#issuecomment-282776550)

Moving this to the documentation repository.

I think we need to figure something out here, but putting an example like yours on the IgnoreAttribute page seems strange, since it's not an example of the IgnoreAttribute, but of the Ignore property of TestCaseAttribute. Perhaps what we need is a section that explains how IgnoreAttribute actually works when used with a TestCase.

**Comment by mateusz-dobrowolny** [comment]
You are right - there is an "Ignore" attribute for TestCase.
https://github.com/nunit/docs/wiki/TestCase-Attribute

When I searched the Wiki, I just put "Ignore" into search field, and I was redirected to the ignore attribute 
https://github.com/nunit/docs/wiki/Ignore-Attribute
rather then 'Ignore' property for TestCase.

Limitation of GitHub search (results containing words "ignoring", "ignored", "ignore" are mixed up even if I am looking for "ignore") may be also a reason.

Maybe "examples" section for some common use cases (personally I like very much the shape of documentation used in PowerShell, see for exaple https://msdn.microsoft.com/en-us/powershell/reference/3.0/microsoft.powershell.management/remove-item#examples)
would be usefull...

**Comment by ChrisMaddock** [comment]
I added the below note to the IgnoreAttribute page. Let me know if people think it could be improved:

> Note that the Ignore Attribute is attached to a method. If you have multiple Test Case Attributes on one method, adding an Ignore Attribute will ignore all test cases. To ignore individual test cases, use the Ignore named parameter on the [[TestCase Attribute]].

**Comment by CharliePoole** [comment]
@ChrisMaddock Since we are telling them about TestCaseAttribute, I figured we should add TestCaseSource as well. I split the info out into a separate section of the page. Feel free to edit further.
