### ISSUE TITLE
VS test adapter doesn't add CodeLens for parametric tests

### ISSUE THREAD

**Issue by cmeeren** [nunit/docs#174]
I have installed the NUnit 3 Test Adapter for VS2015. It successfully runs all the tests, including parametric tests. But for some reason, CodeLens icons are not added to parametric tests, and the "x/y passing" thingy above the tested methods do not include parametric tests.

![capture](https://cloud.githubusercontent.com/assets/7766733/23542136/c9a692ba-ffeb-11e6-8e3b-aa2392b485d7.PNG)

![capture2](https://cloud.githubusercontent.com/assets/7766733/23542172/0059ca02-ffec-11e6-82b1-b47a4c2c7343.PNG)

**Comment by ChrisMaddock** [comment]
This is a know issue - and unfortunately seems to be a limitation of CodeLens.

See: 
https://github.com/nunit/nunit3-vs-adapter/issues/55
https://github.com/nunit/nunit-vs-adapter/issues/105

I'll close this issue as a duplicate - shout if I've missed something.

**Comment by cmeeren** [comment]
Too bad, but such is life.

Let me just add that it also happens when using `[Values]` for the test method parameters instead of `[TestCase]`.

**Comment by tparikka** [comment]
If anyone still watching this issue wants to raise this to Microsoft, I've added a Uservoice request for it at the request of Microsoft's social media team as they told me they had no previous requests for this enhancement.

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/18701998-codelens-doesn-t-detect-parameterized-nunit-tests

**Comment by OsirisTerje** [comment]
Thanks!  I've made the product group aware of that uservoice link.  (They - the right people - are already aware of the issue itself, it has been raised before)
