### ISSUE TITLE
RandomAttribute for string Generation

### ISSUE THREAD

**Issue by mbcrawfo** [nunit/docs#175]
[RandomAttribute](https://github.com/nunit/docs/wiki/Random-Attribute) documentation seems to indicate that the it supports generating values for any type with supported by `Randomizer`, when using the *count* constructor.  However, using it on a string parameter results in an `Int32` being generated, causing an `ArgumentException` when invoking the test method.

Unsure if this an oversight in the behavior of `RandomAttribute` or just documentation that needs to be clarified.

**Comment by CharliePoole** [comment]
The docs were correct when we first created them but became incorrect after the `GetString` methods were added to `Randomizer`. 

`RandomAttribute` definitely does not support a string. I modified the documentation page to indicate that it applies to numeric parameters.

If you want to propose a change that will support random string argument generation, please create an issue in the nunit/nunit repository. I think we would probably need something more than just the count argument for must use cases.
