### ISSUE TITLE
Create Release Notes for the Console/Engine

### ISSUE THREAD

**Issue by rprouse** [nunit/docs#176]
Now that the console and engine are built and released separately, the release notes for them should be broken out from the framework.

To make maintaining all of the release notes easier, should the release notes page just link to the CHANGES.txt (or md) files in each repo?

**Comment by CharliePoole** [comment]
I agree with splitting the release notes and perhaps even the docs themselves.

I don't think we should point the release notes to the changes files, which don't actually exist in every project anyway. There is currently structure in the release notes that doesn't exist in the changes files. If we felt there was redundancy, I'd rather get rid of the changes files.

In any case, I think this should be up to each project. I don't think we should make a "rule" about it that applies to all projects.

**Comment by CharliePoole** [comment]
As a quick solution for this release, How about modifying the menu like this...

```
NUnit
   Release Notes
      Framework
      Console Runner and Engine
   License
   ....
```

The new pages for framework and console could end with a link to the old page labeled "Older versions combining both framework and console"

**Comment by rprouse** [comment]
That looks good to me.

**Comment by CharliePoole** [comment]
I updated. See what you think.

**Comment by rprouse** [comment]
Looks great to me. Closing.
