### ISSUE TITLE
Visual Studio Test Adapter (NUnit 2) Crashes, Will Not Run or Debug Tests

### ISSUE THREAD

**Issue by DarthGregarious** [nunit/docs#177]
I tried to run tests in Visual Studio 2015 for the first time since the latest adapter extension update. In one of my solutions, it just crashes. I am using NUnit 2.6.4 with the latest Visual Studio adapter and targeting .NET 4.5. 

When debugging a test, it starts to run, but it stops abruptly when it says "loading symbols for Mono.Cecil..."

I found an older issue that suggested adding an ".addins" file to the output directory, so I tried that but it didn't help.

Whether "Running" or "Debugging" a test, "Test Output" includes:
Dependent Assembly  of C:\projects\...Tests.dll not found. Can be ignored if not a NUnit project.

Debug Output:
![image](https://cloud.githubusercontent.com/assets/7608479/23803183/b6e39a22-0583-11e7-88f4-33f95aff1799.png)
![image](https://cloud.githubusercontent.com/assets/7608479/23803200/c7c29c62-0583-11e7-8205-1e74b390cf49.png)

**Comment by DarthGregarious** [comment]
I should add that I tried a smaller solution, and it works just fine - running and debugging. It still has the "Cannot find or open the PDB file." errors but it does not have the "Dependent Assembly..." warning. I also used the separate NUnit desktop program with no problems.

**Comment by DarthGregarious** [comment]
`NUnit VS Adapter 2.1.0.7 executing tests is started
Loading tests from C:\projects\...Tests.dll
Dependent Assembly  of C:\projects\...Tests.dll not found. Can be ignored if not a NUnit project.
NUnit VS Adapter 2.1.0.7 executing tests is finished`

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit-vs-adapter #143](https://github.com/nunit/nunit-vs-adapter/issues/143) via [**ZenHub**](https://www.zenhub.com/)
