### ISSUE TITLE
Broken header formatting

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#178]
I'm not sure when, but GitHub seems to have changed it's markdown formatting to require a space after the hashes, for a header. This has broken a significant amount of the header formatting in the wiki.

Fingers crossed its a temporary bug, and not a permanent change. If not, I guess we can bulk replace.

![image](https://cloud.githubusercontent.com/assets/4837132/23926163/92c16f4a-090a-11e7-8a6f-91db26e12588.png)

**Comment by jnm2** [comment]
I bet this si when it happened: https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown

**Comment by ChrisMaddock** [comment]
Ugh, thanks @jnm2 - I had a quick google at the time, but couldn't find any such GitHub news release. Guess it won't be changing back then.

I leave on holiday tonight, so won't be able to sort it now. Will have a look when I'm back, if nobody else can get to it first.

**Comment by jnm2** [comment]
Apparently you can git clone the wiki, then NotePad++ could do a regex replace of `(^#+)\s*(?=[^#\s])` with `$1 ` across all files. Seems to work, maybe I'll give it a try.

**Comment by jnm2** [comment]
Yup, I'm looking over the result and it seems to be exactly what I hoped. It's added a single space between the hashes and the header text in all .md files.

**Comment by jnm2** [comment]
Saw a file with headers like this:

```markdown
###Text##
####Text###
```

Those ending hashes should disappear or at least also be spaced away from the text, or we'll have:

### Text##
#### Text###

**Comment by jnm2** [comment]
Replacing `(^#+.*?)(\s*#*$)` with `$1` seems to work for that.

**Comment by jnm2** [comment]
@ChrisMaddock I'm really scared because I just pushed this to the wiki. Wiki PRs aren't supported. Everything looks good though. Before I pushed, I checked every sidebar and multiple random files in each folder. I think I got everything and didn't mess anything up.

**Comment by ChrisMaddock** [comment]
Awesome, thanks @jnm2! 😄 

It all looks good to me - I can't find anything stray. 👍

**Comment by CharliePoole** [comment]
@jnm2 Pushing is how we do it for the occasional major change, so don't worry. We have the history of we need it thanks for doing this.
