### ISSUE TITLE
Release Notes for 3.6 and 3.6.1 missing

### ISSUE THREAD

**Issue by dnperfors** [nunit/docs#181]
I just noticed that the Release notes for version 3.6 and 3.6.1 are missing. Looking into the history of the page, it seems that they are accidentally removed?

**Comment by CharliePoole** [comment]
Starting with NUnit 3.6, the framework and console/engine are released separately and so have separate Release Notes. If you start from the wiki right-hand menu, you'll be taken to the right place. The old Release Notes page has the combined notes through NUnit 3.5.

Did you follow a link of ours to the release notes? If so, we should change it.

Additionally, I guess it was an error that I didn't rename the old Release Notes page and create a landing page for those following older links. I'll fix that.

**Comment by CharliePoole** [comment]
Fixed: Release Notes is now a landing page that directs the user to select either the Framework or the Console Release Notes. The old Release Notes page is now called Pre 3.5 Release Notes.
