### ISSUE TITLE
nunit3 can't find assembly

### ISSUE THREAD

**Issue by brian-kane521** [nunit/docs#185]
I have an assembly, SomeAssembly.dll that I've created tests for (SomeAssembly.Test.dll).  This assembly depends on another library, Dependency.dll and anytime I try to run my unit tests (nunit3-console.exe SomeAssembly.Test.dll) I get a System.IO.FileNotFoundException: Could not load file or assembly 'Dependency.dll'. 

This occurs both in NUnit3 in Visual Studio, where I am certain I have all of my references properly sorted, and it also happens when using Nunit console from the command line.  I've tried adding/deleting references, with and without local copy, I've tried copying nunit-console in the bin/Release/ directory and running it from there, and I've tried copying the Dependcy.dll into nunit-consoles working directory but for some reason it still fails to find it.

The only workaround I've found is installing Depency.dll into the GAC, but this is not acceptable for our production CI environment.  I've seen some similar issues online, but none that seem to exactly match mine, and none of the solutions I've tried have resolved my problem.

Any thoughts/assistance would be greatly appreciated!

**Comment by rprouse** [comment]
That is a pretty common scenario that should work. Is the Dependency.dll copied into your tests bin directory along with SomeAssembly.dll and SomeAssembly.Test.dll? All should be in that directory if your references are setup correctly.

If they are there, is there something special about Dependency.dll? For example, does it call out to a native assembly that is not in the test directory?

**Comment by brian-kane521** [comment]
Thanks for the reply, Dependency.dll and all of it's dependencies are copied into the test bin directory. I'm pretty confident that isn't the issue, I've checked all references in the Dependency.dll project and made sure they are all present.  It's very mysterious... I don't think there's anything special about Dependency.dll, and it only references one third party library which is definitely present.  

Additionally, since the problem is circumvented by adding Dependency.dll to the GAC, that suggests to me NUnit isn't struggling to resolve any of the references made by Dependency.dll - only the library itself, even though it's present right next to it.  Are there any traits of a class library which might make it "undiscoverable" to NUnit that you know of? I'm totally at a loss.

**Comment by jnm2** [comment]
Can you run https://msdn.microsoft.com/en-us/library/e74a18c4.aspx?

**Comment by brian-kane521** [comment]
I got the following entry in the log:
*** Assembly Binder Log Entry  (3/30/2017 @ 2:52:07 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = NUnit3.TestAdapter
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: NUnit3.TestAdapter | Domain ID: 1
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = vstest.executionengine.x86.exe
Calling assembly : Microsoft.VisualStudio.TestPlatform.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/NUnit3.TestAdapter.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/NUnit3.TestAdapter/NUnit3.TestAdapter.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/NUnit3.TestAdapter.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/NUnit3.TestAdapter/NUnit3.TestAdapter.DLL.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/NUnit3.TestAdapter.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/NUnit3.TestAdapter/NUnit3.TestAdapter.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/NUnit3.TestAdapter.EXE.
LOG: Attempting download of new URL file:///C:/PROGRAM FILES (X86)/MICROSOFT VISUAL STUDIO/2017/COMMUNITY/COMMON7/IDE/COMMONEXTENSIONS/MICROSOFT/TESTWINDOW/Extensions/NUnit3.TestAdapter/NUnit3.TestAdapter.EXE.
LOG: All probing URLs attempted and failed.


This makes it look like NUnit itself is failing to load, but it's running the test and failing at runtime to load the Dependency.dll

**Comment by jnm2** [comment]
Stranger and stranger. In these scenarios it's hard to do anything without a simplified repro we can build and run.

**Comment by brian-kane521** [comment]
I was afraid that might be the case, and thank you guys for your help.  If there's any other info I can provide/ things to try etc. just let me know

**Comment by brian-kane521** [comment]
Ah, for what it's worth I now found this in the Binding log

*** Assembly Binder Log Entry  (3/30/2017 @ 3:00:13 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.x86.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = MediaVueLibrary, Version=1.7.0.0, Culture=en-US, PublicKeyToken=3f02000659c13c7d
 (Fully-specified)
LOG: Appbase = file:///C:/Users/bkane/Documents/Visual Studio 2017/Projects/NetworkManagementLibrary/NetworkManagementLibrary.Test/bin/Release/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = Tests_1178968
Calling assembly : NetworkManagementLibrary, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\bkane\Documents\Visual Studio 2017\Projects\NetworkManagementLibrary\NetworkManagementLibrary.Test\bin\Release\NetworkManagementLibrary.Test.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: MediaVueLibrary, Version=1.7.0.0, Culture=en-US, PublicKeyToken=3f02000659c13c7d
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Users/bkane/Documents/Visual Studio 2017/Projects/NetworkManagementLibrary/NetworkManagementLibrary.Test/bin/Release/en-US/MediaVueLibrary.DLL.
LOG: Attempting download of new URL file:///C:/Users/bkane/Documents/Visual Studio 2017/Projects/NetworkManagementLibrary/NetworkManagementLibrary.Test/bin/Release/en-US/MediaVueLibrary/MediaVueLibrary.DLL.
LOG: Attempting download of new URL file:///C:/Users/bkane/Documents/Visual Studio 2017/Projects/NetworkManagementLibrary/NetworkManagementLibrary.Test/bin/Release/en-US/MediaVueLibrary.EXE.
LOG: Attempting download of new URL file:///C:/Users/bkane/Documents/Visual Studio 2017/Projects/NetworkManagementLibrary/NetworkManagementLibrary.Test/bin/Release/en-US/MediaVueLibrary/MediaVueLibrary.EXE.
LOG: All probing URLs attempted and failed.

**Comment by brian-kane521** [comment]
MediaVueLibrary is my Dependency.dll, so we can see it's failing to find this.

**Comment by jnm2** [comment]
Fyi, you can prevent logs being interpreted as markdown and make them easier to read by formatting them as a code block by fencing with three or more backticks:

````markdown
```
*** Assembly Binder Log Entry (3/30/2017 @ 3:00:13 PM) ***
```
````

**Comment by jnm2** [comment]
It says your app base directory is `file:///C:/Users/bkane/Documents/Visual Studio 2017/Projects/NetworkManagementLibrary/NetworkManagementLibrary.Test/bin/Release/`, but it's trying to load `en-US/MediaVueLibrary.DLL` from there. I haven't seen that before, I wonder where the `en-US` is coming from?

**Comment by brian-kane521** [comment]
If I manually add an en-US folder to the bin folder and put MediaVueLibrary in there, the test now runs successfully! I've taken a look at the Assembly properties and for some reason the Neutral Language is set to English (US) instead of the default (None) - I'm guessing this must be the root of the issue.  I wonder if this same situation would occur for any assemblies referencing a library with a different culture.  Thank you so much, this was driving me insane!
