### ISSUE TITLE
Can not found any test if test is inherited from TestKit of Akka.Net

### ISSUE THREAD

**Issue by chambeer** [nunit/docs#186]
I try to reinstall test adapter, change x86-x64 proc arch, restart pc and visual studio. Nothing changed. If i delete TestKit inherited, all is fine, tests visible and working. I check VS 2015 and 2017. All of installed nuget and extensions have latest version. Test explorer is empty. WHAT wrong with adapter????

**Comment by SamJongenelen** [comment]
You have nunit3 adapter as VsExtension and also the nugetpackage for nunit3? Or just the adapter?

**Comment by ChrisMaddock** [comment]
Closing as there's insufficient information here to take this further. We can reopen if @chambeer has further information to provide. 🙂
