### ISSUE TITLE
Link to Pre 3.5 Release Notes on Console Release Notes page incorrect

### ISSUE THREAD

**Issue by jasonruz** [nunit/docs#187]
On https://github.com/nunit/docs/wiki/Console-Release-Notes#earlier-releases the link in the text saying:
> Release Notes for NUnit 2.9.1 through 3.5

should link to https://github.com/nunit/docs/wiki/Pre-3.5-Release-Notes instead of the Release Notes page.

**Comment by CharliePoole** [comment]
Thanks!
