### ISSUE TITLE
PCL Profile not Compatible

### ISSUE THREAD

**Issue by emmanuele-villa** [nunit/docs#188]
Hi! I'm trying to add the nuget.xamarin package to a PCL project with profile 259, because I saw in the nuget gallery that it's the profile to be used (https://www.nuget.org/packages/NUnit/) but I have this error:

> Could not install package 'nunit.xamarin 3.6.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm using Visual Studio for Mac and I've added the NUnit package with no problems.
I've tried also all other PCL profiles with .net 4.5 but with no luck: I can't find a compatible profile.
This error also comes up in Xamarin Studio.
Thanks for your help

**Comment by rprouse** [comment]
@emmanuele-villa you closed this. Can you add an update in case other people run into the same problem?

**Comment by emmanuele-villa** [comment]
@rprouse Sure, I've downloaded the unit3-console executable and successfully ran the tests without adding the xamarin runner package, so I thought that this was simply not needed on a PCL project. On the android and ios tests I've successfully added and used it!
