### ISSUE TITLE
Update SetUp and Teardown changes doc

### ISSUE THREAD

**Issue by tom-dudley** [nunit/docs#191]
Similar to https://github.com/nunit/nunit/issues/2158 I recall reading [this page](https://github.com/nunit/docs/wiki/SetUp-and-TearDown-Changes) and finding
> OneTimeSetUpAttribute is used for one-time setup.

not the most enlightening. (I'm still a bit fuzzy on what this actually does, I assume it's run once per assembly, per namespace or per fixture depending on which you are applying the attribute to.)

**Comment by rprouse** [comment]
You are correct in your assumption. That is the problem when we write our own docs already knowing what something does 😄

**Comment by SamJongenelen** [comment]
I've added an extra sentence, although the name itself states exactly what it does already.

@tom-dudley what do you think? 
https://github.com/nunit/docs/wiki/SetUp-and-TearDown-Changes

**Comment by CharliePoole** [comment]
This page doesn't actually read like a doc, but like a spec that was used when we developed NUnit 3. Is it actually linked from anywhere? Do we need a page that describes how we changed SetUp and TearDown from NUnit 2 to NUnit 3 at this stage of things?

**Comment by CharliePoole** [comment]
@SamJongenelen Unfortunately, "once per test run" is not strictly correct, since the method could be used in multiple fixtures by virtue of inheritance. However, now that I have noticed this issue, let's figure out whether we need this page at all first. I originally wrote it to describe what changes we were going to make in NUnit 3 as compared to V2.

If we do feel we need a general description of how the various setup and teardown methods relate, it should probably be linked from https://github.com/nunit/docs/wiki/Usage-Notes. Also, should the comparison with V2 be retained or should the page just talk about NUnit 3?

@nunit/framework-team What do you think?

**Comment by jnm2** [comment]
I think more clear and discoverable documentation is a good thing. It seems like it's been long enough since v2 that I wouldn't guess an upgrade spec to be of interest, but I may be completely wrong on that.

**Comment by SamJongenelen** [comment]
@charliepoole personally, I would like to see all references/conparisons to non Nunit3 deleted.

**Comment by CharliePoole** [comment]
Do we have any consensus as to whether any part of this document is needed and - if so - where it should go? Otherwise, we should delete it as we did with most other implemented specs.

**Comment by ChrisMaddock** [comment]
This page is only linked from the Breaking changes, right? I think this is part of that content.

Looking at the last six weeks of downloads, I'd guess NUnit 2.X still makes up 25-30%? I think we need to maintain our 'breaking changes' docs for some time yet.

https://www.nuget.org/stats/packages/NUnit?groupby=Version

**Comment by CharliePoole** [comment]
@ChrisMaddock I didn't know it was liked form anywhere! Since we are trying to get rid of the specs, I guess it should move to the nunit section of the wiki. Since it's a breaking change, I guess we keep the comparison to 2.x in the text.

**Comment by CharliePoole** [comment]
Freeing this up for others to work on for now.

**Comment by tom-dudley** [comment]
I see I'd been using the spec as a doc since I couldn't find a better overview of setup/teardown. I've gone and made a new page which is basically the same but with all the NUnit 2 specific text stripped out. Hopefully this will give a more user friendly overview of setup and teardown.

https://github.com/nunit/docs/wiki/SetUp-and-TearDown

**Comment by CharliePoole** [comment]
Thanks for doing this @tom-dudley! 

I moved the new file to the nunit directory, so it would get the correct sidebar menu. It's not possible to create new files in the right place using the wiki itself, so we just do it afterwards.
