### ISSUE TITLE
NUnit Roadmap page out of date

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#195]
https://github.com/nunit/docs/wiki/NUnit-Roadmap

This page was last updated pre-v3.0. I'd like to decide what to do with it, and tidy up. 😄 

I suggest we simply get rid of it. My experience is that, in practice, we don't currently operate with a long-term 'roadmap' - and more deal with individual issues as and when they are raised, and when demand is sufficient.

What do people think?

**Comment by JustinRChou** [comment]
I am curious to see what would be in a 4.0 road map.
But I think it should be removed and  
https://github.com/nunit/docs/wiki/NUnit-Vision
be updated.

**Comment by CharliePoole** [comment]
@ChrisMaddock I'd say drop it. If the core team wants a global roadmap, I'd recommend putting it in the governance repo, but I think it makes more sense to let each project do one if they think they need it.

@JustinRChou The vision is something we will be taking up shortly in the core team. I'd like to hear what you think ought to be updated about it. Note that anybody can follow the issues we bring up for the core team in the governance repo and comment on them. The volume is low so subscribing to issues shouldn't cause you much pain.

**Comment by JustinRChou** [comment]
Oh, did not notice the new governance repo.
I was thinking that the major plans for future updates would be maintained in the Future Vision instead.

**Comment by ChrisMaddock** [comment]
Done, thanks. 👍
