### ISSUE TITLE
--Where does not filter results of --Explore

### ISSUE THREAD

**Issue by HuntaKiller** [nunit/docs#196]
using the --where command works for filtering which tests are run, however, expected functionality of combining the two commands would be to just print out the tests which match the Where conditions. When combining the two command line arguments, --where is ignored if --explore is used. This is an issue with how we have our swarm running tests as we are moving from V2.X to V3. Would love a fast fix!

**Comment by ChrisMaddock** [comment]
This has recently been implemented in the master, and will be released as part of NUnit 3.8. We're hoping to release 3.8 next week - providing nothing holds it up. 🙂
