### ISSUE TITLE
Document Assert.Positive and Assert.Negative

### ISSUE THREAD

**Issue by mikkelbu** [nunit/docs#198]
Should go on the Classic Model page (link https://github.com/nunit/docs/wiki/Classic-Model)

**Comment by SamJongenelen** [comment]
I've made a basic page for the two asserts;

https://github.com/nunit/docs/wiki/Assert.Negative
https://github.com/nunit/docs/wiki/Assert.Positive

and added both entries to the Classic Model page.

@CharliePoole do you agree with the changes?

**Comment by mikkelbu** [comment]
Hi @SamJongenelen 

I got the following comment on #120, and I think that you have made the same mistake I did :)

> @mikkelbu - compare your pages to Assert.True - you see the sidebars different? I'm assuming you created these pages using the "New Page" button on the web interface?
> 
> Unfortunately that button doesn't really work with out directory structure. 👎 To fix this, you'll need to clone the wiki repo to your local machine, like a normal git repo (https://github.com/nunit/docs.wiki.git). Once you've done that, you'll see your new pages are in the root directory. If you move them to /nunit/ and push, they will instead pick up the sidebar in the /nunit/ subdir, which is what you see on all the other assertion pages.
> 
> You won't need to change any links - subdirectories are ignored in the linking structure. Also, don't worry about branching/PRs or whatever - there's no PR system for wiki's, so everything just gets pushed to master. It's not the best system, for changes like this, unfortunately.
> 
> Let us know if you have any problems, and I can fix it. 🙂

**Comment by SamJongenelen** [comment]
Ahh. That's unfortunate. I'll try and see if I can fix that

**Comment by CharliePoole** [comment]
Yes, this has to be done with every new page. If it gets complicated, feel free to ask someone else to do it! 😄

**Comment by SamJongenelen** [comment]
Well, I didn't get to it, so if someone could do it quickly, please make it so

**Comment by mikkelbu** [comment]
I can do it tonight

**Comment by CharliePoole** [comment]
I think so. We can iterate in the wiki if we need to.

**Comment by mikkelbu** [comment]
Closed and thanks for the contribution @SamJongenelen
