### ISSUE TITLE
Issue template for nunit/docs

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#201]
I'm it hasn't escaped any of you how easy it is for people to accidentally post issues here. GitHub doesn't naturally lend itself to making it obvious where you should go.

I propose an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) roughly similar to the following:

-----

If you have an issue with the test framework, go to: https&#58;//github.com/nunit/nunit/issues/new
If you have an issue with the console runner, go to: https&#58;//github.com/nunit/nunit-console/issues/new
If you have an issue with the VSTest adapter, go to: https&#58;//github.com/nunit/nunit3-vs-adapter/issues/new

If you have an issue with the wiki and the documentation itself, stay here and delete these lines.
If you have an issue with another component, go to: https&#58;//github.com/nunit#org-repositories

-----

What does the @nunit/core-team think?

**Comment by CharliePoole** [comment]
Is this more suitable for the contribution guidelines that appear on top of the page when you add new issue?

**Comment by jnm2** [comment]
> Is this more suitable for the contribution guidelines that appear on top of the page when you add new issue?

The only reason I'd say no is that I don't think it would have the effect we want. The goal of the issue template is to be more preventative of a very specific accident where people are not aware of which repository they are in and which they should be in, which is to save ourselves work and keep things clean.  The contribution guidelines link is a little less preventative and would look exactly the same in every repo and not really grab your attention once you've read it in one repo. I'm embarrassed to say it but my reaction was, "guidelines appear on top of the page?"

**Comment by CharliePoole** [comment]
@jnm2 Oh... I thought the contribution guidelines were different for each repo.

I just checked... they are. 😄 

However, it's a link you have to click, which goes to Guidelines.md in the root of the repo. We have one for the nunit repo for example. A template is more "in your face" obviously. I merely dislike that they have to erase the block to actually submit an issue. We can try it and see how it goes anyway.

**Comment by jnm2** [comment]
@CharliePoole I said that with the understanding that they _are_ different in each repo, but also being conscious of the fact that we are addressing a scenario where the user is not thinking about which repo they are in.

I agree about the delete being slightly annoying, and yet it's just the other side of the awareness coin.
We could suggest <kbd>Ctrl</kbd><kbd>A</kbd>, <kbd>Delete</kbd> for Windows users?

**Comment by CharliePoole** [comment]
I say do it, try it, change it if necessary.

**Comment by jnm2** [comment]
I'm leaning towards putting it at `/.github/issue_template.md` but `/issue_template.md` also works. Thoughts?

**Comment by jnm2** [comment]
This is something we'll maybe want to keep consistent across repos.

**Comment by ChrisMaddock** [comment]
Sounds great. I'd go for the subdirectory - one day we may want pull request templates etc. too - and some roots are pretty full.

**Comment by jnm2** [comment]
Well, [this is what it looks like]9https://github.com/nunit/docs/pull/202).
