### ISSUE TITLE
How to install NUnit with monodevelop?

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/docs#203]
Installation instruction
https://github.com/nunit/docs/wiki/Installation
doesn't contain steps for installing nunit in monodevelop (it says only about visual studio)

**Comment by rprouse** [comment]
@ArsenShnurkov if you would like to add documentation, we would be happy to help get it posted. Most Mono users are comfortable with the command line, so just run their tests using `nunit3-console.exe`. I am not sure if there is an NUnit test adapter for MonoDevelop or if MonoDevelop supports the Visual Studio style of adapter.

**Comment by CharliePoole** [comment]
@rprouse I think he means the framework. The very first line of how to install the nuget framework package mentions VS. Maybe we should not do that so prominently, but give the nuget command line for installing and add "or use your IDE to install the package."

In the case of the adapter, there is no equivalent for monodevelop. Integration uses their own type of extension based on Mono.Addins and there is no NUnit 3 version of it. It's something I've considered working on after I depart this project.

**Comment by CharliePoole** [comment]
@ArsenShnurkov If you meant the framework, just install it in your project as you would any other extension. You can install the console the same way. However, if you mean monodevelop integration, i.e. running tests in a panel of monodevelop, then I don't believe that is available. Using integrated nunit testing, you are limited to whatever version of nunit the monodevelop guys bundle.

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: Closing this older issue as I'm not sure there's any meaningful update for the docs to make here. Feel free to comment if you'd like it reopened.
