### ISSUE TITLE
Is there an msbuild task to run nunit with .nunit file as parameter?

### ISSUE THREAD

**Issue by ArsenShnurkov** [nunit/docs#206]
this is the question for the page
https://github.com/nunit/docs/wiki/NUnit-Test-Projects

What is the proper place to put this task:
https://github.com/loresoft/msbuildtasks/blob/master/Source/MSBuild.Community.Tasks/NUnit.cs
is it .csproj of .dll with test? ot some other place? Does special type of project for unit tests exists?

**Comment by ChrisMaddock** [comment]
For NUnit3 - you'll want to be using the NUnit3 task instead.

https://github.com/loresoft/msbuildtasks/blob/master/Source/MSBuild.Community.Tasks/NUnit3.cs

Make sure you're using a runner with the NUnit project installation - the NUnit msi installer and NUnit.Console NuGet package both include this. You should then just be able to pass a `.nunit` file in in the assemblies list as far as I know - however MSBuild.Community.Tasks is a separate project that just integrates with NUnit - you may be better asking questions relating to this over there.
