### ISSUE TITLE
Update TSL docs to mention namespace keyword

### ISSUE THREAD

**Issue by tom-dudley** [nunit/docs#207]
Bit of a reminder to myself to add some docs for the work done in https://github.com/nunit/nunit-console/issues/162 

Possibly also https://github.com/nunit/nunit/issues/1990 which is the corresponding framework code, although on first glance I can't see anything that would need documenting.

@rprouse Is there any process for creating documentation issues when a new release is made? I assume there's probably at least two or three changes (probably more!) made in the 3.7 release which warrant a change in docs. Is it just open for anyone to make an issue where they think a new feature should be documented? I guess I was half expecting e a master issue for the 3.7 release saying "these things should be documented", which obviously could have their own individual issues.

**Comment by CharliePoole** [comment]
Usually, we have tried to document things at the time of the release. If we missed anything, then an issue is necessary - or at least a fix. 😄

**Comment by mikkelbu** [comment]
I don't think that there are any process (but I'm new so I could have missed something :) ). We also have #157 about changes to the AuthorAttribute in 3.7. But I like the idea to go through https://github.com/nunit/nunit/milestone/25?closed=1 and see if we have missed anything.

**Comment by ChrisMaddock** [comment]
We're generally just not very good at keeping up with this. =( 

It would be great if someone could run through the 3.7 release notes, and make any relevant issues - anyone able to do that?

**Comment by tom-dudley** [comment]
I added a short section on namespaces to the TSL doc after reminding myself about it all!

**Comment by CharliePoole** [comment]
Thanks for doing that!
