### ISSUE TITLE
Category at class level hides Category at Test Method level in NUnit v3.7

### ISSUE THREAD

**Issue by VirendraSinghRathore24** [nunit/docs#209]
Issue with NUnit Category attributes. (Verson 3.7)
 - Add one Category for Test Method 
 - Add one Category for same Class
 - Run test case and you will not see Method level Category under traits

**Comment by CharliePoole** [comment]
This repository is for the nunit documentation and issues here are about errors in the docs.

I'm moving this to the nunit 3 adapter repo.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #336](https://github.com/nunit/nunit3-vs-adapter/issues/336) via [**ZenHub**](https://www.zenhub.com/)
