### ISSUE TITLE
Explicit attribute wiki page has broken formatting

### ISSUE THREAD

**Issue by PJB3005** [nunit/docs#210]
this page: https://github.com/nunit/docs/wiki/Explicit-Attribute

![](http://i.imgur.com/qcI4VId.png)

The C# code block isn't being parsed correctly.

**Comment by jnm2** [comment]
Appreciated! [Fixed.](https://github.com/nunit/docs/wiki/Explicit-Attribute/_compare/6551c5b673974ee77c0ce5b4e20119f64f1f4d13...1abfbf4e758ae89e1c8e8f9fefeb293275479baa)
