### ISSUE TITLE
Remove or update 'What tools are needed to build NUnit' page

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#211]
Every contributor so far has seemed to figure it out on their own, with the exception of #163.
I'm not sure we really need it. But we should do something because it's way out of date and never completed and slightly an eyesore at the moment.

https://github.com/nunit/docs/wiki/What-tools-are-needed-to-build-NUnit

**Comment by ChrisMaddock** [comment]
I agree - this sort of stuff should be (and mostly is!) documented per repo, like we have BUILDING.md in the main nunit repo.

**Comment by jnm2** [comment]
Since we don't have PRs for docs, how do I know when to go ahead? Wait for one person or two?

**Comment by CharliePoole** [comment]
Go ahead and edit it go ahead and delete?

**Comment by jnm2** [comment]
Okay, done.

**Comment by CharliePoole** [comment]
So what's done?

**Comment by jnm2** [comment]
I removed the link and deleted the page as per my, @ChrisMaddock's and your comments.

**Comment by CharliePoole** [comment]
@jnm2 My comment was a question. You had asked "when to go ahead" and I could not answer without knowing whether you edited or deleted. The title of this issue says "remove or update" and I couldn't tell from subsequent comments which you planned to do.

I think we probably need something - maybe in the wiki - to say what the process is for changing stuff.

**Comment by jnm2** [comment]
I'm sorry I misunderstood it.

The more I think about Chris's comment, the more I realize it's almost a *bad* thing to have this in the docs. The most helpful place for that information would be source-controlled in a doc in each repo. Having it here can only detract from that maintenance.

**Comment by CharliePoole** [comment]
I'm late to this issue, so I don't even know what "this" looked like. I'll take a peek in my local repo to see.
