### ISSUE TITLE
Do we want a developer faq? Finish or remove it.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#212]
Updating the dev faq has been an ongoing project of mine, but without an issue to represent it. As a result, people don't even know I'm working on it. This issue remedies that.

However, I'm wondering if we want it at all. Let's discuss here first. It's much easier to remove, obviously.

Meanwhile, I'm going ahead and removing the unfinished dev faq from the right-hand menu.

**Comment by jnm2** [comment]
I like the just-in-time approach to documentation: wait till someone asks, then either add it to the repo's build/contributing docs, or if that doesn't make sense, add it to the FAQ.

**Comment by CharliePoole** [comment]
I reviewed what we have. Here's what I see...
1. Easy to replace, very simple stuff, if we later need it.
2. Out of date pages
3. Links to pages we never created

I recommend we remove it entirely. The menu entries are already gone, so I would only have to remove the pages. To follow in my footsteps and check it for yourself, go to https://github.com/nunit/docs/wiki/Developer-FAQ

**Comment by rprouse** [comment]
I haven't looked at that in years and never did find it very helpful. The Windows 8.1 page can be deleted too, I fixed that years ago with a new signing key.

**Comment by CharliePoole** [comment]
Three of us say remove it. One more and I'll do it. 😉

**Comment by ChrisMaddock** [comment]
Removing sounds ok to me

**Comment by jnm2** [comment]
Kill it 😊
