### ISSUE TITLE
Update Action Attributes page to say when NOT to use it

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#213]
The page doesn't make it clear that action attributes are a holdover from NUnit V2 and that there are better ways to do things. This generates issues about the attributes that we don't want to fix.

**Comment by CharliePoole** [comment]
I have updated two pages in the wiki...
  https://github.com/nunit/docs/wiki/Framework-Extensibility
  https://github.com/nunit/docs/wiki/Action-Attributes
in an attempt to discourage unnecessary use of Action Attributes.

Please review the changes.

**Comment by SamJongenelen** [comment]
I've read the changes and it and its message are very clear to me. 
I do think its replacement `Custom Attributes` could use more specification and perhaps an example.

**Comment by CharliePoole** [comment]
Have you reviewed the new Custom Attributes page, put up yesterday?

**Comment by CharliePoole** [comment]
See #40
