### ISSUE TITLE
how did Nunit test .Net Standard lib,I can not find test menu

### ISSUE THREAD

**Issue by mokeyish** [nunit/docs#216]

**Comment by ChrisMaddock** [comment]
Can you explain your issue in more detail?

Have a look at the page below, maybe this will help.

http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/

**Comment by mokeyish** [comment]
@ChrisMaddock thankyou for your replying,I create a .net standard library,in order to testing this library then I create another .net standard library and add Nunit from nuget ,but it seems dose not works as .net framework library ,no testing menu or button

**Comment by mokeyish** [comment]
@ChrisMaddock Thankyou,I have solve it.This means .net standard is not  a concrete platform ,it must specify .net core app or .net framework to testing

**Comment by jnm2** [comment]
@mokeyish That is correct. .NET Standard is a *specification* to which .NET Framework and .NET Core and other *implementations* must conform.

**Comment by ChrisMaddock** [comment]
Great, glad you're up and running. 😄 

That blog post is currently the go-to place for getting up and running the .NET Core/Standard. I believe @rprouse intends to add something to the actual docs once things are settled down a little.
