### ISSUE TITLE
Update --labels option with new options

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#217]
In v3.7 of the Console, `--labels` will have additional options. This should be added to the console command line page, possibly with a separate section, now there's a bit more information to include.

See https://github.com/nunit/nunit-console/pull/186

A note - I was looking for the missing documentation, before I realised it wasn't actually in a release yet. I haven't made any attempt to go through all the 3.7 changes and see what needs to be documented.

**Comment by ChrisMaddock** [comment]
Thanks Mikkel! After digging into this, do you know what the options do? Might be helpful to add a line for each explaining that if so - I don’t know without looking at the code, or id add it myself!

**Comment by mikkelbu** [comment]
Sure. I can more less directly use what Charlie has written in nunit/nunit-console#186

**Comment by ChrisMaddock** [comment]
Ah! That’s exactly he sort of thing I was thinking - looks like it could be copied straight in! Thanks! 😊

**Comment by mikkelbu** [comment]
@ChrisMaddock it is ready for review now. I had to insert 2 * <br/> to force a new section in the beginning of the text.

**Comment by ChrisMaddock** [comment]
Looks great Mikkel. 😄 Thanks for picking this one up!
