### ISSUE TITLE
Text change for Combinatorial-Attribute page

### ISSUE THREAD

**Issue by jimothyjim** [nunit/docs#221]
Apologies if this is in the wrong place.

[Combinatorial-Attribute page ]( https://github.com/nunit/docs/wiki/Combinatorial-Attribute)

I think a line got accidentally duplicated, namely  _[Values("A", "B")] string s)_ 

```
[Test, Combinatorial]
public void MyTest(
    [Values(1, 2, 3)] int x,
    [Values("A", "B")] string s)
    [Values("A", "B")] string s)
{
    ...
}
```
It's a small thing but I couldn't see an easy way to suggest an edit so I thought I'd put it here.

**Comment by mikkelbu** [comment]
Thanks for the correction 👍 . I've updated the page.
