### ISSUE TITLE
Clarification of field naming standards

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#222]
See: https://github.com/nunit/docs/wiki/Coding-Standards#naming

I commonly see people using PascalCase for `const` and `static` fields no matter the visibility. ReSharper also encourages this out of the box.

Our standard does not mention `const` or `static` fields. Since constants aren't really fields I definitely think we should explicitly call out what we want for them. It would also be nice to explicitly call out static fields just because people are used to treating them specially.

Protected fields are a similar situation. The .NET design guidelines say that all protected (incl. protected internal) fields should be PascalCase just like public fields. This makes sense to me since public and protected fields go together in the sense that they are both visible outside your assembly, while private and internal fields can only be seen by your code. However, our standard is to split public and protected fields into PascalCase and _underscoreCamelCase, respectively.

#### Questions

 1. What should we explicitly say for constants?
    a. All constants PascalCase
    b. Public constants PascalCase, private constants _underscoreCamelCase
    c. Public constants PascalCase, private constants up to the dev's preference

 2. What should we explicitly say for static fields?
    a. All static fields PascalCase
    b. Public static fields PascalCase, private static fields _underscoreCamelCase
    c. Public static fields PascalCase, private static fields up to the dev's preference

 3. Do we want to expand “public” to mean fields visible outside the assembly as per the .NET design guidelines, explicitly `public` or `protected` or `protected internal`?

**Comment by mikkelbu** [comment]
Personally, I would say
1) a
2) 2
3) Yes
But it is not something I feel strongly about. I feel much more strongly about that the code is consistent throughout the codebase.

**Comment by jnm2** [comment]
More on the `protected` question. Our [comment standards](https://github.com/nunit/docs/wiki/Coding-Standards#comments) require XML documentation on public members only, but the .NET design guidelines require them on protected members also.

This **is** in fact being enforced as a compile error! So we should probably update the comment standards to match our real-life comment standards, explicitly specifying `public`, `protected` and `protected internal`. Once we do that, it's not far to making the naming standard section consistent with the comment section on this.

**Comment by jnm2** [comment]
My personal opinion is it would look kinda weird to enforce XML documentation on an `_underscoreCamelCase` field. I do thing the .NET design guidelines make sense when they say no externally visible fields should have underscore prefixes.

**Comment by jnm2** [comment]
I think we also have a CLS compliance issue if a protected field begins with an underscore.

**Comment by OsirisTerje** [comment]
IMHO we should avoid letting fields be anything but private.  Protected fields should be encapsulated as properties, and *preferably* only with get'ers.  
I would also suggest to test the decisions here (on all coding standards) up against the different analyzers available,  Resharper, and the most popular Roslyn ones, Sonarqube, Codecracker and MS FxCop analyzer.

**Comment by immeraufdemhund** [comment]
1) My work resharper settings were set for `const` to be ALL_UPPER_CASE (no matter the visibility) and it's what I've grown use to.

I agree with @OsirisTerje  when he said
 >IMHO we should avoid letting fields be anything but private. Protected fields should be encapsulated as properties, and preferably only with get'ers.

2) I am used to treating static the same as non-static. which I think is "B"

3) Meh

**Comment by CharliePoole** [comment]
1. ALL_UPPER_CASE is how I'm doing constants. It makes them stand out. However, when I have a set of static "constants" some of which can't really be C# constants because they require non-constant initialization, then I use Pascal casing for both the `const` and the `static readonly` members, so that they all look the same. Clarity is what's important.

2. Mostly I prefer to name static fields the same as instance fields, so I don't see the need for a new standard. I've worked in places that used `_sName`, which is truly ugly.

3. I don't see what we would change in our naming if we did that. We don't make visibility part of the name currently, do we?

**Comment by jnm2** [comment]
1. So for consistency, const and static readonly should be PascalCase? Regardless of visibility?

 3. It would change any protected field (we have a bunch, mostly camel case with no underscore) from our current non CLS-compliant standard of _underscoreCamelCase to PascalCase on the basis that they are visible to external assemblies.

We should either clarify this or ban public and protected fields which are also discouraged by the the .NET design guidelines. Public and protected readonly fields don't bother me and indeed you'll see them frequently in things like `DateTime.MinValue`, but the only time I'm okay with a field being mutable is if it's private.

**Comment by CharliePoole** [comment]
As I said, I use ALL_UPPER_CASE for const except in that one special situation I described.

Whether to use properties or fixtures is a collective, case by case decision in my view. It's not part of a coding standard because it's not merely coding, but design - albeit low-level design. I also don't think it should be part of a coding standard because it doesn't appear to need standardizing.

**Comment by jnm2** [comment]
Thanks for the discussion. Let's see if I get this right:

Constants:
 - PascalCase: @mikkelbu, @OsirisTerje
 - MACRO_CASE: @immeraufdemhund
 - want flexibility: @CharliePoole 

Static fields:
 - a: @mikkelbu, @OsirisTerje
 - b: @immeraufdemhund, @CharliePoole 

Name all externally-visible fields like public fields:
 - yes: @jnm2
 - weak yes: @mikkelbu
 - don't care: @immeraufdemhund
 - asked a question but didn't vote: @CharliePoole
 
Please correct me if I'm wrong.

(I'm adding my name to one because the alternative is the non-CLS-compliant underscore and because it's our externally visible API at stake which I feel strongly about.)
 
@rprouse: as a lead of some of the key projects, I'm not comfortable adding coding standards to org-wide docs without buy-in from you as well as Terje. I'm sorry to pull you away from what you're doing, but would you mind weighing in?

**Comment by CharliePoole** [comment]
I didn't actually "vote" on anything, because as far as I knew we were not voting. It was a long time ago, but reading my comments it seems like I went out of my way to state what I do, which is different from saying it should be a standard.

Could we turn the discussion to whether anything you are advocating actually __needs to be a standard__? The idea in my view is to standardize things which - if not standardized - would lead to confusion in the team.

Maybe it would help to simply propose specific textual changes to the standard doc, one at a time, and see what people think?

**Comment by CharliePoole** [comment]
There's a bigger picture thing here as well. As far as I'm concerned, the existing coding standard was invalidated when we set up the core team. Until each project establishes a (possibly different) standard, we don't have one even if the wiki says we do. We could, of course, decide to adopt the existing standard for core projects but I wouldn't want to go any further than that. What if somebody using a different standard offers us a project? Do we make him change the code?

Of course, the lighter-weight the standard, the easier it is to make it apply to everything.

**Comment by ChrisMaddock** [comment]
> What if somebody using a different standard offers us a project? Do we make him change the code?

Can we cross that bridge when we come to it? I'm sure we'd be able to compromise if that came about.

CLS compliance is a separate issue to variable styling - I agree with you that should definitely be in, @jnm2. The others I have no preference on.

**Comment by CharliePoole** [comment]
@ChrisMaddock I agree we can cross that bridge when we come to it, so long as we don't say or suggest that there is a common standard that applies to all projects under the NUnit organization.

CLS compliance is an issue for those assemblies we declare to be CLS compliant and only those.

**Comment by jnm2** [comment]
Superseded by https://github.com/nunit/nunit/issues/2822.
