### ISSUE TITLE
Interface and type parameter naming standards

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#223]
See: https://github.com/nunit/docs/wiki/Coding-Standards#naming

 1. Do we want to enforce the naming standard that interfaces must start with the prefix `I` in addition to the remainder of the name being PascalCase?

    a. Yes, and error via .editorconfig
    b. No, but suggestion or warning via .editorconfig
    c. Not at all

 3. Do we want to enforce the naming standard that classes named after an interface must elide the prefix `I` if the class name starts with the interface name? I ask because we turned back a PR for this, so an .editorconfig error would have been nice for the contributor.

    a. Yes, and error via .editorconfig (when the capability is available)
    b. No, but suggestion or warning via .editorconfig (when the capability is available)
    c. Not at all

 2. Do we want to enforce the naming standard that type parameters must start with the prefix `T` in addition to the remainder of the name (if any) being PascalCase?

    a. Yes, and error via .editorconfig
    b. No, but suggestion or warning via .editorconfig
    c. Not at all

**Comment by immeraufdemhund** [comment]
If this does become a thing I would go with A's accross the board. Since I have multiple projects going on and trying essentially multiple coding masters (IE those who will reject my pull request) keeping track of the different standards would be very helpful to me.

**Comment by mikkelbu** [comment]
I agree with @immeraufdemhund

**Comment by CharliePoole** [comment]
@immeraufdemhund Can you explain further what you mean?

The notion of "enforcement" really bothers me, implying as it does that there is some authority outside the team that gets to tell the team how to work. In my coaching practice I often started out by getting management to agree they have no business doing this - as well as many other things. It bothers me if we, as a team, are going to act like bad managers of one another or of contributors.

I do see that you, having recently joined the team might want a bit more clarity. I just wondered we do that without telling you how to work.

**Comment by immeraufdemhund** [comment]
I've not used a editor config before but I do plan on looking into it to see if it is something that I can copy in when I clone down a repository here at work so that I can code to the integration managers preferences. Here at work I get dinged for naming conventions most frequent (as a side note we all have resharper here at work and we all claim to have never touched the settings and everyone says the same thing "Why doesn't your resharper complain about the way you named that? I've never touched my settings..."). So if it were possible to have visual studio remind me of how 1 team prefers to name things I would greatly be in favor of that. Normally it isn't a problem for me when I edit a specific class, but it's when I make something new that I forget. Out of curiosity can a .editor config complain about no header applied?

 > The notion of "enforcement" really bothers me, implying as it does that there is some authority outside the team that gets to tell the team how to work.

I don't really see this as a someone saying you need to work in a specific way. In the context of the other issues it seems like it is all mostly naming conventions which really don't play a role in how we test or how the application looks, but rather a reminder to those who contribute to keep the code consistent.

**Comment by jnm2** [comment]
> The notion of "enforcement" really bothers me, implying as it does that there is some authority outside the team that gets to tell the team how to work. In my coaching practice I often started out by getting management to agree they have no business doing this - as well as many other things. It bothers me if we, as a team, are going to act like bad managers of one another or of contributors.

> No special objection but I get the general feeling that you want these to be much more precise than I like to see and prescriptive to a perhaps unhealthy degree.

> What does "enforcing" mean for you in this context?

@CharliePoole I'd like some clarity on this now. You're the one you drilled into us that we can't add XML documentation best practices to the coding standard because the coding standard is an absolute blind enforcement type deal. If that's such a bad thing, why not downgrade the entire document to a best practices document and include the XML best practices from it? If it's not such a bad thing, what's wrong with refining some of the flaws in the coding standard?

**Comment by jnm2** [comment]
I'm been using the word enforce, meaning "we'll do our best to make sure this doesn't get committed to master," to remind people how austere the coding standard is, to help them get the right mindset for answering the question, because all of us routinely forget that coding standard isn't synonymous with best practices.

**Comment by jnm2** [comment]
I think it is bad manners not to include everything that we know we will send back a PR over, in either a best practices or a coding standard, and even better, realtime editor feedback in addition to the documentation. This saves time for both contributors and us.

**Comment by jnm2** [comment]
Which is also why I left the option in every case, “explicitly leave it up to the dev's preference.” That also makes it less likely to send back a PR over something. Explicitness means that contributors know that they don't have to guess. Again, some of them really want best practices to follow for our project. Others just want a clear idea of how much freedom they have or don't have before investing in a direction.

**Comment by CharliePoole** [comment]
I see "enforce" as "force", i.e. as an exercise of power by some person or group over some others. That's what standards have been in most companies I worked at, at least until I was able to change it.

IIRC our past conversations were about the standards we were imposing on ourselves so no enforcement was involved. You seem to be describing a different approach, where some "we" imposes rules on some "they". I can't figure out who is the enforcer, who the enforcer, so I asked.

I also don't know what __you__ mean

**Comment by jnm2** [comment]
I mean enforce in the same sense that you told us the rest of the coding standard is already to be enforced.  I don't know why this is so complicated. If the approach in the existing coding standard is bad, let's change the approach. If it's not bad, let's continue to talk about making the coding standard more clear and useful.

**Comment by CharliePoole** [comment]
Explicitness, scope and degree of enforcement are all orthogonal. I'm in favor of very explicit standards, somewhat limited in scope, with virtually nothing being rejected out of hand while still insisting on the most important things. Part of being explicit is telling people how important each thing is.

I also think it's different when a team establishes standards for itself and when we turn around and apply those standards to outside contributors. I'm not sure exactly how to express that difference though.

**Comment by jnm2** [comment]
So to address:
> No special objection but I get the general feeling that you want these to be much more precise than I like to see and prescriptive to a perhaps unhealthy degree.

We need something precise so that _if_ someone is looking to follow the project style, they don't have to try to find an existing scenario in the codebase to glean clues, they don't have to ask us and wait, and they don't have to guess and find out. That sounds like a best practice.

We also need something precise if we know for sure we will request changes in the PR over it, like naming an interface without an `I` prefix. We know we're going to do that, and I think it's only helpful to document that in case someone wants to skim and double check as they code.

**Comment by jnm2** [comment]
> Part of being explicit is telling people how important each thing is.

I'm totally in agreement with this.

**Comment by CharliePoole** [comment]
@jnm2 If it's simple, just tell me. Our past discussion was about voluntarily following a standard, as a team member. Enforcement sounds like something new to me. I'm trying to keep an open mind, that you may not mean anything by it.

BTW, I do see you left other options. I'm only objecting to the notion of enforcement, especially automated enforcement, which eliminates the option of even discussing exceptions to the rule.

**Comment by jnm2** [comment]
> Our past discussion was about voluntarily following a standard, as a team member. Enforcement sounds like something new to me. I'm trying to keep an open mind, that you may not mean anything by it.

In our past to discussion I used "coding standard" to mean a guideline voluntarily followed, and you said that a coding standard was a thing enforced from the outside and that what I really meant was “best practice.” I assume there is a distinction between a best practice and a coding standard; therefore, when I say enforced, I'm referring to that distinction .

**Comment by jnm2** [comment]
Automation is amazing for efficiency and people do appreciate it. From my existing understanding of coding standard and best practices:

If there is anything we know for sure we'll reject, we should show it as an error in realtime if possible and document it as a coding standard.
If there is anything we prefer but wouldn't necessarily reject, we should show it as a suggestion in realtime if possible and document it as a best practice.

And like anything else we can adjust in either direction as we learn new information.

**Comment by oznetmaster** [comment]
I am not sure that everyone is aware how arbitrary this all is.

ALL of my NUnit code is written to an entirely different coding standard, since I cannot stand the NUnit standard.

I simply wrote a very short Roslyn program which converts my source code to the NUnit "standard" before I submit it.  Took about two hours to write the program.

I personally think way too much time is being spent on this.  Why not simple write a single Roslyn program which will take in any C# source, and output C# source to the NUnit "standard".  It could either be made available to developers, or automatically run when code is submitted.

This would allow each contributor to code as they wished, yet maintain a consistent look and feel in the repository.

**Comment by immeraufdemhund** [comment]
@oznetmaster HOW YOU DO DAT!?!?!?!?

or more formally... how could a person make this part of the cake script. I'd so much rather have it as part of a `cake -target=precommit` or something like that to fix any files that I touched and messed up the standards.

**Comment by CharliePoole** [comment]
@oznetmaster I entirely agree about spending too much time on it!

@jnm2 If I haven't adequately communicated my actual position to you in all our past discussions, which is what it sounds like, I'm sure it's my fault because it's always the responsibility of the guy trying to explain something to do it in a way that is understood.

Right now, it's you in the position of trying to explain something to me and I'm not getting it.

I think it's better to clarify what you are asking us to do when you say "enforce" rather than debate what I might have said or what it meant at some time in the past.

If you are asking us to "enforce" you have to tell us what that will mean. That's all. If it's no different from what we do now, I'm happy with everything except the word, which - to me - does not represent what we now do. In that case, it's just bad naming. To me, enforcement is what the boss does. Maybe he gives you three chances to do things the way he likes and then fires you. Obviously that is not what you mean, but the word definitely suggests more than just doing our best to be in compliance.

**Comment by jnm2** [comment]
> I think it's better to clarify what you are asking us to do when you say "enforce"

I've clarified what I mean by “enforce” severally above. Here it is all together, what I meant by “enforce”:

 1. Nothing. That is, by “do we want to enforce,” I meant no more, no less, than, “do we want in our coding standard.” I used the word specifically to avoid this conversation because I thought it was how you wanted us to think of the coding standard. Since I have no special attachment to the concept of enforcement, I'm going to hereon replace it with “standardize.”

 2. If it's a waste of time let's stop discussing, but I don't think this conversation is a waste of time. Since we're here having the conversation and aren't understanding each other as well as I'd like, I'm game. This is my best go:

    > Members and new contributors are encouraged to scan the coding standards and the best practices. If we notice that code does not follow a rule in the **coding standard**, we'll do our best to make sure this mistake doesn't get committed to master. If is such code is already in master, we should update the file if we're already making extensive changes to the file.
    >
    > If there is anything over which we know for sure we'll ask for changes, we should show it as an error in realtime if possible and document it as a **coding standard**. Anything else isn't respectful of outside contributors' time or team members' time.
    >
    >  If there is anything we hope to see over which we wouldn't necessarily ask for changes, we should show it as a suggestion in realtime if possible and document it as a **best practice**.
    >
    > And like everything else, we can adjust in any direction as we learn new information. For example, so long as we are sure no interface names should leave off the `I` prefix, we should make this an .editorconfig error. If it happens to come up in a PR that we want an interface without the `I` prefix, we should react to the new situation by moving the rule from the **coding standard** to the **best practices** and changing the .editorconfig error to a suggestion.


@oznetmaster 
> Why not simple write a single Roslyn program which will take in any C# source, and output C# source to the NUnit "standard". It could either be made available to developers, or automatically run when code is submitted.

That would be a burden if done manually and source control hell if done automatically. No way around it.

**Comment by jnm2** [comment]
(Automatic source transformation on either commit or push or merge would be like our current minor whitespace consistency issues, on steroids.)

**Comment by CharliePoole** [comment]
@jnm2 That clears up a lot. Briefly...

> ...by “do we want to enforce,” I meant no more, no less, than, “do we want in our coding standard.”

OK. In that case we have nothing more to discuss regarding enforcement.

> Members and new contributors are encouraged to scan the coding standards and the best practices. If we notice that code does not follow a rule in the **coding standard**, we'll do our best to make sure this mistake doesn't get committed to master.

Can't argue with that.

> If there is anything that we're always sure we'll reject in a PR, we should show it as an error in realtime if possible and document it as a **coding standard**. 

I think we do have such things, but I don't think anyone reading the coding standard can tell which ones they are. I don't think we can do anything about them until we make that clear. One way to make it clear would be to __only__ include such items in the coding standard an nothing else. That's a position I've pushed in the past. However, while it works with a close-knit, co-located team, I think occasional contributors may need more guidance about the things we "mostly" like to see. I'd love to see us develop a document that has levels of severity like "Always" "Usually" "Avoid" "Never" Any automation should come after we have such a categorization, IMO.

**Comment by jnm2** [comment]
> Any automation should come after we have such a categorization, IMO.

Perfect, and that's exactly what's driving these questions. :D

I'm pretty sure you said the coding standard should only contain rules whose level of severity is "Always" or "Never," and that was the only reason XML documentation best practices couldn't be called XML documentation standards: because "standards" are things that can't have "usually" and "avoid," only "always" or "never." Is there a different reason?
At the time, I wanted to suggest that we specify levels just like this and thought everyone would complain that it was needlessly complex.

**Comment by oznetmaster** [comment]
I have been doing the automatic conversion for about five years now.  It has not been the "burden" or the "hell" you suggest.

**Comment by jnm2** [comment]
@oznetmaster You're also more experienced than the average contributor and either way you maintain an intense one-way conversion so it makes sense for you to take this approach.

**Comment by jnm2** [comment]
Thanks for the discussion. Let's see if I get this right:

 - @immeraufdemhund and @mikkelbu voted to add a coding standards rule and .editorconfig error
 - @oznetmaster won't notice a difference because he preprocesses the source
 - @CharliePoole hasn't voted yet these should be standards ("always", .editorconfig error) or best practice ("usually", .editorconfig warning), or none (in the future we should try to refrain from requiring changes to PRs which name interfaces without a leading `I`).

Please correct me if I'm wrong.

@rprouse and @OsirisTerje: as leads of the key projects, I'm not comfortable adding coding standards without buy-in from you. I'm leaning towards closing the issue; do you disagree?

**Comment by CharliePoole** [comment]
@jnm2 If pressed, I comment. However, this really is not an issue that I think is worth a lot of anybody's time. You feel differently, which is fine. 

In this particular case, I didn't vote because your multiple-choices didn't include an option I would select. I would have picked:

1.  Yes, but don't use .editorconfig
2.  Yes, but don't use .editorconfig
3.  Yes, but don't use .editorconfig

**Comment by jnm2** [comment]
> If pressed, I comment. However, this really is not an issue that I think is worth a lot of anybody's time. You feel differently, which is fine.

Um.... okay. Thank you.

**Comment by jnm2** [comment]
Naming conventions don't appear to be a problem in practice.
