### ISSUE TITLE
Anonymous type and tuple field naming standards

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#226]
See: https://github.com/nunit/docs/wiki/Coding-Standards#naming

Our naming standard does not directly cover anonymous type field names or tuple field names.
Technically they are public fields in both cases and are covered by the PascalCase rule.

 1. Do we want to continue enforcing PascalCase for anonymous type fields? (Example: `new { FieldA = 1, Field B = 2 }`.)

    a. Explicitly enforce PascalCase, add note "Includes anonymous type fields" to Public Fields
    b. Explicitly leave it up to the dev's preference, add new row under Public Fields

 2. Do we want to continue enforcing PascalCase for tuple fields?
    I think we should switch and enforce `camelCase` if we enforce anything, because tuples were designed to be as much like parameter lists as possible– the feature was called Multiple Return Types once– and when the fields aren't treated like parameters, they're treated as much as possible like locals.
    Almost all code I've seen uses camelCase here. Example: `(fieldA: 1, fieldB: 2)`.

    a. Explicitly enforce PascalCase, add note "Includes tuple fields" to Public Fields
    b. Explicitly enforce camelCase, add new row under Parameters
    c. Explicitly leave it up to the dev's preference, add new row under Parameters

 3. What about inferred anonymous type field names and tuple field names?

    a. Explicitly allow inferred field names to use any style
    (Example: `new { localA, localB.PropertyB }` has public field names `localA` and `PropertyB`. Same for tuples in C# 7.1.)
    b. Explicitly require a new field name to be specified which follows the naming standard
    (Example: `new { LocalA = localA, localB.PropertyB }` has public field names `LocalA` and `PropertyB`. Same for tuples in C# 7.1.)

**Comment by immeraufdemhund** [comment]
I don't have an opinion on these

**Comment by mikkelbu** [comment]
@jnm2 Regarding 1. What exactly do you mean by "anonymous type fields"? I'm quite sure that you cannot declare a field as having an anonymous type.

**Comment by jnm2** [comment]
I mean fields *of* anonymous types: `new { FieldA = 1, FieldB = 2 }`.

**Comment by jnm2** [comment]
I added examples.

**Comment by mikkelbu** [comment]
Aah that makes more sense 😄 . Then I will say 
1) a
2) b

**Comment by jnm2** [comment]
Added new question 3.

**Comment by CharliePoole** [comment]
@jnm2 What does "enforcing" mean for you in this context?

**Comment by jnm2** [comment]
[Discussion had continued at https://github.com/nunit/docs/issues/223#issuecomment-315759566]

**Comment by jnm2** [comment]
@rprouse and @OsirisTerje: as leads of the key projects, I'm not comfortable adding coding standards to org-wide docs without buy-in from you. Due to low interest, I'm leaning towards closing the issue; do you disagree?

**Comment by rprouse** [comment]
Let's close. We are not going to cover every language construct in our documentation.
