### ISSUE TITLE
Update Test Filters page

### ISSUE THREAD

**Issue by tom-dudley** [nunit/docs#227]
This page isn't quite up-to-date: [https://github.com/nunit/docs/wiki/Test-Filters](https://github.com/nunit/docs/wiki/Test-Filters)

From what I can tell it's missing the following XML elements:
- `method`
- `namespace`
- `name`
- `prop`
- `class` ?

**Comment by mikkelbu** [comment]
The page should be updated now. I used the schemas from nunit/nunit#2929 and the text in https://github.com/nunit/docs/wiki/Test-Selection-Language for inspiration and help. @jnm2 can you do a review, since you have created the schemas.

**Comment by ChrisMaddock** [comment]
Thanks for picking up these docs issues Mikkel - great to see them being ticked off! 😄

**Comment by jnm2** [comment]
https://github.com/nunit/docs/wiki/Test-Filters/_compare/6aa30d59504302710625c172bce82c02bde01f40...22d48d8207bb219486eef5882e24268f6f286b46 looks good to me! Thanks Mikkel!

**Comment by mikkelbu** [comment]
@jnm2 I just found out that regular expressions were not mentioned on the page, so I've just added information about this also.

**Comment by jnm2** [comment]
Looks good.
