### ISSUE TITLE
The console parameter --test-name-format is not documented

### ISSUE THREAD

**Issue by Galad** [nunit/docs#228]
Hello,
The console parameter --test-name-format which was added as part of the issue https://github.com/nunit/nunit/issues/1549, and which allows to change the default [test name format](https://github.com/nunit/docs/wiki/Template-Based-Test-Naming) is not listed in the [command line documentation](https://github.com/nunit/docs/wiki/Console-Command-Line). 

Shouldn't it be listed there ?

**Comment by ChrisMaddock** [comment]
I never knew this existed! Cool!

**Comment by ChrisMaddock** [comment]
This is added - thanks for reporting the problem. 😄
