### ISSUE TITLE
When running tests console output not written til test is finished.

### ISSUE THREAD

**Issue by sbhanderi** [nunit/docs#23]
When running say 1 test via 
"c:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" --x86 --verbose --labels=All --timeout=300000 --trace=Verbose Genesyslab.Lync.Test.dll --testlist=CustomTestList.txt --result=C:\Jenkins\workspace\WPLync-Regression-Runner\nunit-result-QA180.xml;format=nunit2 

If within the test I have console.writeln(). It does not get written out until the test is run to the end.
Is there an option which will output to console.

If have found that if I use the NUNIT 3 plugin adapter, then I don't get console output at all.

**Comment by CharliePoole** [comment]
That's correct. See issue nunit/nunit#1139.

This is the docs repo, where people report errors in our documentation
