### ISSUE TITLE
NUnit3TestAdapter is not compatible with .Net Core v 1.1

### ISSUE THREAD

**Issue by rock-walker** [nunit/docs#230]
Thank you, first of all, that you keeping NUnit up-to-dated.
I'm big fan of NUnit for last 3 years. 
Now I'm on Visual Studio 2017 and .Net Core v 1.1 and trying to install NUnit3TestAdapter. VS says to me, that it's incompatible and displays the error:

> "Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)"

Would you plan to upgrade UnitTestAdapter?

**Comment by rprouse** [comment]
Version 3.8 of the test adapter does support .NET Core 1.1 (and 2.0). How are you installing the adapter?

See https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard for instructions and common problems. Let us know if it helps.

**Comment by rock-walker** [comment]
Thanks, Rob a lot. I have read your blog post "http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/" and succeeded with alpha version 3.8.1 of NUnit3TestAdapter.
Now I see my tests in VS2017.

**Comment by rprouse** [comment]
3.8.1 has been released, you don't need to use the alpha anymore.
