### ISSUE TITLE
Timout-Parameter excluding OneTimeSetup and OneTimeTearDown

### ISSUE THREAD

**Issue by Scordo** [nunit/docs#231]
Hello,

Test-Scenario:
- 1000 tests of the same kind
- all the test need a special "environment" which must be setup once (1 run for all Tests, not 1000)
- the setup of the environment takes up to 10 seconds
- the test excluding the setup will run in under a second, each
- the setup is done using OneTimeSetup-Attribute

Goal:
- limit test execution time to 1 second (fail and stop a test if it exceeds the 1 second limit)
- execution time: should not include OneTimeSetup and OneTimeTearDown

Problem:
- the execution time of the first of the 1000 tests always exceeds the time-limit because of the OneTimeSetup

Proposed Solution:
- Add a parameter like "/TestMethodTimeout" which is like "/timeout" but does not count OneTimeXXX times

Nice to have:
- Timeout for each Category (CI=1s, Nightly=10s ...)
- Also provide the TestMethode-Only-Time in the Test-Result-Xml file. (So its possible to see the real execution time of the test-logic itself

I don´t know if this is the right place to post this.

Regards,
Jens

**Comment by CharliePoole** [comment]
Let's figure out the right place first, after which we have a way to move the issue.

Are you talking about the TimeoutAttribute, the console runner timeout option or something else? Depending on how you run your tests, there are various ways a timeout might be specified. NUnit's internal timeout doesn't include one time setup because it isn't part of the test case execution but rather of the fixture.

**Comment by Scordo** [comment]
What I really want - Clarification:
We are running our test during CI- and Nightly build on a build server. 
Those test are executed using the console runner. (The execution is triggered by a msbuild-script)

The goal is to force a limit for CI-Tests of 1 second. If a tests takes longer it shouldn't be a CI test, it should be a Nightly.
Thats why Attribute-Based timeouts are no option. Currently there is no option for the console runner for the timeout which does not include OneTimeXXX. The timeout for the console runner is always the full execution time of the test including all Setups/Teardowns.

We want a short CI-Build-Time, thats why we have to make sure no long running tests are part of the ci test runs.

Maybe I'm missing a possibility. :-)

Tnaks!
Jens

**Comment by CharliePoole** [comment]
Timeout specified on the console runner command-line using the --timeout option is exactly the same as that used when an attribute is applied. It only includes setups and teardowns for test cases. One the setup and TearDown don't exist for cases, only for fixtures. OneTimeSetUp and OneTimeTearDown are never included.

**Comment by Scordo** [comment]
Ok, so I'm wrong? :-s
I'll do some testing to check that - Sorry for that.

**Comment by Scordo** [comment]
I did some tests and you're right. I then realized that I took wrong assumptions on our test behavior. :-(
There is some internal caching logic in our base test class which is producing a longer test runt for the first test being executed :-(
Sorry for stealing your precious time.

**Comment by CharliePoole** [comment]
No problem! We're always glad to clarify how things work in NUnit.
