### ISSUE TITLE
parallelism confusion - forcing single-threaded across and within assemblies

### ISSUE THREAD

**Issue by SurajGupta** [nunit/docs#234]
How do I force single-threaded execution across all tests in an assembly and all tests across assemblies (basically creating one long serial pipeline in which tests are run) by only modifying code in my solution (so NOT changing default command-line arguments to the runner)?

I'm read the documentation a few times and I'm confused.

This seems to be an assembly level setting, which I can just set to 1:
https://github.com/nunit/docs/wiki/Parallelizable-Attribute

This also seems to be available at the assembly level:
https://github.com/nunit/docs/wiki/NonParallelizable-Attribute

The documentation here:
https://github.com/nunit/docs/wiki/Parallelizable-Attribute
says "By default, no parallel execution takes place" - but that seems to contradict the first link which says that the greater of 2 workers and # of cores is used.

**Comment by CharliePoole** [comment]
There is no parallelism within an assembly by default so you  don't need to use any attributes. The LevelOfParallelism attribute us only consulted to determine how many either threads should be used when there is parallelism.

Note that this is completely separate from parallelism between different assemblies. Multiple assemblies are run in parallel by default and you can only prevent it by using a command line option.

**Comment by SurajGupta** [comment]
Thank you!
