### ISSUE TITLE
Documentation for dotnet test with nunit on OSX

### ISSUE THREAD

**Issue by andyp1per** [nunit/docs#235]
https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-macos contains a description for developing a dotnet core application with xunit tests on osx. Ideally there would be a similar way to create an nunit based project, but the templates do not exist and I'm not really sure what part is missing.
I can follow the instructions and then do something like:
`dotnet add library package NUnit3TestAdapter`
but 
`dotnet new nunit -o test-library`
fails (obviously) and its really not clear to me what direction to go in. The [blog](http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/) does not seem to help.

**Comment by andyp1per** [comment]
A little more color, here is an example csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="NUnit" Version="3.8.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
  </ItemGroup>

</Project>
```
I have to target net461, because netstandard2.0 is not available (maybe this is the problem?).
Adding a test C# file ytieds this when I try and run dotnet test:
```
andypiper:example andy$ dotnet test
Build started, please wait...
Build completed.

Test run for /Users/andy/projects/dotnet/example/library/bin/Debug/net461/library.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Failed to initialize client proxy: could not connect to test process.
```

**Comment by mikkelbu** [comment]
Hi @andyp1per. Regarding your first question.

This page https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new refers to https://github.com/halex2005/dotnet-new-nunit for an nunit template. Accordingly to this page all you need to do is `dotnet new -i NUnit3.DotNetNew.Template` to install the template and then `dotnet new nunit` to create a NUnit library project from template.

**Comment by andyp1per** [comment]
Ah very good. That gets me much further. The template appears a little outdated:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" Version="3.7.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\library\library.csproj" />
  </ItemGroup>

</Project>
```
but the netcoreapp2.0 seems to be the key, as I can then run tests:
```
andypiper:example andy$ dotnet test test-library/test-library.csproj 
Build started, please wait...
Build completed.

Test run for /Users/andy/projects/dotnet/example/test-library/bin/Debug/netcoreapp2.0/test-library.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
NUnit Adapter 3.8.0.0: Test execution started
Running all tests in /Users/andy/projects/dotnet/example/test-library/bin/Debug/netcoreapp2.0/test-library.dll
NUnit3TestExecutor converted 1 of 1 NUnit test cases
NUnit Adapter 3.8.0.0: Test execution complete

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.2465 Seconds
```

**Comment by andyp1per** [comment]
Progressing with this. I cannot find attributes other than Test, so for instance [Platform] and [Timeout] fail for me with something like:
`error CS0246: The type or namespace name 'PlatformAttribute' could not be found (are you missing a using directive or an assembly reference?)`
Any idea what reference or otherwise I am missing?

**Comment by andyp1per** [comment]
To be clear this code works fine under VS on Windows10, its not working with netcore on OSX.

**Comment by CharliePoole** [comment]
The `PlatformAttribute` and `TimeoutAttribute` don't exist on our .NET Standard builds. I'm going to file a separate documentation error about this.

**Comment by ChrisMaddock** [comment]
https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard has been updated in the docs since this issue was filed, and I think now covers the questions here.

**Comment by jnm2** [comment]
PlatformAttribute and TimeoutAttribute are now in our .NET Standard build, too.
