### ISSUE TITLE
There is no documentation for DefaultFloatingPointToleranceAttribute

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#237]
Like it says. Needs to be linked from Attributes page.

**Comment by mikkelbu** [comment]
@CharliePoole The documentation have been added at https://github.com/nunit/docs/wiki/DefaultFloatingPointTolerance-Attribute and linked from https://github.com/nunit/docs/wiki/Attributes

**Comment by CharliePoole** [comment]
Looks good to me
