### ISSUE TITLE
failing test due to whitespace

### ISSUE THREAD

**Issue by LesediM** [nunit/docs#239]
**Test Cases**

`[TestCase(0, "R 0.00")]`
          `[TestCase(1000, "R 1\u0020000.00")]`
           ` [TestCase(10000, "R 10 000.00")]`
`            public void GivenValueHasValue_ShouldReturnValueAsSouthAfricanCurrency(decimal amount, string expectedValue)`
`            {`
`                var result = PayfastTransactionCommon.FormatAsCurrency(amount);`
`                Assert.That(result, Is.EqualTo(expectedValue));`
`            }`

**Code being tested**
` public static string FormatAsCurrency(decimal? amount)`
        `{`
            `return amount.HasValue`
              `  ? $"R {amount:N}"`
              `  : string.Empty;`
      `  }`

First test case passes but the latter test cases fail. 
Am I missing something or doing something wrong?
Nunit version is 3.8.1.0

**Comment by CharliePoole** [comment]
You filed this as an issue against our documentation. I'm moving it to the proper repository.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit #2559](https://github.com/nunit/nunit/issues/2559) via [**ZenHub**](https://www.zenhub.com/)
