### ISSUE TITLE
Add the FAQ page

### ISSUE THREAD

**Issue by ixSci** [nunit/docs#24]
As per the following SO question [comment ](http://stackoverflow.com/questions/35983016/nunit-3-forbid-tests-to-run-in-parallel?noredirect=1#comment59738188_36022871) I suggest to add the FAQ page where the most asked question would be listed with answers. I think adding a page with the name like "Things You Must Not Assume" would be rather specialized while having a general FAQ page might be useful for different questions not just for those assumptions related.

**Comment by CharliePoole** [comment]
Presumably, you did notice the smiley for the "Things you must not assume" idea on SO. ;-)

This is a good idea. Folks, please add suggestions to this issue about what questions should be answered on the FAQ page.

**Comment by ixSci** [comment]
I mentioned that contrived name just in case :) 

I think at least hose answers mentioned in the comment should be there:

1. Don't assume your constructor is only called once per run by NUnit 
2. Don't assume your test is running on a unique thread - although you can ask NUnit to do that
3. Don't assume your tests are all run on the same thread
4. Don't assume your tests are all run in the order they appear in the source file or in alphabetical order.

They lay smoothly on the usual FAQ format.

**Comment by CharliePoole** [comment]
JUnit has a good example of a FAQ: http://junit.org/faq.html

**Comment by ChrisMaddock** [comment]
I agree this would be a good thing to have, but can I suggest we remove the current page, until we someone is willing to write some content?

Following the "User FAQ" link from the main menu to find this is a little disappointing. 😞 

https://github.com/nunit/docs/wiki/User-FAQ

**Comment by CharliePoole** [comment]
That's fine with me. Note that you can delete the page online, but to update the various sidebars you have to pull down the wiki and edit each `_Sidebar` file that contains it. It's not possible to maintain the directory structure otherwise.

**Comment by ChrisMaddock** [comment]
Done - thanks. 🙂

**Comment by SeanKilleen** [comment]
Given that this was previously removed and has not made progress for 3 years, I am going to close this issue as part of cleaning up.

Just comment here if you'd like this to be reopened. I'm happy to revisit if we feel there's a need, though I would want to have it seeded with topics by this group that I could then break down to have myself and others write up. I'm thinking with the prevalence of StackOverflow etc. we might be able to abandon this for now.
