### ISSUE TITLE
Parallelization and setup and teardown pages need to mention mutual exclusiveness

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#242]
We need to mention the fact that parallelization within a fixture reuses the same instance and therefore you should remove all mutable class fields.

We have a number of issues where people have run into a conflict because everyone assumes there is a new fixture instance per test case, so this should be clearly documented: https://github.com/nunit/nunit/issues/2105, https://github.com/nunit/nunit/issues/2252, https://github.com/nunit/nunit/issues/2573.

**Comment by CharliePoole** [comment]
I would have sworn this was very clearly documented somewhere! However, I can no longer find it. 😦 

It was a page that showed the execution of tests in pseudo-code... like foreach class... etc. It would be nice if we could recover and update it.

**Comment by CharliePoole** [comment]
This is really general information, not especially related to parallelism. Maybe we need a page to which the parallel attributes refer.

**Comment by SeanKilleen** [comment]
🧹 Housekeeping -- going to close this old issue because I believe it is covered in the warning in https://docs.nunit.org/articles/nunit/writing-tests/attributes/parallelizable.html which states:

> When tests are run in parallel, you are responsible for the thread safety of your tests. Tests that run at the same time and modify instance fields or properties without locks will cause unexpected behavior as they would in any multi-threaded program. If you are using fields or properties between parallel tests consider using the FixtureLifeCycleAttribute to construct a new instance of a test fixture (class) for each test that is run.

If anyone disagrees feel free to re-open and I'm happy to consider it. 👍

**Comment by CharliePoole** [comment]
I often tell people that Parallelizable doesn't actually tell NUnit to do anything... Rather, it just makes a promise to NUnit that your tests are capable of running in parallel.
