### ISSUE TITLE
What's the best practice for culture invariant string comparison?

### ISSUE THREAD

**Issue by KubaOczko** [nunit/docs#243]
I want to use  something like  `Assert.That("ABCH" , Does.StartWith("ABC"));` but in some cultures CH is considered as a letter and test is failing. 

I didn't find any option how to set invariant comparer for string assertions. I can change the current thread culture but I don't think that it's something I want to do in test.

**Comment by CharliePoole** [comment]
You can use SetCulture attribute on a test, which will only affect that test. Otherwise, to affect the single assert, check out various overloads of Using on the constraint.

**Comment by KubaOczko** [comment]
> Otherwise, to affect the single assert, check out various overloads of Using on the constraint.

Maybe I'm missing something but Using method with string comparer is not available for StartsWith/EndsWith constraint. It's available for SubstringConstraint only.

**Comment by ChrisMaddock** [comment]
> Maybe I'm missing something but Using method with string comparer is not available for StartsWith/EndsWith constraint. It's available for SubstringConstraint only.

I think you're correct. I think this is something the team would consider accepting a PR for, if you wanted to raise it in the nunit/nunit repo.

I think it depends on what you actually want to test. If you want to not run this particular test in certain cultures, you can look at the [Culture Attribute](https://github.com/nunit/docs/wiki/Culture-Attribute#test-syntax). If you want to make sure that the comparison always runs with an invarient culture, you can use `[SetCulture("")]` on the test method.
