### ISSUE TITLE
Revise and move Text-Output-from-Tests-Spec to Usage Notes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#246]
https://github.com/nunit/docs/wiki/Text-Output-from-Tests-Spec

**Comment by SeanKilleen** [comment]
@CharliePoole do you think these contents are still largely accurate? If so, I can perform this move.

**Comment by CharliePoole** [comment]
@SeanKilleen It's probably about 50% accurate today and not really needed so much. It was originally written to explain a major change from NUnit V2 to NUnit3, but that was a long time ago. I'd suggest deleting it if nobody objects.

**Comment by SeanKilleen** [comment]
It's had almost no views on the new site, and since that's been active for a while, I'm OK with saying we can delete it. 👍 

PR incoming.
