### ISSUE TITLE
Revise and move Generation-of-Test-Names-Spec to Usage Notes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#247]
https://github.com/nunit/docs/wiki/Generation-of-Test-Names-Spec

**Comment by ChrisMaddock** [comment]
Can you add some more details here Charlie? What are you thinking that we need, in addition to the page below?

https://github.com/nunit/docs/wiki/Template-Based-Test-Naming

**Comment by CharliePoole** [comment]
I created these issues so as to have something to remind us what needed to be cleaned up but I didn't review any of the docs. (I reviewed others and fixed them without an issue - these issues are the ones I didn't actually do myself.)

From a quick read-through it seems like this one is covered and can be deleted.

**Comment by SeanKilleen** [comment]
Updating this: I'll take an action to remove the `Generation of Test Names` spec page as it's already covered.
