### ISSUE TITLE
I am trying to use custom attributes, for executing tasks before and after every test method run

### ISSUE THREAD

**Issue by vigneshwar-v** [nunit/docs#25]
I have implemented ITestAction interface and overrided before&after test methods, but I cant catch the exception thrown at the end of every test.

**Comment by vigneshwar-v** [comment]
the ITest argument doesnt have much details other than test method name, class name and method info. Can I get the exception/return value thrown by a test method inside after test method?

**Comment by CharliePoole** [comment]
FYI, you will probably get a faster response to questions on the nunit-discuss forum. This is the repository for the NUnit documentation, and is for issues about things that need fixing in the docs. Of course, if the docs have not answered your question, maybe this is an issue for here. :-)

The ITest interface represents a general test case. To get more information, you would have to cast it to a concrete type, such as TestMethod.

However, the information you are looking for is not stored in either the test method or its result. The exception is immediately translated to an NUnit TestResult. You can examine the TestResult through the current TestContext. If a non-NUnit exception was thrown, the error message contains the name of the type and it's Message. The stack trace is also available.
