### ISSUE TITLE
Wiki:ListMapper - "three" -> "two"

### ISSUE THREAD

**Issue by oleggavril** [nunit/docs#252]
![2017-12-15_1446](https://user-images.githubusercontent.com/13567095/34042790-f4145d14-e1a6-11e7-859f-ca2fa8d2bc20.png)

**Comment by ChrisMaddock** [comment]
Looks like I did a pretty rubbish job of removing the old `AssertionHelper` docs. Fixed - thanks for flagging it! 😄

**Comment by oleggavril** [comment]
Thanks Chris! 👍
