### ISSUE TITLE
NUnit3 console runner is not running assemblies in parallel

### ISSUE THREAD

**Issue by atlemann** [nunit/docs#253]
I have tried passing a .sln file and a list of .csproj files and with and without setting the following arguments: `--workers=8 --agents=8 --domain=multiple --process=multiple`. All I get is one `nunit3-console.exe` and one single `nunit-agent.exe`. How do I make it run all test assemblies in parallel?

My unit-tests are Nunit2 and I'm running nunit console runner v3.7.0 on windows.

**Comment by ChrisMaddock** [comment]
What's you're exact command line? This looks like it should work.

If you're passing multiple csproj's - you shouldn't need any of these arguments, and it should run in parallel by default, I believe. Passing the sln file _may_ be hitting https://github.com/nunit/nunit-console/issues/116, but using the `--process=multiple` flag should sort that out.

**Comment by ChrisMaddock** [comment]
If the above doesn't help, please run with `--trace=Debug`, and share the logs.

**Comment by CharliePoole** [comment]
Someone the listed options are contradictory and the runner makes no promises to which will win. Most likely it will be the last one.

If your goal is to run each test assembly in parallel, eliminate all of them. If you want to run a smaller number than you actually have in parallel, include --agents. The others are just confusing the issue unless you really want to have 64 (8x8) threads of execution.

**Comment by atlemann** [comment]
I'll run with `--trace=Debug` tomorrow and send the logs. I just want to multiple assemblies in parallel, since I have more than 50 test assemblies (I know, the solution is way too big). I'm trying to reduce the build time on TeamCity and running the Nunit3 test runner there seems to pass only one assembly at a time to the Nunit3 console runner, so I was trying to run a custom command line step instead.

**Comment by rprouse** [comment]
If TeamCity is only passing one assembly at a time on the command line, then you need to take up the issue with them. If you pass multiple assemblies on the command line to NUnit Console, it will run them in parallel. You can drop all of those command line options and just just `nunit3.console.exe test1.dll test2.dll test3.dll` and NUnit will handle it for you.

**Comment by atlemann** [comment]
That's why I tried to create a command line build step, instead of the Nunut3 build step, where I passed in all assemblies. I also tried on my local machine in PowerShell, but I still only get one agent running at a time, even though I passed in over 50 test assemblies.

**Comment by CharliePoole** [comment]
But are you passing them __directly__ as @rprouse suggested or by passing the solution?

I realize you may not want to pass 50 assemblies on the command-line, but distinguishing between how it's handled when passing assemblies versus csproj files versus solution files is an important step in figuring out what's wrong.

**Comment by atlemann** [comment]
- `nunit3-console.exe My.sln`: Spawns a `single` nunit-agent process at a time
- `nunit3-console.exe test1.csproj test2.csproj test3.csproj`: Spawns a `single` nunit-agent process at a time
- `nunit3-console.exe test1.dll test2.dll test3.dll`: Spawns `multiple` nunit-agents in parallel

**Comment by CharliePoole** [comment]
The failure of `nunit3-console.exe My.sln` is an example of nunit/nunit-console#116. That issue is stated to apply only to the __default__ process model. What happens if you add `--process:Multiple` to it?

OTOH the example using three `.csproj` files is new to me. Same question: what if you add `--process:Multiple`?

The third example, of course, is the way it's supposed to work!

**Comment by atlemann** [comment]
`nunit3-console.exe --process=multipe My.sln` fixes the problem! I guess I tried with too many arguments before. Thanks for the help. Much appreciated.

I do get this though, but the test run is marked as `Passed`:
Unhandled Exception: NUnit.Engine.NUnitEngineException: Unable to unload AppDomain, Unload thread timed out.
Agent Process was terminated successfully after error.
   at NUnit.Engine.Runners.ProcessRunner.Dispose(Boolean disposing)
   at NUnit.Engine.Runners.AbstractTestRunner.Dispose()
   at NUnit.Engine.Runners.TestExecutionTask.Execute()
   at NUnit.Engine.Runners.ParallelTaskWorkerPool.ProcessTasksProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by CharliePoole** [comment]
The message about unloading the AppDomain would suggest that some thread in your test is not being terminated.

So, at this point, the only new wrinkle seems to be the use of multiple .csproj files on the command line. I'll make a note on nunit/nunit-console#116 and close this.
