### ISSUE TITLE
What location are results written on to the listening server?

### ISSUE THREAD

**Issue by pMaske** [nunit/docs#256]
I am running out of the box Nunit test template, made no change except for tcpwriterinfo.
I tried following and the line of code didn't fail which indicates file is successfully written but I am confused where does the result file gets written  on remote machine? How can I locate it?

TcpWriterParameters = new TcpWriterInfo("RemoteMachine", 80),

**Comment by ChrisMaddock** [comment]
This is nunit.xamarin, correct?

The TcpWriter first the results to a port and IP adress - you need to set up something to listen to that port to get the information. There's an example of that on the original Pull Request: https://github.com/nunit/nunit.xamarin/pull/50#issuecomment-193249831

Are you running the tests on actual devices? If you can access the simulator device itself you may find the `CreateXmlResultFile` and `ResultFilePath` options a simpler solution - so you can specify the location the results file gets written, and then just retrieve the file.

**Comment by pMaske** [comment]
>This is nunit.xamarin, correct?

Yes

>Are you running the tests on actual devices?
Yes

But after tests are run on the device, I need the results summary to be available on the machine device is tethered to which is also my Jenkins server. Then I will use that file to report via Jenkins. And I stuck at achieving this for very long...

**Comment by ChrisMaddock** [comment]
So you have two options I think.

1. You can use the `CreateXmlResultFile` and `ResultFilePath` options to create the result file in a known location on the device, and then retrieve this file with Jenkins, once the Tests have completed.

2. You could open a port on the Jenkins machine, and listen to the port to receive each test result 'as it happens'. That would be the use of TcpWriterParameters.

Personally, 1) seems like the simpler option, if you have access to retrieve the test file. I guess that depends how your device is set up.

**Comment by pMaske** [comment]
>then retrieve this file with Jenkins, once the Tests have completed.

I also like option one and have been trying to do this. The setup would be Jenkins machine will run a script that will create the apk and install and autorun the unit test app. After test run is complete, the results file from known location on the device should get copied to Jenkins server.

I know I can use adb command in a script to pull the file from device to the hard disk , but when should that command run. Time to run the tests and when test results will be available can vary in every run.

**Comment by rprouse** [comment]
You could combine the two by writing a simple TCP listener that listens for test events and either exits (as a signal), or uses adb to pull the results when the test finished event is received.

**Comment by pMaske** [comment]
Highly appreciate your responses @rprouse @ChrisMaddock 

@rprouse Is there any way you can expand a little more on your suggestions. 

>TCP listener that listens for test events 

Would this a separate app running on Jenkins server that would listen to running tests?

> or uses adb to pull the results when the test finished event is received.

Can I call adb from inside the unit test app?

**Comment by rprouse** [comment]
This is still very vapourware, but my idea is that the TCP listener is used as a build task in Jenkins and listens to the test running on the device. When it receives the test finished event, it exits, which finishes the build task, allowing the next build task to run which is the adb command to copy the results off the device.

**Comment by pMaske** [comment]
Ok, so I guess I am making progress...I wrote following code to Send file inside unit test app after the test run is complete.
                string resultsummary = System.IO.File.ReadAllText(TestOptions.ResultFilePath);
                try
                {
                    TcpClient client = new TcpClient();
                    Task connect = client.ConnectAsync("testserver", 80); //sending file to machine testserver on port 80
                    Task timeout = Task.Delay(TimeSpan.FromSeconds(30));
                    if (await Task.WhenAny(connect, timeout) == timeout)
                    {
                        throw new TimeoutException();
                    }
                    client.Client.SendFile(TestOptions.ResultFilePath); // Works fine ,I believe file is sent because there is no exception.
                    client.Close();
}

Now I beginning to write the receiver and I a stuck . When I run the program program is stuck at client.AcceptTcpClient()  forever. I was basing my code using sample https://gist.github.com/roubachof/ab3a9094f9fd9c1db9c6.

Any ideas why? Do I need to enable something on device to allow accepting clients. Can author of the sample code `roubachof` help?
```
 var localAddr = IPAddress.Parse("127.0.0.1");
string outputPath = @".\unittestsoutput.xml";                
IPEndPoint ipEndPoint = new IPEndPoint(localAddr, 0); //port 0 will get the first available one.
server = new TcpListener(ipEndPoint);
// Start listening for client requests.
server.Start();
// Buffer for reading data
var bytes = new byte[256];
// Enter the listening loop.
 while (true)
 {
Console.Write($"Waiting for a connection on {localAddr}:{port}, will drop output to {outputPath}");
  TcpClient client = server.AcceptTcpClient(); ////**** STUCK AT THIS LINE FOREVER
...
...

**Comment by rprouse** [comment]
Your send code is sending to the host `testserver` on port 80, but your server side code is listening on `127.0.0.1` which is the loopback address and not available outside of the machine. You are also specifying port 0 which tells it to specify a specific port, not port 80. 

Port 80 is also likely already used by your CI servers web interface, that is why the send is working, you are sending the file to the HTTP server. 

You should select a different port, maybe 8080, and use `IPAddress.Any` for the address. Next you will need to open that port for TCP in the Windows Firewall.

**Comment by pMaske** [comment]
I wanted to take a moment to thank @rprouse  and @ChrisMaddock . I was finally able to get the TCP client/server communication working. But I am actually trying something neater, I believe. In my batch script I am checking if the process running in while true loop. As soon as process is done I call adb pull to fetch the results to a local hard disk location. I will give it a few days of runs to ensure it's stability. If it doesn't work will switch back to TCP stuff.
Thanks again for all your inputs.

**Comment by pMaske** [comment]
@rprouse @ChrisMaddock , I am facing another challenge and was wondering if you can shed some light on it. When my unit test app auto-runs, it runs for a while. I have about 2000 unit tests. I have set TerminateAfterExecution to true but that doesn't work.  When I see the device, the UI seems kind of frozen and unresponsive. What actually happen when this property is set or do I have to add some CustomLogic.

**Comment by ChrisMaddock** [comment]
@pMaske - can you post your actual code of how you’re setting the property? But what you’re trying to do seems correct - it maybe that this functionality has a bug for your particular device. If so, we’d appreciate a Pull Request to fix it! 😄

**Comment by rprouse** [comment]
When we wrote the test adapter, it used a fairly old version of Xamarin.Forms that did not support `RecycleView` on the `ListView` that displays the test results. If you have 2000 tests, it will be creating 2000 listview items which is probably taking a very long time to complete. This is likely a bug with our runner, can you enter one in the NUnit.Xamarin project?

**Comment by pMaske** [comment]
ok, had to fix it this way..In    public static void TerminateWithSuccess()
#elif __DROID__
            Process.KillProcess(Process.MyPid());
            System.Environment.Exit(100);

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
