### ISSUE TITLE
Multiple Asserts compatible with SpecFlow SpecRunner?

### ISSUE THREAD

**Issue by realfaisalk** [nunit/docs#257]
Hi,

Just wondering what it would take to make Multiple Asserts compatible with SpecFlow SpecRunner so it reports all the assertions in the block?
Is it something NUnit can do, or do the SpecFlow team need to do something on their side?

Thanks

**Comment by CharliePoole** [comment]
While it's conceivable that NUnit might have to do something, it would probably take the SpecFlow team to tell us what that something might be. They will know exactly how they are using NUnit, which is the bit of info that the NUnit team doesn't have.

**Comment by sisillV** [comment]
Hi,
I am interested on this topic too... 
Or is there a way to just report Pass and Failed without stop the run of the test. Something like: Log Assert.Failed...

**Comment by rprouse** [comment]
I would recommend reaching out to the SoecFlow team. We can make changes, but only if they tell us what is needed. I suspect that everything is in place on our side that they need though. They likely just need to update to support it.

**Comment by SabotageAndi** [comment]
We have to add support for multiple asserts into the SpecFlow+Runner. I will add an entry to our product backlog for it.

**Comment by ChrisMaddock** [comment]
Thanks @SabotageAndi. Let us know if there's any enhancements on the NUnit side needed to make this work. 😄
