### ISSUE TITLE
NUnit3TestAdapter v3.9.0 not targeting .NETStandard2.0

### ISSUE THREAD

**Issue by Latency** [nunit/docs#258]
This appears to be a build & release issue.
Please update package!

![image](https://user-images.githubusercontent.com/788296/35777966-1b3c2530-0974-11e8-8df8-21728b2c6856.png)

![image](https://user-images.githubusercontent.com/788296/35777986-84fc4cb6-0974-11e8-815f-3709ab4a2262.png)

**Comment by rprouse** [comment]
Could you show us your csproj file? Looks like you are multi - targeting, but I don't know why you also have all of the dependencies listed in the root of your project. Also, what version of Visual Studio?

**Comment by jnm2** [comment]
@rprouse I can repro:

![image](https://user-images.githubusercontent.com/8040367/36310526-54ed014c-12f6-11e8-8b73-e529f7e3c92a.png)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.0;net45;net471;netstandard2.0</TargetFrameworks>
    <DebugType>Full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
  </ItemGroup>

</Project>
```

**Comment by jnm2** [comment]
@OsirisTerje do we have time to fix this for 3.10? I can work on it this evening EST.

**Comment by jnm2** [comment]
Wait duh, I see the problem. @Latency .NET Standard is not considered a valid test project target (or executable project target) by the .NET Core SDK. We don't yet have the tools to make that happen, though .NET Standard tests would be far superior to the situation we're in today.

Follow https://github.com/dotnet/sdk/issues/1561. You may find the discussion starting at https://github.com/Microsoft/msbuild/issues/1310#issuecomment-346102103 to be interesting. In the meantime, you'll have to remove .NET Standard from your list of targets in your test project.

**Comment by jnm2** [comment]
Going to close as a duplicate in principle of https://github.com/nunit/nunit3-vs-adapter/issues/379.
