### ISSUE TITLE
Links are broken on the Custom Attributes page

### ISSUE THREAD

**Issue by dlech** [nunit/docs#259]
On the page: https://github.com/nunit/docs/wiki/Custom-Attributes

I assume the table values are supposed to be links to other pages, but they appear to be broken. There is a `[[` or `]]` shown depending on the column.

**Comment by jadarnel27** [comment]
Thanks for reporting this!  The pipes used in the wiki links needed to be escaped since they were inside table formatting.  I've corrected the page so it renders properly now.

**Comment by dlech** [comment]
Much better, thanks!
