### ISSUE TITLE
Incorrect activeConfig attribute name

### ISSUE THREAD

**Issue by maliutin** [nunit/docs#262]
In [NUnit Project XML Format][1] description `activeConfig` attribute name has incorrect `C` character:
![image](https://user-images.githubusercontent.com/10669340/37705145-1472a984-2d0c-11e8-81a7-9f9291c7945d.png)

My tests showed that it should be `activeconfig`. Only, in this case, it works correctly.
![image](https://user-images.githubusercontent.com/10669340/37705259-7ee7acba-2d0c-11e8-9a44-aca5b047c25b.png)

  [1]: https://github.com/nunit/docs/wiki/NUnit-Project-XML-Format

**Comment by mikkelbu** [comment]
Apparently, @ChrisMaddock has just updated this 😄 . Thanks for the notice @maliutin 👍 .

**Comment by ChrisMaddock** [comment]
Sorry, got distracted mid way though! Thanks! 😄
