### ISSUE TITLE
Broken download link in documentation

### ISSUE THREAD

**Issue by refaelsh** [nunit/docs#268]
Hello,

There is a broken download link in documentation.
Here: https://github.com/nunit/docs/wiki/Installation#downloading-the-zip-file,
the download link is broken.

Thanks. Refael.

**Comment by mikkelbu** [comment]
@nunit/framework-and-engine-team To begin with I've changed the link to http://nunit.org/download/. But this is just a (pretty) indirection to the GitHub releases, so it is a bit of duplication both to have links to http://nunit.org/download/ and to GitHub releases. What do you think?

**Comment by CharliePoole** [comment]
There's also a link to older releases, which are not all on GitHub.

**Comment by ChrisMaddock** [comment]
I removed the duplicate link - thanks @rafaelsh!
