### ISSUE TITLE
Does the latest Nunit console supports .net version 4.7.2?

### ISSUE THREAD

**Issue by vijaynagr** [nunit/docs#277]
We have moved to .net runtime version 4.7.2. When I run the tests on that machine, the tests are not running, but the result is appearing to be Passed. Wondering is that because of the latest .net version. 
Can someone please help clarify this for me. 

Thanks in advance.

**Comment by jnm2** [comment]
I can't think of any way it would be related to NUnit Console, but anything's possible. Maybe your tests are doing something 4.7.2-specific? My best advice would be to cut it down to a minimal repro and then we can see if it's related to NUnit or a more general issue.

Once you do that, if you think it might still be specific to NUnit, please open an issue at https://github.com/nunit/nunit-console/issues. This issue tracker is for NUnit documentation itself, as the issue template indicates.
