### ISSUE TITLE
Typo on RangeAttribute wiki page

### ISSUE THREAD

**Issue by christianMurschall** [nunit/docs#278]
I noticed on the [Attribute Wiki Page](https://github.com/nunit/docs/wiki/Range-Attribute/9cd1c1ee8d89299f2a4aab152772e5a722e070af) an typo at the example (misssing '`)`' )
Instead of `[Range(0.2, 0.6, 0.2] double d)` it should be `[Range(0.2, 0.6, 0.2)] double d)`

As a matter of fact the Values Attribute in the example is also a missing `]`

I would have loved to create a PR but I have no Idea on how to do it on a wiki.

**Comment by mikkelbu** [comment]
Hi @christianMurschall 
Thanks for reporting the typos. I've corrected them as unfortunately PRs are not supported by github wikis (see eg https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github or the discussion in #147), so only people with write access can (easily) make changes to the wiki.
