### ISSUE TITLE
Document Dictionary constraints

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#282]
I may be wrong, but I couldn't find any documentation for DictionaryContainsKeyConstraint, and DictionaryContainsValueConstraint. Both of these should be documented.

**Comment by mikkelbu** [comment]
I think you are right. I could only find mentions of `DictionaryContainsKeyConstraint` in
[Summary Under Development](https://github.com/nunit/docs/wiki/Summary-Under-Development) and [Pre 3.5 Release Notes](https://github.com/nunit/docs/wiki/Pre-3.5-Release-Notes) and not mention of `DictionaryContainsValueConstraint`.

**Comment by oriash93** [comment]
[DictionaryConstraints.zip](https://github.com/nunit/docs/files/2717463/DictionaryConstraints.zip)


Added new pages for both constraints, also updated the general Constraints page.

**Comment by ChrisMaddock** [comment]
This is brilliant - thanks @oriash93! Adding these pages in now. 😄

**Comment by ChrisMaddock** [comment]
Done - thanks!
