### ISSUE TITLE
ParallelScope has one additional undocumented value

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#284]
@oznetmaster commented on [Sun Sep 09 2018](https://github.com/nunit/nunit/issues/3010)

There is a ParallelScope.All value which is the same as ParallelScope.Self + ParallelScope.Children.

It is visible in Intellisense, but is not documented.

---

@ChrisMaddock commented on [Mon Sep 10 2018](https://github.com/nunit/nunit/issues/3010#issuecomment-420040720)

Looks that way to me - moving this issue to docs. 🙂 

(Edit: no I'm not - no Zenhub on my tablet. 'To be moved' by the next person capable!)

**Comment by mikkelbu** [comment]
@nunit/framework-team Made addition to https://github.com/nunit/docs/wiki/Parallelizable-Attribute, please review and close issue.

**Comment by CharliePoole** [comment]
LGTM
