### ISSUE TITLE
Assert.ThrowsAsync sample test produces CS1998 warning

### ISSUE THREAD

**Issue by origameg** [nunit/docs#285]
The sample test for Assert.ThrowsAsync that stores the resulting Exception generates a CS1998 warning.
```
[TestFixture]
public class UsingReturnValue
{
  [Test]
  public async Task TestException()  // CS1998  This async method lacks 'await' operators and will run synchronously.
  {
    MyException ex = Assert.ThrowsAsync<MyException>(async () => await MethodThatThrows());

    Assert.That(ex.Message, Is.EqualTo("message"));
    Assert.That(ex.MyParam, Is.EqualTo(42)); 
  }
}
```
Since `Assert.ThrowsAsync` is a synchronous method, one would expect the return type for the test method to be void.

**Comment by mikkelbu** [comment]
Closing this as the this was fixed in https://github.com/nunit/docs/pull/704/files#diff-04b36b3d212c841bdd29884136eb1766ca62fe3b52579d5503a3b09111bdc63d
