### ISSUE TITLE
TestCategory not visible when applied at TestFixture level

### ISSUE THREAD

**Issue by OnamChilwan** [nunit/docs#286]
Is it possible to use `Category` at `TestFixture` level? It doesn't seem to pull out the category when I do. I am expecting using `Category` at either `TestFixture` or `Test` level I would expect the same output, in this case the list of categories should contain the value **"My Category"**.

This is an example of it not working:
```
    [TestFixture]
    [Category("My Category")] //At this level no categories are populated
    public class SomeTests
    {
        [Test]
        public void Foo()
        {
            IList categories = (IList)TestContext.CurrentContext.Test.Properties["Category"];

            foreach (var category in categories)
            {
            }
        }
    }
```

This works correctly:
```
    [TestFixture]
    public class SomeTests
    {
        [Test]
	[Category("My Category")] //This works fine
        public void Foo()
        {
            IList categories = (IList)TestContext.CurrentContext.Test.Properties["Category"];

            foreach (var category in categories)
            {
            }
        }
    }

```

Packages and Frameworks:

> - .NET Core 2.1.201
> - NUnit 3.10.1
> - NUnitTestAdapter 3.10.0
> - Microsoft.NET.Test.Sdk 15.7.0

Thanks in advance.

**Comment by CharliePoole** [comment]
Every test has its own context, including the fixture itself,which is a test containing other tests. The context of the fixture can only be accessed in the OneTimeSetUp and OneTimeTearDown for the fixture.

**Comment by OnamChilwan** [comment]
That works perfectly thank you.

**Comment by jnm2** [comment]
I believe `TestContext.CurrentContext.Test.Parent.Properties["Category"]` also works.

See also https://github.com/nunit/nunit/issues/2674.
