### ISSUE TITLE
How to contribute to the wiki?

### ISSUE THREAD

**Issue by slang25** [nunit/docs#291]
I have a minor fix I'd like to make to the wiki, but cannot figure out how to do it, is editing completely private or am I missing something?

**Comment by mikkelbu** [comment]
Hi @slang25 
Unfortunately, the support for changes and PRs to GitHub wikis are not very good, see e.g. https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github. Depeding on the size of the change you can e.g. just write it in the comment, or you can clone the wiki, make commit, and then us merge the changes from your branch (as mentioned in the link).

Ps. I know that there has been some discussion about moving the documentation to something else that will support more easily user interaction (e.g. similar to the new MS documentation site).

**Comment by OsirisTerje** [comment]
We have the documentation in its own repo, and we only use the wiki part of it.  We could move the content to the code part, and then have a process that just copies it down to the wiki.  That way we could use normal PRs on the content.

**Comment by mikkelbu** [comment]
Thanks for the heads up @slang25. I've corrected the link and will close this issue, but we will still consider moving the wiki to something more usable.
