### ISSUE TITLE
Parameterized Test Fixtures

### ISSUE THREAD

**Issue by sheikhjebran** [nunit/docs#298]
Parameterized Test Fixtures is not working on Nunit3.8.0

**Comment by mikkelbu** [comment]
Hi @sheikhjebran 
This repository is for the NUnit documentation, and not for issues with NUnit. Version 3.8 had a couple of issues, see https://github.com/nunit/nunit/releases/tag/3.8.1, but nothing about parameterized test fixtures as far as I know. That begin said I think you'll need to provide some more information for us to help you (and to move this issue to the right repository):
* What did you do
* What did you expect
* How are the tests executed
* ...
The more information you provide the better answers we can give.

**Comment by CharliePoole** [comment]
Hi @sheikhjebran ,

This is the repo for reporting issues with the docs. Could you file an issue on the nunit framework please? It's https://github.com/nunit/nunit

In your report, please tell us exactly what isn't working, preferably with a code sample.

**Comment by CharliePoole** [comment]
@mikkelbu Seems we crossed.   :smiley:

**Comment by sheikhjebran** [comment]
Hi Mikke,
Thank you so much for your reply, i shall re-correct it . and i got answer
to my problem as well,
Regards,
Sheikh jebran

**Comment by sheikhjebran** [comment]
closing with respect to above comment
