### ISSUE TITLE
Description from TestContext.AddTestAttachment does not displays in TEst Output window

### ISSUE THREAD

**Issue by CMALD** [nunit/docs#301]
![description](https://user-images.githubusercontent.com/46340089/53882724-c97bac00-401f-11e9-85af-c278a62aa3a2.PNG)
My code is: 

      var v = @"C:\Screenshots\1.Jpeg";
      TestContext.AddTestAttachment(v , "Description Test Attachment");

and as the screenshot, I see only the picture name and not the description

Thanks.

**Comment by OsirisTerje** [comment]
Which tool do you use ?

**Comment by CMALD** [comment]
Nunit3 +Selenium WebDriver

**Comment by CharliePoole** [comment]
We need to know what tool you use to execute the tests. For example, nunit console runner, nunit is test adapter, some 3RE party runner. Usually, it's up to the runner to decide what to display.

**Comment by CMALD** [comment]
![nunit test runner](https://user-images.githubusercontent.com/46340089/53936951-42c4de80-40b4-11e9-8786-54f8a35ee501.PNG)
See attached screenshot

**Comment by CMALD** [comment]
This is perhaps called "VS Test Adapter"?

**Comment by CharliePoole** [comment]
If you are able to run nunit3 tests in Test Explorer, then you have almost certainly installed the NUnit 3 VS adapter somewhere. It would help to know which version.

**Comment by CharliePoole** [comment]
I'm on my phone right now, but as soon as I get onto my computer I'll transfer this to the correct project... unless someone else does it first!

**Comment by CMALD** [comment]
I has NuGet Package : NUnit3TestAdapter v3.13.0

**Comment by mikkelbu** [comment]
Issue moved to [nunit/nunit3-vs-adapter #618](https://github.com/nunit/nunit3-vs-adapter/issues/618) via [**ZenHub**](https://www.zenhub.com/)
