### ISSUE TITLE
How to set the 'build agent' directory

### ISSUE THREAD

**Issue by henrikgjeriksson** [nunit/docs#303]
This is more of a question,
How to set the "build agent" working directory?

**Comment by CharliePoole** [comment]
Can you expand the question a bit?

By "build agent" what do you mean? NUnit-agent? The agent in some CI system?

By "working directory" do you mean the current Directory or the NUnit WorkDirectory where test output is saved?

If you aren't sure of either of those, try to explain what you are trying to accomplish instead.

**Comment by henrikgjeriksson** [comment]
Here is a log printout
[JetBrains dotCover] Coverage session finished with errors: Error HRESULT E_FAIL has been returned from a call to a COM component
PDB server error: Invalid MVID for the absolute module path is detected
 [location] = c:\build agent\work\cf3eb19e8ddb7658\profiler\kernel\windows\native\solution\pdb_server\src\pdb_processor.cpp(174)
 [function] = unsigned int __cdecl jbprof::pdb_processor::load_module(const class boost::filesystem::path &,const struct _GUID &)
 [location] = c:\build agent\work\cf3eb19e8ddb7658\profiler\kernel\windows\native\solution\core\src\bridges\pdb\pdb_bridge.cpp(195)
 [function] = void __thiscall jbprof::pdb_bridge::send_receive_command(const char *,enum jbprof::pdb_bridge::time_key,enum jbprof::pdb_bridge::time_key,enum jbprof::pdb_bridge_command,enum jbprof::pdb_bridge_answer,class std::function<void __cdecl(struct write_stream_iface* )>,class std::function<void __cdecl(struct read_stream_iface *)>); Error HRESULT E_FAIL has been returned from a call to a COM component

**Comment by OsirisTerje** [comment]
@henrikgjeriksson What is the context here?   Ref @CharliePoole questions.  
The log is from JetBrains DotCover
The folders may indicate Azure Pipelines, but could be anything else too.
What is the "thing" that calls DotCover ?

**Comment by henrikgjeriksson** [comment]
The root issue:
We have a cakebuild ci pipeline, which calls dotCover (which runs Nunit3 tests)
Now our current win laptops are getting replaced with new ones, incorporated by a larger concerns windows framework.
Execution of the pipeline on the previous windows system works fine, but it does not on the new system.

Noted is that execution of dotCover itself works fine on the new system. Also noted is that McAfee is executing on the new system. And we are not allowed to turn it of.

**Comment by OsirisTerje** [comment]
Do your project includes the latest versions of NUnit?  
Do you use the NUnit console runner, or do you use the NUnit3TestAdapter?,  and again, which versions?
How do you call DotCover ?  What is the config ?
Is there a change of WIndows versions between old and new?
Can you set up a small repro project ?

**Comment by henrikgjeriksson** [comment]
#tool nuget:?package=NUnit.ConsoleRunner&version=3.9.0
#tool nuget:?package=NUnit.Extension.NUnitV2ResultWriter&version=3.6.0
#tool nuget:?package=JetBrains.dotCover.CommandLineTools&version=2018.3.4

**Comment by henrikgjeriksson** [comment]
From cakebuild pipeline, dotCover is called using https://cakebuild.net/dsl/dotcover/
And Nunit3 is called using https://cakebuild.net/dsl/nunit-v3/

**Comment by henrikgjeriksson** [comment]
Will comeback related to the other questions.

**Comment by CharliePoole** [comment]
Quite a chain of product dependencies! If it were me, I might try a sequence like the following on the new laptops...

1. Run nunit-console from the command-line, using the same options that are being passed to it by dotCover and, of course, the same version of the console runner.

2. Run dotCover from the command-line in the same way, invoking NUnit.

3. Write a small cake script that uses the DSL to invoke dotcover, but without any other stuff that may be in your existing script.

My guess is that you'll learn more at one of these points or the other.

**Comment by ChrisMaddock** [comment]
Closing this, as there's not enough information to understand/reproduce the problem. 

Happy to reopen if anyone has more to add. 🙂
