### ISSUE TITLE
No TestFixture documentation on the side bar

### ISSUE THREAD

**Issue by jpfreyen** [nunit/docs#308]
Look at the NUnit 3 documentation and search for 'TestFixture':

https://github.com/nunit/docs/wiki/NUnit-Documentation

Can't find it, right?

Now go to the old NUnit 2 documentation and look for 'TestFixture'.

http://nunit.org/docs/2.6.3/platform.html

It's right there for viewing.

The old NUnit 2.+ documentation is way easier to find stuff than the new NUnit 3 documentation, unfortunately.  Google always picks up NUnit 2.+, thank god.

**Comment by mikkelbu** [comment]
You are right that Githubs wiki is not ideal for documentation (it also makes it difficult for people to supply changes and improvements to the documentation). But it is possible to search it. If you search for testfixture you get https://github.com/nunit/docs/search?q=testfixture&type=Code and Github says that there is no code matching, but there are hits on the wikis tab - currently 51 - and the first one is the primary page.

Also searching for "nunit documentation testfixture" (without the quotes) in Google gives me the same result.

That being said I wouldn't mind replacing the wiki with something else.

**Comment by jpfreyen** [comment]
Thanks for the insight and clarity.  Boy, that is not intuitive...

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
