### ISSUE TITLE
File Type Not supported issue

### ISSUE THREAD

**Issue by manojmsrit** [nunit/docs#311]
I am getting "File Type Not Supported" error when i try to run nunit3-cosole.exe from my mac os. Can you please suggest regarding the issue

+ mono /Users/manojdeshpande/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe Test.kommmit.Offers/Test.kommmit.Offers.csproj --result=nunit-result1.xml -config=Debug
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
Tuesday, May 21, 2019 10:37:28 PM

Runtime Environment
   OS Version: MacOSX 17.7.0.0 
  CLR Version: 4.0.30319.42000

Test Files
    Test.kommmit.Offers/Test.kommmit.Offers.csproj

Errors, Failures and Warnings

1) Invalid : /Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/Test.kommmit.Offers/Test.kommmit.Offers.csproj
File type is not supported

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-05-21 20:37:29Z
    End time: 2019-05-21 20:37:30Z
    Duration: 1.713 seconds

**Comment by mikkelbu** [comment]
Looks like you have installed `NUnit.ConsoleRunner` which is without any extensions, and you need an extension to load Visual Studio projects.

You can either use `NUnit.Console` instead then you among other also get `VSProjectLoader` which loads tests from Visual Studio projects. Or you can download the `VSProjectLoader` extension - called NUnit.Extension.VSProjectLoader on nuget - and place it in the appropriate location (this happens automatically using nuget, chocolatey as far as I can remember).

I'm closing this as answered, but we still see additional comments in the issue.

Ps. `.\nunit3-console.exe --list-extensions` will show you the installed extensions.

**Comment by manojmsrit** [comment]
Hello , Thank you for the response, Below is the output for the " .\nunit3-console.exe --list-extensions" . I am struck again, how to load the "VSProjectLoader" extension to this , can you please provide me the steps.

(base) MANOJs-MacBook-Air:angebotsapp manojdeshpande$ mono /Users/manojdeshpande/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe --list-extensions
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
Wednesday, May 22, 2019 6:54:39 PM

Runtime Environment
   OS Version: MacOSX 17.7.0.0 
  CLR Version: 4.0.30319.42000

Installed Extensions
  Extension Point: /NUnit/Engine/NUnitV2Driver
  Extension Point: /NUnit/Engine/TypeExtensions/IService
  Extension Point: /NUnit/Engine/TypeExtensions/ITestEventListener
  Extension Point: /NUnit/Engine/TypeExtensions/IDriverFactory
  Extension Point: /NUnit/Engine/TypeExtensions/IProjectLoader
  Extension Point: /NUnit/Engine/TypeExtensions/IResultWriter


And i downloaded NUnit.Console but i could not find the NUnit3-console in the folder to run the test files. When i download and extract NUnit.Console below is the folder structure. Can you please suggest me am i missing something here,

bin
  net20
  net35
  netcoreapp1.1
  netcoreapp2.0
  netstandard1.6
  netstandard2.0
CHANGES.txt
License.rtf
LICENSE.txt
NOTICES.txt
nunit.ico

I am really struck in this issue, Thank you in advance, Please help me out

**Comment by ChrisMaddock** [comment]
Hi @manojmsrit - it should be inside the net20 folder.

**Comment by manojmsrit** [comment]
Hello, Thank you for the response, I could able to run the test file now , but encountered new error,
I am sorry to write again, Is it something wrong with the file or am i missing something .

Time Elapsed 00:00:02.73
+ mono /Users/manojdeshpande/Downloads/NUnit.Console-3.10.0/bin/net20/nunit3-console.exe Test.kommmit.Offers/Test.kommmit.Offers.csproj --result=nunit-result1.xml -config=Debug
NUnit Console Runner 3.10.0 (.NET 2.0)
Copyright (c) 2019 Charlie Poole, Rob Prouse
Wednesday, May 22, 2019 8:04:05 PM

Runtime Environment
   OS Version: MacOSX 17.7.0.0 
  CLR Version: 4.0.30319.42000

Test Files
    Test.kommmit.Offers/Test.kommmit.Offers.csproj


Errors, Failures and Warnings

1) Invalid : /Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/Test.kommmit.Offers/bin/Debug/netcoreapp2.2/Test.kommmit.Offers.dll
File not found: /Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/Test.kommmit.Offers/bin/Debug/netcoreapp2.2/Test.kommmit.Offers.dll

Test Run Summary
  Overall result: Failed
  Test Count: 0, Passed: 0, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-05-22 18:04:05Z
    End time: 2019-05-22 18:04:06Z
    Duration: 0.813 seconds

**Comment by ChrisMaddock** [comment]
Ah - you’re using .NET Core.

The Nunit console doesn’t yet support .NET Core, for now, you need to use the test adapter instead. Try following the guide below:

https://github.com/nunit/docs/wiki/.NET-Core-and-.NET-Standard

**Comment by manojmsrit** [comment]
Hello, sorry again. I came up with new error, I am getting below error when i try to use "dotnet test", can you please suggest me regarding this

dotnet test Test.kommmit.Offers/Test.kommmit.Offers.csproj
Build started, please wait...
/usr/local/share/dotnet/sdk/2.2.107/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETPortable,Version=v4.5,Profile=Profile259" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/kommmit.Offers/kommmit.Offers/kommmit.Offers.csproj]
/usr/local/share/dotnet/sdk/2.2.107/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETPortable,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
Before this error i got one more error shown as below which i resolved by updating path of "Microsoft.Portable.CSharp.targets" manually.

dotnet test Test.kommmit.Offers/Test.kommmit.Offers.csproj
Build started, please wait...
/Users/manojdeshpande/.jenkins/workspace/Test_Local_Angebotsapp/kommmit.Offers/kommmit.Offers/kommmit.Offers.csproj(220,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/2.2.107/Microsoft/Portable/v4.5/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
