### ISSUE TITLE
Small typo in nunit/docs/wiki/Test-Selection-Language

### ISSUE THREAD

**Issue by lsolano** [nunit/docs#313]
The page nunit/docs/wiki/Test-Selection-Language has a small typo on the following paragraph:

> For matching regular expressions, NUnit users .NET's Regex.IsMatch method. For detailed information on the syntax of regular expressions in .NET, see ...

It should be 

> For matching regular expressions, NUnit uses .NET's Regex.IsMatch method.

Change **_users_** to **_uses_**.

**Comment by mikkelbu** [comment]
Thanks for reporting this @lsolano, I've corrected the typo.
