### ISSUE TITLE
Serveral duplicated words

### ISSUE THREAD

**Issue by lsolano** [nunit/docs#314]
Duplicated words

- **nunit\Assert.Greater.md:**
> **Assert.Greater** tests whether one object is greater **than than** another.`

- **nunit\Assert.Less.md:**
> **Assert.Less** tests whether one object is less **than than** another.`

- **nunit\Assert.Throws.md:**
> The Type format is available in **both both** a non-generic and generic form.

- **nunit\Assumptions.md:**
> **Note:** Failing assumptions indicate that running tests is invalid,  while [[Multiple Asserts]] allow testing to continue after a failure. For that reason, the two features are incompatible and assumptions may not be **used used** within a [[multiple assert|Multiple Asserts]] block.

- **nunit\EqualConstraint.md:**
> Two arrays, collections or IEnumerables are considered equal if they have **the the** same dimensions and if each of the corresponding elements is equal.

> 5. When an equality test between two strings fails, the relevant portion **of of** both strings is displayed in the error message,

- **nunit\Property-Attribute.md:**
> dialog of the gui. You may also **use use** properties with the `--where` option on the

- **nunit\Runtime-Selection.md:**
> By default, NUnit runs tests **under under** the runtime version for which the test

**Comment by jnm2** [comment]
@lsolano Thank you very much for providing these fixes. GitHub doesn't allow pull requests to wikis, but I locally added your fork as a remote and merged your `fix/dupWords` branch (the most recent commit autolinked above) and pushed to master. Your changes are now live. Hopefully I didn't do this before you were ready.

**Comment by lsolano** [comment]
Hi @jnm2 ,

I was a little confused about how to create the PR, I didn't know that GitHub does not permit those. Anyway, I was already done with the fixes. 

If anyone want to use it, this was the Regex used to find the issues: `\b(\w+)(\s+\1\b)+` full credits to "FARENDA" at [Java regex remove duplicated words](https://farenda.com/java/java-regex-remove-duplicated-words/).

Regards,

**Comment by jnm2** [comment]
Thanks!

@rprouse, do we still add people to a GitHub team to allow wiki edit rights?
