### ISSUE TITLE
Behaviour change of normal SetUp in NUnit 3.11

### ISSUE THREAD

**Issue by DontKnowThen** [nunit/docs#315]
Hello there,
We've just upgraded from 3.6 to 3.11 and noticed a lot of behaviour changes when running tests in parallel. We've worked around through some of them. But I now have 2 tests that inherit from a base class. This Base Class has a normal SetUp. So previously it worked with intention that it would create a unique user before each test, as SetUp is suppose to be called in the beginning of each test. But I see this is not the case any longer :( and SetUp is executed only once when running them in parallel. Therefore the same user is re-used in the second test which is wrong. Is this a bug or is there a new way of achieving a SetUp per test even when ran in parallel?
Nothing I could find in documentation about this either. It still says Setup should ran before each test.
Cheers.

**Comment by SeanKilleen** [comment]
Hi @DontKnowThen,

Apologies for not getting back to this issue for so long. I took over as docs project lead a little while back and while scanning old issues, came across this.

I think the best place to submit this issue, if you still require a response, will be [over at the nunit repo itself](https://github.com/nunit/nunit/issues/new).

I am closing this issue for now but don't hesitate to reach out again if it remains unresolved. And again, sorry for the radio silence!
