### ISSUE TITLE
How to run a testcase with params from cmd

### ISSUE THREAD

**Issue by tomern** [nunit/docs#316]
I have the following test

[TestCase(1, "Jim")]
[TestCase(2, "Donnie")]
public void TestSomething(int num, string name)
{
	// Do something	
}

As you can see, this test has 2 iterations, one for each test case.
I would like to run only the test case 2 (Donnie) from the cmd.

nunit3-console.exe 'C:\Automation.dll' --where "(method=TestSomething(2, "Donnie"))"

I get this error:

Unexpected token '(' at position 21 in selection expression.

Running this works but it runs both test cases.
nunit3-console.exe 'C:\Automation.dll' --where "(method=TestSomething)"

**Comment by CharliePoole** [comment]
In a where clause, method means the method name. So the first example is invalid. The second is valid and runs all tests that use that method.

You want test rather than method.

**Comment by tomern** [comment]
Not working, same error:
nunit3-console.exe 'C:\Automation.dll' --where "(test=TestSomething(2, "Donnie"))"

**Comment by CharliePoole** [comment]
Ah... it's your initial parenthesis giving the error. Don't wrap the where clause in parentheses. The earlier comments still apply however.

**Comment by tomern** [comment]
Not working

**Comment by CharliePoole** [comment]
OK... I was on my phone up to now. I had to try a few times on the computer so I guess it's not as easy as it should be! This should work for you...

```
--where test==`Some.Name.Space.SomeClass.TestSomething(2,\"Donnie\")`
```

Notes:
1. The above is for windows. On another OS, the command-line escaping necessary to have the double-quote character accepted may be different.
2. The test name is the __full__ name of the test method plus the args.
3. I used single-quote to surround the where clause, you can also use /.

Hope that helps. If you do have more problems, be sure to include your new command-line.

**Comment by tomern** [comment]
It works! thank you so much!

**Comment by mikkelbu** [comment]
Great. I'll close the issue and mark it as answered. We will still see additional comments.
