### ISSUE TITLE
Update Installation page

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#32]
https://github.com/nunit/docs/wiki/Installation refers to the alpha packages and such and needs a general update.

**Comment by ChrisMaddock** [comment]
I believe I've removed all the outdated references on this page, would someone else mind having a look through and seeing if anything else should be included? 

@rprouse - I noticed this page references using NUnitLite for CF and SL, but doesn't mention anything about portable - should it? It's not something I've ever used, would you mind adding something?

**Comment by CharliePoole** [comment]
@ChrisMaddock Not important to change, but fyi when I do an edit of a wiki page that is still in html, I generally change it to use github markdown exclusively. The html is inherited from earlier versions.

You could just add the portable framework to the other two but it may be worth mentioning that, by definition, there is no such thing as a portable NUnitLite. You have to pick, the platform under which you want to run tests. We distribute a runner that runs under .NET 4.5 and references the portable framework. This may be too much info for the installation page however... maybe it should be on the nunitlite page under running tests.

**Comment by ChrisMaddock** [comment]
@CharliePoole 
I've converted to markdown. Perhaps documenting how to run portable tests should be a separate issue entirely? It's not something I have any experience with, within NUnit or otherwise, so would prefer someone else to make any changes required there!

**Comment by CharliePoole** [comment]
@ChrisMaddock Looks good, I fixed the `<pre>` element.

@rprouse Where do you think we should document the ins and outs of using the portable framework?

**Comment by rprouse** [comment]
I was thinking that we should have a chart with every .NET Framework we support as the first column, the second column could be the NuGet package for the NUnit Framework and maybe the target. The third column can then link to a platform specific page on running tests for that platform.

Maybe something like this with all of our possible platforms added and the test runners linking to internal wiki pages if they are ready, or to blog posts for the Xamarin stuff until I write proper documentation. NuGet packages can also link to NuGet.

Platform | NuGet Package | NUnit Target | Test Runners 
----------- | ------- | --------- | -----------
.NET 2.0, 3.0, 3.5 | NUnit | .NET 2.0 | NUnit Console, Visual Studio Test Adapter, NUnit GUI, NUnitLite
.NET 4.0 | NUnit | .NET 4.0 | NUnit Console, Visual Studio Test Adapter, NUnit GUI, NUnitLite
.NET 4.5+ | NUnit | .NET 4.5 | NUnit Console, Visual Studio Test Adapter, NUnit GUI, NUnitLite
.NET SL 5.0 | NUnit.SL | SL 5.0 | NUnitLite for Silverlight
.NET Core | NUnit | PCL | NUnitLite for .NET Core
Xamarin Android | NUnit | PCL | NUnit Xamarin Runner

**Comment by blairjam** [comment]
It looks like this issue hasn't been looked at in a while, but I ran across a small issue while looking for nunit3-console to set up a script on our build server. The docs currently say that it is located at **packages\NUnit.3.X.X\tools**, when it is actually located at **packages\NUnit.ConsoleRunner.3.X.X\tools**.

This isn't a huge deal, but I had to do a little more searching than needed to find the actual location.

**Comment by rprouse** [comment]
Thanks @blairjam, I have updated the page.

**Comment by SeanKilleen** [comment]
🧹 Cleanup -- I am closing this issue because:

✅ The installation page appears to be updated per the thread
✅ This issue has not been updated for 3+ years.

Happy to reopen if I'm missing something; just leave a comment.

**Comment by ChrisMaddock** [comment]
This page still isn't great - it recommends installing the console as a solution-level NuGet package. Google tells me was those were deprecated back in NuGet v3 - 5 years ago!

I think realistically this whole "Getting Started" section needs a rework. So yeah, probably worth keeping this closed. 😞
