### ISSUE TITLE
'Question' -> LevelOfParallelism Attribute does not work as described in documentation 

### ISSUE THREAD

**Issue by mcopjan** [nunit/docs#320]
Hi,
referring to this documentation https://github.com/nunit/docs/wiki/LevelOfParallelism-Attribute I would like to ask a few questions. First of all it says this parameter is optional so if I don't specify that I am expecting I should be able to run maximum number of tests in parallel = 8 (number of logical CPU's on my machine)

![image](https://user-images.githubusercontent.com/20699180/64596717-52e3b080-d3ac-11e9-91ff-ad0066c75607.png)

Code to demonstrate current behavior :

`
[Parallelizable(ParallelScope.All)]
    public class ParallelTests :TestBase
    {

        [TestCaseSource(nameof(TestData))]
        public void Tests()
        {
            OpenBrowser(new Uri("https://www.google.com/"));
        }

        public static IEnumerable<TestCaseData> TestData ()
        {
            var numberOfTests = 10;
            for (int i = 1; i <= numberOfTests; i++)
            {
                yield return new TestCaseData() { TestName = $"Test{i}" };
            }

        }
    }
`
If i remove attribute [assembly: LevelOfParallelism(20)] from AssemblyInfo.cs my tests are working as expected -> 8 browser instances are opened in parallel

If I put [assembly: LevelOfParallelism(20)] back into AssemblyInfo.cs, I am able to run all 10 tests  from the TestCase Source in parallel. Now my question is **how is is possible that I am able to run more tests than number of my CPU's**?

Nunit 3.12.0
NunitLite 3.12.0
NUnitt3TestAdapter 3.13.0

**Comment by CharliePoole** [comment]
A program may start any number of parallel tasks. NUnit uses `LevelOfParallelism` to control the number of test threads it creates, which defaults to the number of CPUs.

Whether those tasks may __actually__ be able to make progress in parallel depends on what they are doing. For most unit tests, there is probably no advantage to increasing the number of threads beyond the default. However, if you were running the sort of functional tests that do a lot of waiting for input or for a remote call to return, then you could effectively run more test threads (provided they were not all waiting for the same resource, of course).

Your title indicates a problem in the docs. Can you clarify exactly which statements seem to be incorrect?

**Comment by mcopjan** [comment]
@CharliePoole Thanks for clarification. When I am reading through again, it makes sense now. I was under impression that It was not possible to specify LevelOfParallelism > number of CPU.
For our scenario we want to use much higher number of tests running in parallel as we have a big selenium grid with multiple chrome nodes and we want to decrease total tests run time.

**Comment by CharliePoole** [comment]
@nunit/framework-team How are updates to the docs "officially" handled these days. That is, are we doing reviewing changes beforehand or just editing and reviewing after the fact? I'd like to add a bit of explanation based on my answer to @mcopjan.

**Comment by ChrisMaddock** [comment]
I'm not too sure what we'd add here - the text seems fairly clear that LevelOfParallelism controls the number of threads. It might have been updated since this issue was filed?

@CharliePoole - anything that still springs to your mind to be added, or can we close this?

**Comment by CharliePoole** [comment]
Based on my unanswered question to the @nunit/framework-team back in September, I probably had something in mind at the time, but ten months have passed and I can't think now what it was. :confused: 

While a better explanation might be nice, that's true of many pages and in this case it's up to the @nunit/framework-team to decide where to put in their time.

**Comment by ChrisMaddock** [comment]
Thanks Charlie. I think we can close this, and any improvements can come separately
