### ISSUE TITLE
Not all test are showing in test Explore 

### ISSUE THREAD

**Issue by smarteez17** [nunit/docs#321]
Hi there I using NUnit3TestAdapter I have created  a test with 4 test cases 

  static ReportingPeriodInput[] FinancialYearIDAndStatusCases = new ReportingPeriodInput[]
        {
            new ReportingPeriodInput() { FinancialYearID = new Guid("0FEE4342-A248-4602-A95D-F6168DEDDD28"), Status ="Draft"},
            new ReportingPeriodInput() { FinancialYearID = new Guid("0FEE4342-A248-4602-A95D-F6168DEDDD28"), Status ="Published"},
            new ReportingPeriodInput() { FinancialYearID = new Guid("0EC52910-14BE-439C-81D0-FD542DF1F342"), Status ="Archived"},
            new ReportingPeriodInput() { FinancialYearID = new Guid("0EC52910-14BE-439C-81D0-FD542DF1F342"), Status ="T"}
        };

here my test 

[Test, TestCaseSource(typeof(ReportingPeriodTestCases), "FinancialYearIDAndStatusCases")]
        public void GivenFinancialYearIDAndStatusShouldReturnData(ReportingPeriodInput reportingPeriodInput)
        {
            //---------------Arrange---------------
            //---------------Act-------------------
            var sut = _ReportingPeriodRepository.GetByFinancialYearIDAndStatus(reportingPeriodInput);
            Console.WriteLine("No of Rows : " + sut.Count);
            //---------------Asset-----------------
            Assert.That(sut.Count, Is.GreaterThanOrEqualTo(1));
        }

But when I run my test in test explorer is only show one ( please see image )  but when I run it I can see a summary of all four tests 
![Capture 02](https://user-images.githubusercontent.com/35128168/65032841-36afb880-d944-11e9-96aa-486ad36ebdee.PNG)
 
![Capture 01](https://user-images.githubusercontent.com/35128168/65032698-eafd0f00-d943-11e9-9116-68fb8d651c8c.PNG)

My question how can i get it to on test explorer it show me all test ( show me all 4)

**Comment by CharliePoole** [comment]
You have created four tests, all with the same name...

```
GivenFinancialYearIdAndStatusShouldReturnData(Domain.Lookups.ReportingPeriodInput)
```

The test explorer treats this as a single test with four results. If you want it to be shown as four tests, you need to give each one a different name.

NUnit creates names for your tests using the arguments you pass in. But you are passing your own type as an argument and the name of that Type is used in the test name.

**Comment by smarteez17** [comment]
@CharliePoole  thanks for that is there a way to give it a different name with using test cases

**Comment by smarteez17** [comment]
public class ParameterizingUnitTests
{   
  [Test]
  [TestCaseSource(nameof(ParseTestsCases))]
  public void ParseTests(string input, string expected)
  {
    // Arrange
    var sut = new InputParser();
    // Act
    var result = sut.Parse(input);
    // Assert
    Assert.AreEqual(result, expected);
  }
  private static IEnumerable<TestCaseData> ParseTestsCases
  {
    get
    {
      yield return new TestCaseData("One Two Three Four", "Three").SetName("Valid input, Returns value");
      yield return new TestCaseData("One Two", null).SetName("Invalid input, returns null");
      yield return new TestCaseData(string.Empty, null).SetName("Empty string input, returns null");
      yield return new TestCaseData(null, null).SetName("Null input, returns null");
    }
  }


How would I used this example to pass my object through
