### ISSUE TITLE
SetUp may run async?

### ISSUE THREAD

**Issue by itsho** [nunit/docs#326]
Hi.

The [SetUp Attribute page](https://github.com/nunit/docs/wiki/SetUp-Attribute) says:
> SetUp methods may be async if running under .NET 4.0 or higher.

But I'm not sure I understand the meaning of the "May be" part in the sentence.
does it depend on me? can I control it?
if not - how can I avoid it from running async if I need it to run synchronously?

Thanks in advance.

**Comment by CharliePoole** [comment]
It simply means you may declare it using the async keyword if necessary. NUnit will only continue after it completes in any case.

**Comment by itsho** [comment]
if that's the case, I think it's better to write it explicitly - "... may be async if 'async' keyword is specified"

**Comment by CharliePoole** [comment]
Done! Thanks for the suggestion.

**Comment by itsho** [comment]
Thank you!
