### ISSUE TITLE
Nunit Suite

### ISSUE THREAD

**Issue by santhosh-James** [nunit/docs#329]
is there a way to have a suite kind of technique in nunit3? This will help to  do some actions after all tests are finished

**Comment by CharliePoole** [comment]
You'll have to explain a bit more what you mean. Technically, NUnit tests are entirely organized as a set of nested suites. There used to be a `SuiteAttribute` in NUnit V2, which allowed creating suites composed of arbitrary fixtures, without regard to the namespace hierarchy, but that's not available any longer.

**Comment by santhosh-James** [comment]
To elaborate this more, if I want to run ten fixtures parallel then is there a way to do some action after all these ten fixtures executed?  Basically a Teardown after all tests

**Comment by CharliePoole** [comment]
Sure... that's what a `SetUpFixture` is for.

1. If the fixtures are not already in the same namespace, put them in one. They can all be in one namespace or in different descendant namespaces of the common namespace. Don't have any other fixtures in that namespace.

2. Create a class in that common namespace and mark it as a `[SetUpFixture]`

3. Create methods in the fixture, marked as `[OneTimeSetUp]` and / or `[OneTimeTearDown]'. The one-time setup method will run before any of the fixtures start and the one-time teardown will run after they complete.

4. If you want the fixtures to run in parallel, mark each fixture `[Parallelizable]`. I suggest testing the one-time teardown without parallel execution first and then adding this.

**Comment by ChrisMaddock** [comment]
Closing this, as I think the questions answered. Feel free to comment further if not, the team will still get the notifications. 🙂
