### ISSUE TITLE
Any information on exit codes for cli ?

### ISSUE THREAD

**Issue by lGSMl** [nunit/docs#333]
I was trying to find an info about exit codes to nunit3 cli runner for my CI setup - but all I found was chunks of data here and there on Stackoverflow and google groups, which sometimes contradict and outdated. Can exit code info be added to cli docs section please? (or maybe I am blind and exit codes already there somewhere and you could point me to?)

**Comment by rprouse** [comment]
In the meantime, the console runner returns 0 if tests pass successfully. A positive return value is the number of tests that failed. A negative return value is one of the following;

```C#
        public static readonly int OK = 0;
        public static readonly int INVALID_ARG = -1;
        public static readonly int INVALID_ASSEMBLY = -2;
        //public static readonly int FIXTURE_NOT_FOUND = -3;    //No longer in use
        public static readonly int INVALID_TEST_FIXTURE = -4;
        //public static readonly int UNLOAD_ERROR = -5;         //No longer in use
        public static readonly int UNEXPECTED_ERROR = -100;
```
