### ISSUE TITLE
Unable to find ConstraintOperator documentation

### ISSUE THREAD

**Issue by qubitz** [nunit/docs#338]
Would love to create a custom [ConstraintOperator](https://github.com/nunit/nunit/blob/8c8cc6c8ff8b24002a94a9457c4a10a4db9f26d2/src/NUnitFramework/framework/Constraints/Operators/ConstraintOperator.cs), but am unable to find any documentation regarding this. Am I missing something simple or does it not exist? If no official documentation exists, does anyone have any helpful links (besides of course the source code).

**Comment by CharliePoole** [comment]
`ConstraintOperator` is pretty deep in NUnit's implementation. If you were to create one, you would then need to find some way to get NUnit to use it and that would be a new kind of customization, heretofore unenvisioned and therefore undocumented. :-)

I'm currently doing a rewrite of a ot of the constraint building code for a new framework I'm writing, and I have given this some thought. In general, the knowledge of which operators to use for each fluent constraint modifier (e.g. "Not") lives in ConstraintExpression.cs. So, when "Not" is encountered, a NotOperator is generated. 

To extend this right now, you could create an extension class that added some new method to `ConstraintExpression` and have that append your own operator to the operator stack. You would need to derive your custom operator from ConstraintOperator at a minimum. There are various kinds of `ConsrraintOperator`s possible... PrefixOperators, BinaryOperators, etc. Can you describe what you are trying to do?

**Comment by qubitz** [comment]
Thanks for the quick and detailed response. I stumbled upon `Has.Property` and subsequently the `PropertyExistsConstraint`. I have just created a custom constraint `Has.Method` (`MethodExistsConstraint`) and got jealous of `Has.Property`'s further ability to constrain the property using already existing constraints.

To be honest, I got a bit lost tracking down how that the expression system worked and was looking for an easier way of understanding.

**Comment by CharliePoole** [comment]
As often happens, you have chosen the most difficult sort of operator to model... assuming that `Has.Method` can either stand alone or be followed by other constraints. Essentially PropertyConstraint exhibits that behavior and could be a model.

Good luck!
