### ISSUE TITLE
OneTimeSetup doesn't get called

### ISSUE THREAD

**Issue by BrandonLegault** [nunit/docs#34]
Methods in a `TestFixture` marked with `[OneTimeSetup]` don't get called. I took the example directly from the documentation and Resharper greyed it out indicating that it has no references. As soon as I switched it to `[TestFixtureSetup]`, it wasn't greyed anymore and was called during my test.

![untitled](https://cloud.githubusercontent.com/assets/10144426/14255719/68f92d4e-fa63-11e5-90cc-43e0f45facf7.png)

**Comment by rprouse** [comment]
Are you using an older version of Resharper? Resharper 9 does not work with NUnit 3, you need Resharper 10. Unfortunately, the Resharper team did not upgrade their NUnit test runner for everyone, they want you to purchase the latest version to get the update.

**Comment by BrandonLegault** [comment]
Awesome. Yeah I'm using 9. I can run tests and stuff, just not with those new attributes.

**Comment by rprouse** [comment]
I would not recommend trying to run NUnit 3 tests with R# 9. None of the new NUnit 3 code gets executed, so you may find other issues, or even false positives. If you want to use NUnit 3 in Visual Studio, I would recommend using the NUnit 3 Test Adapter, or upgrading R#.

**Comment by BrandonLegault** [comment]
For completeness: I switched to the NUnit 3 Test Adapter and it works properly.
