### ISSUE TITLE
Docfx: Redirect links on wiki pages for all content

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#341]
As a way of ensuring the content has migrated as well.

**Comment by SeanKilleen** [comment]
It was decided as part of #355 that this could proceed. 👍

**Comment by SeanKilleen** [comment]
As of now, 99% of the wiki has been converted to point to the site.

**Comment by SeanKilleen** [comment]
Given that only #456 remains and we have a ticket to capture it, I think we can consider this complete.

**Comment by jnm2** [comment]
I'm not sure how they accomplished this, but https://github.com/microsoft/vstest/wiki returns a 302 redirect to https://github.com/microsoft/vstest.
