### ISSUE TITLE
Docfx: Build / Push to GitHub Pages

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#342]
Preferably GitHub actions so we can keep it all here and readily visible.

* Build using Docfx
* Push to a `gh-pages` branch.

**Comment by SeanKilleen** [comment]
The docs are now published to the `gh-pages` branch which is then served by GitHub pages.

The site currently lives at http://nunit.org/docs.

I'll be following up quickly with a robots.txt file to delay search engine crawling for a little bit.

I wasn't aware that creating a `gh-pages` branch would publish the site and that I wouldn't be able to simply disable github pages functionality. My best guess is it's because GitHub pages is enabled for the org with a CNAME record so gh-pages in projects within the org are automatically served?

Either way, I can't disable it and I don't think it's necessary to. The site will be live but not crawled once the follow up PR is complete.

/cc @CharliePoole @ChrisMaddock.

**Comment by ChrisMaddock** [comment]
Hey Sean - great news that it’s up and running! I get a 404 on that link, however?

**Comment by ChrisMaddock** [comment]
Ah, never mind, just seen #403. 😊
