### ISSUE TITLE
Docfx: Enable GitHub pages for docs repo

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#343]

**Comment by SeanKilleen** [comment]
This was done automatically apparently, as soon as I created the `gh-pages` branch during #342. Nothing like "launching by convention" 😆 

As a result, GitHub pages is enabled and the site is being served at https://nunit.org/docs

**Comment by CharliePoole** [comment]
Are you working with @rprouse on this? I had suggested that as he is responsible for the web site. I think we were all assuming you would create the static docs and he would decide when and how to incorporate them in the site. I get that this was unexpected but it ought to be his decision whether to leave it up or not.

**Comment by SeanKilleen** [comment]
@CharliePoole totally agree. Will create an issue specifically for him to make that call, and will figure out what we'd need to do to turn it off.

**Comment by SeanKilleen** [comment]
@CharliePoole actually I've decided that this isn't part if the plan so I'm just going to kill the branch and comment the github action file. We know it's possible now and it will be easy to adjust for launch.
