### ISSUE TITLE
Docfx: Add Subdomain docs.nunit.org

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#344]
Not necessary until build process, etc. is complete. Will ping on this ticket when it's coming up.

**Comment by ChrisMaddock** [comment]
Assigning this to @rprouse - as I think Rob's the account holder for our domains.

**Comment by rprouse** [comment]
What does the CNAME need to point to in DNS?

**Comment by SeanKilleen** [comment]
@rprouse TBD -- no action needed on this yet. This is a ways down the road yet (was going to hold off on tagging you until this came up further in the docs backlog).

**Comment by SeanKilleen** [comment]
This is ready to go -- @rprouse will point the subdomain to the github nameservers as soon as he's able, and the site should be live at that point.

As such, moving this to "in progress."

**Comment by CharliePoole** [comment]
FWIW I can no longer access the site at this point. Url `https://nunit.org/docs/index.html` goes to `docs.nunit.org`, which gives a "Server not found" error.

I think that you may have to wait for Rob in order to do this.

**Comment by SeanKilleen** [comment]
@CharliePoole yep, that's expected at this point. 👍

**Comment by SeanKilleen** [comment]
Rob has set up the DNS and we are now live.

Http://docs.nunit.org

Https will follow shortly once GitHub finishes issuing the certificate.
