### ISSUE TITLE
Docfx: Clean up navigation

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#348]
* [x] Ensure it makes sense
* [x] (#350) See if we can get top level links to be clickable and go to the first child link.

**Comment by ChrisMaddock** [comment]
I'd be interested in doing some restructuring here, to separate out the Engine, Console and Framework docs from just being under the single "NUnit" heading.

That could totally be post-launch though. I think the only pre-launch thing would be the duplicate section headers, which I presume is what your point above refers to. 🙂 

![image](https://user-images.githubusercontent.com/4837132/84571287-3be24c80-ad8a-11ea-80da-e8ec7c9b3742.png)

**Comment by CharliePoole** [comment]
Note that the Release Notes pages are already separate and simply point to the older common release notes if you scroll back far enough.

**Comment by SeanKilleen** [comment]
Thanks for the input on this, guys. I broke out https://github.com/nunit/docs/issues/416 to track separately as a post-launch item. Going to close this 👍
