### ISSUE TITLE
Ensure proper capitalization of "NUnit"

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#364]

**Comment by CharliePoole** [comment]
Except when quoting the names of files or commands where it's lower cased.

**Comment by CharliePoole** [comment]
Do we need some sort of style sheet for authors to use? Similar to a coding standard but for docs?

**Comment by SeanKilleen** [comment]
@CharliePoole I don't think so for now. I'll add an item to the backlog for future consideration.

**Comment by SeanKilleen** [comment]
Anything that I would want along the line of a guide, I'd be sure to automate. Beyond that, I want to ensure the impression is that we will help people get their PRs in. Big guides like that can become barriers.
