### ISSUE TITLE
how to specify results location from command prompt

### ISSUE THREAD

**Issue by VaibhavVS** [nunit/docs#37]
I need to specify the results file location while running the NUnit test from command prompt.
Which command parameter can I specify for the same?

**Comment by CharliePoole** [comment]
--work and/or --result

**Comment by VaibhavVS** [comment]
Thanks a ton Charlie!!! It has worked gr8!! I was trying to figure it out since 2 hours.. Really thank you.. Its already there in the wiki docs, but I was in confusion that it will only result to xml output.
