### ISSUE TITLE
Add documentation for template-based naming of tests

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#38]
This is pretty well described in one of our specifications. That page needs to be copied somewhere in the docs and brought up to date. We should link to it from TestCase and TestCaseData.

**Comment by ChrisMaddock** [comment]
I've just added the new page - @CharliePoole, would you mind reviewing what I've done?

The new page is: https://github.com/nunit/docs/wiki/Template-Based-Test-Naming

It is linked from TestCaseAttribute and TestCaseData. I just took the second half from [the spec](https://github.com/nunit/docs/wiki/Generation-of-Test-Names-Spec) page - that was the bit that seemed relevant from a documentation point of view. 

Will close this issue after review.

**Comment by CharliePoole** [comment]
Nice! Some specific comments here:

* Although it's covered further down, I think you need something in the first lines that indicates that there is a default naming convention and that use of this facility is optional.

* The description of how we generate the fullname is incorrect. There is no template for the fullname. Rather we simply append the test case name to the class name, separated by a '.' character. If we allowed the fullname and name to vary independently, a number of things would break internally. 😢 

Otherwise, looks great to me.

**Comment by ChrisMaddock** [comment]
Thanks @CharliePoole. 

I've edited the first paragraph. 

 * Can you clarify where the error is with fullname's? I'm assuming you mean that fullname for method isn't always "Equivalent to {n}.{c}.{m} or {C}.{m}"?
 * Is the "Standard Name Formats" still accurate, re: truncating the arguments after 40 characters? I have vague memories that we considered moving the truncating functionality to the runners - but I can't remember if anything ever came of that, or find the relevant issues.

**Comment by CharliePoole** [comment]
Generation fo the fullname is __not__ currently template-based, as is hinted by your example of a template. By default, it __looks__ as if it is generated by the template you list but it really isn't. Where you see the difference is if you change the test name, then the fullname changes as well. There is no way the user can modify how the fullname is created.

**Comment by ChrisMaddock** [comment]
Thanks Charlie - I made the change. Sorry it took a while, this was the last thing I did before going on holiday!
