### ISSUE TITLE
Error on Breaking changes

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#4]
Looking at the Breaking changes list again reminded me of [this issue](https://github.com/nunit/nunit/issues/1171). Is it right that the replacement for Assert.IsNotNullOrEmpty should be Is.Not.Null.Or.Not.Empty? (With the extra 'Not')

**Comment by CharliePoole** [comment]
Actually, Is.Not.Null.And.Not.Empty.

Fixed.

**Comment by ChrisMaddock** [comment]
Whoops - thanks!
