### ISSUE TITLE
Document custom attributes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#40]
This page needs update: https://github.com/nunit/docs/wiki/Custom-Attributes

**Comment by ricardovoigt** [comment]
How to run tests command line with attributes in test class?

**Comment by rprouse** [comment]
@ricardovoigt I am not sure what you are asking or if this is an appropriate issue for your question. These are the issues for problems with the documentation.

**Comment by 132u** [comment]
hello! I have created few custom attributes which are derived from CategoryAttribute and marked my testfixture class by few categories, but test explorer show me that tests are located only in one category althought it's in few categories. Moreover  in reshaper unit test explorer window  tests are showed in uncategorized section. Could you please explain how fix it, I want to mark one class tests by few custom categories and see this test in different categories in  test explorer window and in reshaper  unit test explorer window

**Comment by Sebazzz** [comment]
> but test explorer show me that tests are located only in one category(it always takes first category) althought it's in few categories.
I believe the Visual Studio Test Explorer doesn't support the same test in multiple categories.

> Moreover in reshaper unit test explorer window tests are showed in uncategorized section.
I know ReSharper uses its own method of detecting NUnit tests, so that may explain why the ReSharper runner doesn't show your tests correctly.

**Comment by CharliePoole** [comment]
@132u This is not a documentation issue and it's __definitely__ not this issue, which is about updating a particular page in our docs. It sounds like you have a prolem with your own code, or with nunit, or with one of the two adapters. If so, you should file a new issue in the right place.

To get you started, here is some info to check out...

The adapter should display multiple categories. It has to translate categories as traits for use by VS. To do that it has to receive the categories in hte first place. Try to answer these questions (for yourself) before filing an issue...

1. Is my custom attribute actually creating a category? That can be discovered by using the nunit3-console runner and looking at the XML. You can also try running tests, selected by your category. If this doesn't work, then either you are not creating a custom category correctly or nunit is not detecting it correctly. You can ask for help on the nunit-discuss list or file a question in the nunit repository.

2. Is the adapter properly handling the category? If NUnit creates a category, it should appear in the test-window when you group by traits. Ask for help on this on the nunit-discuss list or by filing a question in the nunit-vs-adapter or nunit3-vs-adapter repository, whichever one you are using. (This documentation repo is for NUnit 3, so that's probably what you are using, but I wanted to cover all the bases in this answer)

**Comment by CharliePoole** [comment]
I completely revised the main page and added pages for each interface. I'm sure I missed stuff, so please review.

**Comment by ChrisMaddock** [comment]
Looks good to me, that's really helpful to have written up. 👍
