### ISSUE TITLE
Test ID in the xml report

### ISSUE THREAD

**Issue by alexlazarciuc** [nunit/docs#404]
Hello,

Curiosity ... How the Nunit XML know to generate the same test ID within the xml report although I execute the tests on two different machines?

I am building some test reports and want to start using the IDs from the report and just want to be sure that whenever we execute the tests on diff machines the id won't change for the test. Tested on a jenkins agent and my local and the ID stays the same, but how is that so? :)

Thanks in advance,
Alex

**Comment by ChrisMaddock** [comment]
Hi Alex,

To be short - it doesn't! The fact it might return the same ID twice in a row at the moment is just an implementation detail, and not something that should be relied on. The only guarantee of uniqueness for a test ID is within a single test run. 

Introducing a deterministic Test ID is something on the radar, and there's a couple of open issues: https://github.com/nunit/nunit/issues/2541 https://github.com/nunit/nunit/issues/1336. Pull requests welcome, of course! 😉 

What is it you're actually looking to do? Maybe there's another solution.

**Comment by alexlazarciuc** [comment]
Hi Chris,

Thanks for the quick reply :)

I am integrating Test Rail api with our Specflow tests. 

The idea is to fetch somehow the test cases with the ones generated in the xml and the ones in test rail. I could do it via the title but would like to be somehow flexible in case QAs will change the title in test rail, I still want to match that test with the executed one by Nunit so I was thinking that an ID will solve my issue. I think I will rely on the title for timebeeing. Unless you have some feedback for me on whats the best approach?

Thanks,
Alex

**Comment by ChrisMaddock** [comment]
I'm not familiar with Test Rail, but what you're saying sounds roughly sensible to me.

The other option you might want to consider is to role your own persistent IDs, by creating a custom PropertyAttribute applied to every test and setting your own ID. It requires a little more work for TestCaseSource's etc - but far from impossible.

I'll close this issue now - but feel free to keep replying if there's more to ask - the team will still get the notifications. 🙂

**Comment by alexlazarciuc** [comment]
Hi @ChrisMaddock 
I know it is a closed issue, but just a quick one, would you know how Jenkins plugin knows to keep track of the tests, it is using the same id or test name from the report?
Thanks,
Alex

**Comment by ChrisMaddock** [comment]
To be blunt, I’m afraid I don’t! Sorry! 😅
