### ISSUE TITLE
Consider restructuring to break out docs from the single NUnit Heading

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#416]
Per @ChrisMaddock as a comment on https://github.com/nunit/docs/issues/348: 

I'd be interested in doing some restructuring here, to separate out the Engine, Console and Framework docs from just being under the single "NUnit" heading.

That could totally be post-launch though. I think the only pre-launch thing would be the duplicate section headers, which I presume is what your point above refers to. 🙂 

![image](https://user-images.githubusercontent.com/4837132/84571287-3be24c80-ad8a-11ea-80da-e8ec7c9b3742.png)

_Originally posted by @ChrisMaddock in https://github.com/nunit/docs/issues/348#issuecomment-643630808_

**Comment by ChrisMaddock** [comment]
I think this is a duplicate of #395, no? 🙂

**Comment by SeanKilleen** [comment]
Ah! I believe you're right. 😄 Closing.
