### ISSUE TITLE
Determine the best way to move forward on legacy docs publishing

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#441]
cc @jnm2 as FYI since he raised the original issue.
cc @rprouse as I believe it's his call ultimately.

## Background

In https://github.com/nunit/nunit.github.io/issues/79, @jnm2 realized a docs conflict caused the legacy docs to become unavailable.

## Problem 

This indeed appears to be a breaking change because GitHub's DNS and hosting is having trouble hosting both `nunit.org/docs/*` and `docs.nunit.org` due to the overlap of `docs` at that specific place in the hierarchy.

This is unfortunate; GitHub support confirmed that this should have been fine.

We resolved the symptom with #439 but now need to figure out the best way to proceed.

## Options

Rob is away at the moment but I can see a few courses of action here:

1. I could rename the docs repository to something like `thedocs` (to ensure it doesn't conflict with other similar terms), in which case GitHub would handle all the repo-level stuff for us and nothing should be an issue. I am not sure that it will solve the problem if GitHub's helpful handling of redirects keeps the issue in place.
2. I could do a quick PR capturing the old documentation and moving it to docfx as-is -- e.g. telling docfx to copy the raw html files and not modify them in any way. I believe the result will be that it looks as it does now.
3. Move the docs from the nunit site to a legacy, e.g. Charlie's site as he mentions below, and stop hosting them on nunit.org altogether (with redirect links, etc. maybe?) 
3. Something I haven't thought of?

## My suggestion

I think option 2, hosting the legacy docs in the new docs site, makes the most sense. However, in that scenario, I assume that the documentation is fully archived and does not need to be touched (I am using the Jekyll HTML output, not the jekyll inputs).

I will prepare a PR so that we are ready to go if Rob agrees with option # 2.

**Comment by CharliePoole** [comment]
If it's of any use, at least on a temporary basis, the entire legacy docs are available on the NUnitSoftwarer site: http://www.nunitsoftware.com/nunitv2/index.php?p=documentation

@SeanKilleen Others know this, but for the "new guy"... the team decided to no longer maintain NUnit V2 a while back. I disagreed so i created the legacy project and site. That's open source for you! :smiley_cat:

**Comment by rprouse** [comment]
Could we move the legacy docs to a different folder under the site? To be honest, I wouldn't mind breaking existing links to the legacy docs. I hate googling NUnit and getting links to the version 2.5 docs because they still have the most incoming links.

**Comment by CharliePoole** [comment]
@rprouse IIRC the nunit.org copy of the legacy docs was generated from the original PHP as static html. Is that right? If so, we could move it anywhere so long as the internal links are all relative. Easiest way to find out is probably to just copy it somewhere and try it out.

**Comment by rprouse** [comment]
Yes, they are generated HTML from the original PHP, so they will be easy to move. There are so many of them that the build time for the NUnit site is very long. That is why I am reluctant to move them into the new docs which I hope will be updated more frequently. I'd rather have the long build on the main site which gets updated infrequently by a handful of people than in the new docs which will have more contributors.

We also have a JavaScript file that redirects the old incoming links to the new generated page, so we might be able to update it to point to a new location.

**Comment by SeanKilleen** [comment]
@rprouse 

> so they will be easy to move

Yep -- I already have a PR ready for this: #442 

> There are so many of them that the build time for the NUnit site is very long

I only copied the outputted HTML in this case, so the build time remains very small as docfx is only copying files from folder to folder.

> Could we move the legacy docs to a different folder under the site? To be honest, I wouldn't mind breaking existing links to the legacy docs

I'm generally not a fan of breaking links but I understand the thought here and I love the idea of moving them to a `legacy-docs` folder within `nunit.org` (or moving them to the `nunit2` site if @CharliePoole and the core team agree that's ok; it makes sense to me.) 

----

@rprouse I'm happy to submit PRs for whatever we decide in order to facilitate it.

**Comment by ChrisMaddock** [comment]
I’m not too keen on breaking all the links if avoidable. Isn’t there a way we can get google to point to the latest version by default? I think we were limited with that before of a GitHub wiki, but it should be easier with a proper site, right?

**Comment by SeanKilleen** [comment]
## Option 1

Host legacy docs in the `nunit/docs` repo & site, keeping the links & paths in-tact. (no need to update design / modernize it as long as content stays the same and links continue to work.)

**Comment by SeanKilleen** [comment]
## Option 2

Change the name of `nunit/docs` repository to something like `nunit/documentation-site`. My understanding is that this will remove the conflict. Existing docs will then be able to live at `nunit.org/docs/*` without issue and our new site should be served fine as well.

**Comment by SeanKilleen** [comment]
## Option 3

Move the legacy documentation for nUnit 2.x to Charlie Poole's nunit 2 site, since he is currently supporting v2.x and my understanding is that the NUnit org is no longer doing so. (this may require a longer conversation if there's an official decision that needs to be made around it.)

**Comment by SeanKilleen** [comment]
Hey all! Wanted to get some clarity on our direction here. I've posted some the above that I'm aware of. Please vote :+1: or :-1: on an option, and/or add an additional option if you think one is viable.

@CharliePoole @rprouse @ChrisMaddock @jnm2 @OsirisTerje @mikkelbu

**Comment by jnm2** [comment]
To clarify my 👎 on option 3: it sounds fine (if Charlie wants to take that on) so long as links don't break.

**Comment by CharliePoole** [comment]
@SeanKilleen Option 3 doesn't quite make sense as written because there's nothing to move. The docs are already there. In fact, there are more doc versions there than on the NUnit site... versions 2.6.5 through 2.7.1. 

They are also in an entirely different format even though they present the same information and almost the same tml. What I have is the version of the docs from our pre-github site, based on php. I used a php routine to generate the static html and passed it to Rob, who modified it a bit to fit on our github site.

So Option 3, such as it is, boils down to dropping the legacy docs from nunit.org. As you say, there's a lot to discuss there. I gave it a thumbs down only for that reason. With enough discussion it could become a thumbs up.

It seems to me there's an Option 4: move the legacy docs to a different URL under NUnit.org and break the links like Rob says. I understand this goes against the grain for you as a web developer, but it's archived documentation for software we no longer support. I'd favor this if everyone feels the same way about the links.

**Comment by CharliePoole** [comment]
@jnm2 Re your comment...

> To clarify my -1 on option 3: it sounds fine (if Charlie wants to take that on) so long as links don't break.

As noted, I already have the docs for NUnit V2 on my site. I think the decisions around NUnit V2 may have been before you joined the Core Team and, of course, @SeanKilleen wasn't party to them so I'd like to sum it up for both of you...

1. The project team decided that NUnit V2 would no longer be supported at all.
2. I disagreed very strongly with that decision, so strongly that...
3. I forked NUnit V2 and now maintain it outside the project.
4. Having once forked it, I needed to maintain the docs and so I do.

So if you had the impression that a decision was made to "transfer" the V2 software to me, that's not so. The team decision was to drop it cold, a decision with which I disagreed so strongly that I forked it. My continuing maintenance of the software and the docs is a responsibility I have to my users, it's not in any way being done "for" the NUnit Project.

So here's a question... If the team doesn't care about NUnit V2, then why care about the docs? Should the decision to drop support be revisited? Should the decision to maintain the docs be revisited?

**Comment by SeanKilleen** [comment]
FYI @mikkelbu @jnm2 @ChrisMaddock @CharliePoole I have updated Option 3 to reflect Charlie's comments (move docs to charlie's fork --> drop docs from nunit.org nd let them live only in Charlie's existing fork). Letting you know in case this affects your voting and you'd like to change it.

@CharliePoole, thanks for clarifying the history there.

In light of that point, I most strongly favor option 3 -- the complete removal from nunit.org of `v2.x` docs. This would align the nunit.org web site with the team's decision to stop support for nunit 2 altogether. We could place an external link to Charlie's fork for V2 documentation.

**Comment by SeanKilleen** [comment]
## Option 4

Move the docs to a different folder within the `nunit.org` domain, e.g. `nunit.org/legacy-docs`. This would resolve the URL conflict.

⚠️ This would break links
⚠️ This would continue to duplicate the content in Charlie's V2 fork.

**Comment by rprouse** [comment]
Option 3 or 4 breaks existing links, but as I said I am okay with that since they are legacy docs. Duplicating the docs on NUnit.org and on Charlie's site seems redundant to me. I prefer one canonical version and I think it should be Charlie's site since he already has a more complete copy there.

We might also be able to 'fix' the links with the JavaScript we added when we migrated to Github hosting.

**Comment by SeanKilleen** [comment]
A few observations here:

* Option 1 has the most votes and no down votes
* Option 1 is a non-destructive action
* Option 1 allows us to table the docs removal discussion

Given that, unless there are strong objections, I'll proceed with option 1 and setup discussion to revisit the removal question later.
