### ISSUE TITLE
NUnit 3.0 Test Adapter not available in Nuget

### ISSUE THREAD

**Issue by edoua** [nunit/docs#45]
Hello,

My team is using NUnit as our unit-testing framework.

We are using Visual Studio Team Services as our Build and CI server.
In this set up we do not control the machine where the build agents are running.

Without the NUnit 3.0 Test Adapter Nuget Package we cannot run our NUnit test as part of our build as we cannot install the visual studio runner extension on the build agent machine.

We would need a nuget package like it is possible with xUnit -> http://xunit.github.io/docs/getting-test-results-in-vsts.html

Why was the NUnit 3 Test Adapter pulled from Nuget? as seen on the page https://github.com/nunit/docs/wiki/Adapter-Installation -> 

> (As 12/11/2015, "NUnit 3.0 Test Adapter" is not found in Nuget. It is only available as Extension)

Is there any roadmap when it will be available again?

Any other workaround you would know off?

Thanks

**Comment by CharliePoole** [comment]
The wiki comment is obsolete.  Have you tried to find it? Be sure to include pre-releases in your search.

**Comment by rprouse** [comment]
You can find it here
https://www.nuget.org/packages/NUnit3TestAdapter/3.0.9-ctp-9

Or as Charlie says, check the pre-release checkbox in Visual Studio.

On 13 April 2016 at 08:23, CharliePoole <notifications@github.com> wrote:

> The wiki comment is obsolete. Have you tried to find it? Be sure to
> include pre-releases in your search.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nunit/docs/issues/45#issuecomment-209403328>
>



-- 

Rob Prouse



I welcome VSRE emails. Learn more at http://vsre.info/

**Comment by edoua** [comment]
Thank you very much for the swift answer.
I should have thought about the pre-release state.

Would it make sense to change the confusing wiki?

**Comment by CharliePoole** [comment]
Fixing the wiki is what this issue is for. ;-)

**Comment by CharliePoole** [comment]
Updated the page
