### ISSUE TITLE
Missing Page: Quick Start Source Code

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#456]
https://github.com/nunit/docs/wiki/Quick-Start-Source-Code

* [ ] Convert Page
* [ ] Add to TOC
* [ ] Redirect old wiki page

**Comment by SeanKilleen** [comment]
@jnm2 I believe you authored this page. It's from 2017 and is not linked to anything. 

Would you prefer I:

1. Convert it (and if so, where in the TOC do you think it should go?) 
2. Delete the wiki page as it's not longer needed
3. Leave on the wiki only

My preference would be options 1 or 2 as I do not want the wiki to be a reference anymore.

**Comment by jnm2** [comment]
@SeanKilleen I did some linting but the page didn't originate with me: https://github.com/nunit/docs/wiki/Quick-Start-Source-Code/_history

**Comment by jnm2** [comment]
@SeanKilleen Looks like this is the earliest version I can find: https://docs.nunit.org/2.2/quickStart.html

**Comment by jnm2** [comment]
Looking at the history of _Sidebar.md, it appears to have never been linked from the sidebar. I think that means it's unlikely people will have seen it. It would likely go in https://docs.nunit.org/articles/nunit/getting-started/samples.html if we converted it.

@CharliePoole Since you added it to the wiki, do you have a preference?

**Comment by CharliePoole** [comment]
The example dates from before anyone on the project was here, including me. (That means it was prior to 2002)

Our docs had a long history before the wiki - they were hosted in three or four different places IIRC. I simply took the existing example, which was probably a text file, and converted it to markdown when we went to NUnit 3.

I'm sure it was in the sidebar index for NUnit at one time. Note that even though the names of normal pages are unique across the entire wiki, those special pages that start with an underscore exist in multiple copies in the file hierarchy. That's how we were able to have different sidebar menus for each project.

The QuickStart sample is basically for the framework project, so my guess is that it would have been listed in `docs/NUnit/_Sidebar.md`. It's up to the team to decide if it's still useful.

**Comment by jnm2** [comment]
When I quickly checked multiple _Sidebar.md histories, including `docs/NUnit/_SideBar.md`, I didn't see the quickstart come up. I think this means we'd be making it available as part of the NUnit 3 documentation for the first time.

**Comment by CharliePoole** [comment]
@jnm2 I see one of your links actually points to the legacy docs. That would of course be from before the introduction of the wiki. Our website started as static html, went through a web redesign, got rewritten later in php, got another redesign, got regenerated from php to static html and was imported to github pages. Hosting was in three or four places over the course of it's life. 

The particular example was written for NUnit V1 or V2 and was there when I arrived in 2002.

**Comment by CharliePoole** [comment]
Not everything was always in a menu. It may have been linked from the
getting started page. But it may also be that we decided to let it go since
it's fairly obsolete. Sorry I can't remember more.

**Comment by jnm2** [comment]
Okay, thanks. I'm in favor of deleting it because we want to point people to constraint-based assertions.

**Comment by SeanKilleen** [comment]
@CharliePoole @jnm2 thanks for following up on this! I agree that it's basic enough and.hasnt been linked for a while so I'm going to delete it. I have some ideas for this sort of content in the future.

**Comment by SeanKilleen** [comment]
This wiki page has been deleted.
