### ISSUE TITLE
Test not run in Visual Studio 2015

### ISSUE THREAD

**Issue by alain-dupont-gebocermex** [nunit/docs#46]
this test case not never called and gives error.

        // Test with an expected result
        [Test(ExpectedResult = 4)]
        public int TestAdd()
        {
            return 2 + 2;
        }

Message:
...
Test Outcome:	Failed
Test Duration:	0:00:00.0000001

Result Message:	Test method has non-void return type, but no result is expected

**Comment by CharliePoole** [comment]
Please file issues against the repo for the software that shows the problem. For example nunit, nunit-vs-adapter, nunit3-vs-adapter. This one is for problems in the documentation.

The error you have suggests a mismatch between the version of the nunit framework you are using and whatever software is running the tests.
