### ISSUE TITLE
Add Google TXT Record to DNS for docs.nunit.org

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#464]
E-mailed Rob and asked him to do this. Adding this so I don't forget.

**Comment by rprouse** [comment]
@SeanKilleen It looks like I forgot about this and I don't see anything in my emails. Is there still something that needs to be done? Feel free to DM me on Slack if anything sensitive needs to be shared.

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: Closing this as it's not required and I can revisit it anytime it is in the future.
