### ISSUE TITLE
Reduce linting noise

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/docs#466]
The markdown linting produce a lot of noise in the form of telling me which files are Ok, that they have succeeded.  That alone accounts to more than 700 lines of unneeded lines.  It makes it hard to find the single line I need with whatever error I did to the nice markdown.

Is there any way of getting the linter to **not** write out that a file has succeeded ?

**Comment by SeanKilleen** [comment]
@OsirisTerje I noticed this too on your last PR.

I'll see if I can do a PR against super linter, otherwise I'll switch us to a different process.

**Comment by SeanKilleen** [comment]
@OsirisTerje this is fixed by #469. 

We now use markdownlint-cli which is less generic, much much faster, and only outputs errors. 👍
