### ISSUE TITLE
Incorrect SetUp and SetUpFixture attribute names spelling in the wiki docs

### ISSUE THREAD

**Issue by tautvisv** [nunit/docs#47]
The [wiki attributes list](https://github.com/nunit/docs/wiki/Attributes) lists `SetUp` and `SetUpFixture` attributes as `Setup` and `SetupFixture` - the *u* being lowercase. It's actually uppercase in the code.

**Comment by rprouse** [comment]
Thanks, I fixed both of those and TearDown.
