### ISSUE TITLE
Documentation: Target wrong in Navigation Frame (Attributes/TestCaseSource)

### ISSUE THREAD

**Issue by resuem** [nunit/docs#470]
Go To: https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html 
Navigation on the left (the Attribute List) shows TestCaseSource (below TestCase)
Expected Target of the link:
https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html
Actual Target of the link:
https://docs.nunit.org/articles/nunit/writing-tests/attributes/platform.html

The target of the attributes list from this page is correct: https://docs.nunit.org/articles/nunit/writing-tests/attributes.html

![image](https://user-images.githubusercontent.com/64212485/87943687-adef3500-ca9e-11ea-9597-2077f962a300.png)

**Comment by SeanKilleen** [comment]
@resuem thank you for submitting this! I'll have a PR out for it shortly.

**Comment by SeanKilleen** [comment]
@resuem this is now live; you may have to clear your cache to see the update.
