### ISSUE TITLE
Legacy docs header has four links that 404

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#483]
A Google search took me to https://docs.nunit.org/2.2.7/fixtureTeardown.html, but I wanted the 3.x docs. I clicked "Documentation" in the header which took me to https://docs.nunit.org/documentation/ which 404s. News, download, and contact links have the same issue in that header.

**Comment by SeanKilleen** [comment]
@jnm2 thanks for reporting! I'll get it fixed  up.

**Comment by jnm2** [comment]
Thanks!
