### ISSUE TITLE
Wrong direct link from https://github.com/nunit/docs/wiki/TestCaseSource-Attribute

### ISSUE THREAD

**Issue by mikkelbu** [nunit/docs#486]
It links to https://docs.nunit.org/articles/nunit/writing-tests/attributes/platform.html, but the correct link is https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html.

We should go through all direct links from the wiki and see if they are correct.

**Comment by CharliePoole** [comment]
This looks like #470, which was just fixed. Did you clear your cache?

**Comment by SeanKilleen** [comment]
@mikkelbu thanks for this! Will fix asap.

@CharliePoole We updated the docs site but the error still exists on the wiki redirect. 

FYI @mikkelbu I'm working on a way to automate those link checks. I think we'll find this is a one-off issue though.

**Comment by SeanKilleen** [comment]
Wiki Fixed to bring it in line with #470.

**Comment by mikkelbu** [comment]
I just skimmed all the direct links and only found the following problem, which I'll correct on the wiki
* https://github.com/nunit/docs/wiki/DefaultFloatingPointTolerance-Attribute has no direct link - it just says `Direct link: <red>` in the source, it should refer to https://docs.nunit.org/articles/nunit/writing-tests/attributes/defaultfloatingpointtolerance.html

**Comment by ChrisMaddock** [comment]
just FYI, same on the console release notes page. Fixed by hand. 😊
