### ISSUE TITLE
Hide legacy docs in file hireachy

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#492]
Making the recent change to the engine release notes, I got a little lost in looking for the latest version of the docs. My first thought when I opened the `/docs/` folder was to look for the version I want to edit for - I'm not sure it would be too clear to a new contributor that everything for version 3.x is under `articles` instead.

Is there a way we could push all those old docs down under `/legacy/` or something, and put in a redirect so they end up in the right place?

**Comment by SeanKilleen** [comment]
@ChrisMaddock I like this idea. Goal at the time was to not break any links but I think this is a good outcome to pursue.

That said, I'm not sure how we'd accomplish it. With a static site, the files need to be there to be served even if they just redirect, so I think we'd still have this structure. Maybe I'm missing an approach though.

**Comment by ChrisMaddock** [comment]
I had a quick Google - I think it should be possible using src/dst functionality?

https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html#41-array-format

I'm all out of time for today, but don't mind trying to have a look at this soon. 🙂

**Comment by SeanKilleen** [comment]
@ChrisMaddock ahhh, I see. I can absolutely take care of this; thanks for jogging my memory on the docfx pieces!
