### ISSUE TITLE
Using Test and TestCaseSource attributes together

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#5]
On [this page](https://github.com/nunit/docs/wiki/TestCaseData), both the `Test` and `TestCaseSource` attributes are specified. I normally only specify `TestCaseSource` on it's own, as it's done on [this](https://github.com/nunit/docs/wiki/TestCaseSource-Attribute) page.

Is one way considered 'better practice' than the other, or is the test attribute simply redundant in the first case? Or was it historically required? I checked it out locally and it doesn't appear to make any difference to what's actually run - but seeing the additional attribute at first did make me want to check my tests were actually running!

**Comment by CharliePoole** [comment]
It's a matter of style. When `TestCaseSource` was first introduce, only methods marked with either `Test` or `TestCase` were treated as tests, so the extra `Test` attribute was required. Nowadays, recognize it without `Test`.

The tests of NUnit itself are not standardized, but use a mix of the styles. This is for a very good reason: it's possible that one style or the other may produce a bug some day.

It's also possible that some third-party runners will only recognize tests with the `Test` attribute, so we try to keep it working when used only as a marker and not to generate an extra test case.

Probably, the docs for `TestCaseSource` should indicate that the attribute is sufficient by itself to mark a test. We do that for `TestCase` already.

**Comment by ChrisMaddock** [comment]
Great - thanks for the explanation Charlie. I can summarise this and add it in - I think the explanation would help avoid confusion.

**Comment by CharliePoole** [comment]
Go for it!

**Comment by ChrisMaddock** [comment]
Whoops, this slipped my mind. @CharliePoole - have added a note to TestCaseSource, please feel free to check I haven't twisted your words!

https://github.com/nunit/docs/wiki/TestCaseSource-Attribute

**Comment by CharliePoole** [comment]
@ChrisMaddock You represented my words real well. However, I intended the historical perspective for you, not for the docs.

In our old NUnit docs, we always described the history of everything, even down to what version of NUnit a feature was introduced in. With 3.0, I felt we should break with that and just tell people how things now work. I think that's what they want to know. I will post a question about this for all of us to ponder however.

For TestCaseSource, I just thought you needed something like the first sentence in the TestCase attribute docs, talking about the "dual purpose" of the attribute. I don't think we need the note.

**Comment by ChrisMaddock** [comment]
@CharliePoole Ah, ok. I've switched it for something more succinct, as in TestCaseAttribute.

**Comment by CharliePoole** [comment]
@ChrisMaddock  Looks good, thanks.
