### ISSUE TITLE
Link to code samples

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#50]
I was just coming along to fill in the empty links that were previously on the docs homepage, but seen they've been removed.

As the samples already exist, I think they may get more visibility if they're linked from the docs. Previously they were on the [main home page](https://github.com/nunit/docs/wiki). Is this an appropriate place for them? We could either have each repo linked in the sidebar, or a link to a code samples homepage?

Regardless of what people think about the above, I think they should definitely (also) feature in the sidebar of the NUnit Documentation section, as various links to this bypass the wiki homepage. I'd think a link from this section would be most visible to the new user's who would find samples helpful.

Thoughts?

**Comment by CharliePoole** [comment]
The link seems better to me in the NUnit Documentation section. To avoid clutter, I would say just one link to a Samples page, which can list samples by language.

In case you didn't know, you can edit pages in subdirectories online, but you can't create them. And you can't edit any of the  _Sidebar.md files except for the root online. You need to clone and at least do that much locally.

**Comment by CharliePoole** [comment]
I created the empty page and menu entry, just in case. :-)

**Comment by ChrisMaddock** [comment]
Thanks @CharliePoole - done! Please feel free to reword as you see fit!

https://github.com/nunit/docs/wiki/Samples
