### ISSUE TITLE
The document cannot be viewed

### ISSUE THREAD

**Issue by ananck** [nunit/docs#505]
http://docs.nunit.org/

**Comment by mikkelbu** [comment]
@ananck If I click on your link, then I'm redirected to https://docs.nunit.org/ and I end up on the documentation site. What happens on your machine?
![Uploading image.png…]()

**Comment by SeanKilleen** [comment]
@ananck similar for me:

> ![2020-08-03_DocsHttpsRedirect](https://user-images.githubusercontent.com/2148318/89228875-685a5e00-d5ae-11ea-9739-0a8e2f86b3fd.gif)

Let me know if we're missing anything. Perhaps it was a transient issue?

**Comment by SeanKilleen** [comment]
Given that we have not been able to recreate this, going ahead and closing.

@ananck, if you're still having issues anytime in the future, feel free to open another issue. Thanks!
