### ISSUE TITLE
Document Use of .runsettings file for the NUnit3 Adapter

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#51]
We probably need to keep the registry settings docs, marked for those using older versions.

**Comment by SeanKilleen** [comment]
🧹 Housekeeping -- closing this older issue as I believe the `.runsettings` configuration is now covered here: https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#vs-test-runsettings-configuration

Please let me know if this isn't the case, and I'll reopen.
