### ISSUE TITLE
Custom-Asserts.md mentions IAsserter, which is deprecated

### ISSUE THREAD

**Issue by dellch** [nunit/docs#512]
The documentation page, https://github.com/nunit/docs/blob/master/docs/articles/nunit/extending-nunit/Custom-Asserts.md, mentions using `IAsserter` interface, but, I believe that has been deprecated.  

Should this documentation page still exist?

**Comment by CharliePoole** [comment]
Not deprecated. Rather never implemented. :smiley:

@nunit/framework-team 
At the point when I left the team I had been curating a list of unimplemented specifications. I cleaned up what I could but there were a few like this one where I didn't know whether the team wanted to keep it.

I think that this and any others like it should be deleted if they are not wanted or an issue created out of them if they are ideas the team wants to consider. They are definitely not part of the documentation.

BTW, this particular one was a proposal at the time of NUnit 2.4 and can be found in those docs as well, although not indexed. That leads me to suspect that this was an orphaned page, which was indexed when we converted to docFx.

**Comment by gaffo** [comment]
AT this point delete it, I wasted about 30 minutes before finding this issue trying to figure out where IAsserter was

**Comment by SeanKilleen** [comment]
Finally coming up for air a little bit and I'm going to remove this from the docs because the docs should reflect the current state of things. It will be removed in a few minutes. Thank you @dellch for reporting and @gaffo for bumping, as well as @CharliePoole for adding extra context.
