### ISSUE TITLE
Base class SetUp method is not called if overridden in the derived class

### ISSUE THREAD

**Issue by mitchterlisner** [nunit/docs#53]
I suspect this may be working as desired, but even so I'd suggest clarifying the documentation.

The documentation says

> You may define a SetUp method in the base class and another in the derived class. NUnit will call base class SetUp methods before those in the derived classes.

I’m looking at an existing codebase that uses that uses base classes to share common setup across many derived classes, like this:

```
public class Base
{
    [SetUp]
    public virtual void Setup() { ...

public class Derived : Base
{
    [SetUp]
    public override void Setup() { base.Setup(); ...
```

NUnit ignores the base class setup method, and only calls the derived class setup method.  (I know the derived setup calls the base setup, but I wanted to understand why _NUnit_ didn't call the base setup _first_.)

CommandBuilder.BuildSetUpTearDownList doesn’t just look for SetUp methods at each layer – it gets methods on the fixture (with Reflect.GetMethodsWithAttribute), then traverses the inheritance hierarchy to put them in order.  Since the derived class setup method _overrides_ the base class setup method, Reflect.GetMethodsWithAttribute only finds one setup method – the override on the derived class – it doesn't even see the base class setup method.

I’m guessing this is as-desired, so my suggestion is to simply add a small clarification to the documentation, something like this:

> You may define a SetUp method in the base class and another in the derived class. NUnit will call base class SetUp methods before those in the derived classes. If a base class SetUp method is overridden in the derived class, NUnit will not call the base class SetUp method.

Since it's been this way a while, I'd also suggest updating older versions of the documentation.

Note, if the derived class setup method _hides_ the base class setup method (either explicitly with ‘new’ or implicitly with no ‘new’/‘override’ modifier), then Reflect.GetMethodsWithAttribute finds _both_ setup methods, so it calls both, as expected.

[Tests to replicate.txt](https://github.com/nunit/docs/files/228732/Tests.to.replicate.txt)

Thanks,
Mitch

**Comment by rprouse** [comment]
You are correct that this is the desired and intended behaviour, but a documentation clarification is a good idea.

**Comment by CharliePoole** [comment]
Thanks for pointing this out. One note for your own use, I don't think we envisioned that people might hide the base method. The more "normal" think to do is to just use differently named methods, with the names indicating what they actually do, like CreateXyzInstance(). So long as they have the attribute, then they are SetUp methods.
