### ISSUE TITLE
Confusing Copyright Page

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#541]
[This page](https://docs.nunit.org/articles/developer-info/NUnit-Copyright-Notice.html) was recently a source of confusion to a new developer. There's nothing on the page to indicate what it's for. My guess is that it was linked from something else in the wiki, which may have said what was the purpose of the sample.

We can deduce from the format that it's a sample of a header to be used on files, but which files? Which project does it apply to or does it apply to all projects? Is the name "Charlie Poole" just an example of a name, or does it mean you should use my name?

We could research where this came from and what it's context was originally, but I'm wondering if it serves any purpose at all. If not, we could just delete it. 

@SeanKilleen I'll leave it to you to decide how (or if) we need to discuss this.

**Comment by SeanKilleen** [comment]
Closing this older issue; that page has since been moved and is now in a general license file page. Should remove the confusion. 👍
