### ISSUE TITLE
No docs for distributed engine extensions

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#546]
The engine/console project distributes five extensions:

* V2 Result Writer
* V2 Framework Driver
* NUnit Project Loader
* Visual Studio Project Loader
* Teamcity Test Listener (*)

These are all currently included in the MSI package and are available as separate packages from both nuget.org and chocolatey.org. Unfortunately, there is no user documentation for them.

To be clear, there is some documentation - just not user-oriented:

* There is documentation of how to write an extension, for example some kind of result writer.
* There is documentation of how to package the console and engine, including the V2 Result Writer.
* There's just nothing to tell users that the V2 Result Writer exists, what it's for and how to install it.

We probably don't need more than one or two paragraphs for each extension but first we need to figure out where it goes, since the top-level menu structure is in flux.

@ChrisMaddock @SeanKilleen What do you say?

(*) We plan to stop distributing the teamcity extension at some point, but for now it's included.

**Comment by ChrisMaddock** [comment]
Maybe create a new "NUnit Extensions" section? They are separate projects after all. Could probably clarify in the landing page for the section that these are just a few extensions that the NUnit Org maintains, and other extension may be out there in the ecosystem.

**Comment by SeanKilleen** [comment]
Sorry, I'd completely missed this. 

I like the idea of a page as a way to showcase these extensions, to differentiate between those maintained by the NUnit team and others in the community, and to serve as a jumping off point to the docs on how to create extensions.

I think there a few places we could add this content:

* Option 1: NUnit --> Extending NUnit --> TBD Page Title
* Option 2: NUnit Engine --> Engine Extensions --> TBD Page Title
* Option 3: Some new place

**Comment by CharliePoole** [comment]
We have ways  to extend the framework as well as the engine. If we did (1) then we would need to create a further breakdown under it - framework vs engine at a minimum. That seems confusing. Option 3 seems to have the same problem.

So to me number 2 appears most likely. Maybe something like...

  * Engine Extensions (general description of the idea of extending the engine)
    * Available Extensions
      * NUnit Project Loader
      * VS Project Loader
      * etc.
    * Creating an extension (list kinds of extensions it's possible to create)
      * Project Loader
      * Result Writer
      * etc.

I think we have text to fill in most of this already available.

**Comment by SeanKilleen** [comment]
@CharliePoole's suggestion works fine for me. 

For next steps, how about I create a PR that gets the structural changes in place, and leave TODOs in the text for folks to fill in? Then we could collaborate on the content on that branch, get it to a good place, and merge it in.

**Comment by CharliePoole** [comment]
Exactly what I was hoping for!
