### ISSUE TITLE
Executing selected test method using nunit 3.2.1

### ISSUE THREAD

**Issue by anilrepala505** [nunit/docs#55]
Hi, how to test only selected test method from a specific class file in a dll.

nunit3-console.exe D:\Projects\N_Selenium.dll -testlist=Tests.cs -test=VALIDZIPCODE 
-result=D:\ConsoleResults.xml

**Comment by rprouse** [comment]
`--testlist` is used to provide a file with a list of tests to run, one per line, not the code file.

You can't run a specific file, but you can run a namespace, class or individual test method using the `--where` clause.  You can also decorate groups of tests using a `[Category]` attribute and run those.

See the [Test Selection Language](https://github.com/nunit/docs/wiki/Test-Selection-Language) docs for more info.

I also just answered a similar question on [StackOverflow](http://stackoverflow.com/questions/37297838/run-individual-test-from-nunit3-console-exe/)

I am closing this, but feel free to post if you have questions.
