### ISSUE TITLE
Spell check consideration

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#557]
@OsirisTerje brought this up in #556.

Re: spellchecking, `Pakrym` is not a known word, so wouldn't it be expected that the spell-checker flag it until it is added to a list?

Would seem we have a couple of options here:

* Continue as-is, adding words as they come up, which the spell-checker will alert us to and we can then ignore
* Exclude certain files from spell checker, such as release notes files
* Create some sort of regex that excludes usernames -- I believe cSpell would respect @ followed by characters followed by a [Space].
* Open to other options.

Thoughts?

**Comment by ChrisMaddock** [comment]
I don't mind it. It can be mildly irritating when it fails on your PR (especially with en-US spellings!), but I think its a reasonable trade-off for error catching. 🙂
