### ISSUE TITLE
Update Code of Conduct

### ISSUE THREAD

**Issue by rprouse** [nunit/docs#567]
See https://github.com/nunit/governance/issues/41

The .NET Foundation now has a standard [code of conduct](https://dotnetfoundation.org/about/code-of-conduct) for all projects and the [markdown file](https://github.com/dotnet-foundation/website/blob/main/CODE_OF_CONDUCT.md) linking to it.

This standardizes the CoC across member projects but more importantly for us it provides an email address for reports and a committee for investigations.

**Comment by SeanKilleen** [comment]
@rprouse I'm happy to take this on if you'd like. 👍

**Comment by rprouse** [comment]
Thanks @SeanKilleen, I've dual assigned it but you are free to take it on. I'll take care of the other repos.

**Comment by SeanKilleen** [comment]
Reopening this because somehow I managed to add a blank document previously?
