### ISSUE TITLE
Review Project Editor Docs

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#57]
I've moved the project editor docs essentially as-is from the 2.6 version, minus a few NUnit 2 specific notes and typos. Would someone mind casting a quick look over as a review?

One specific thought - is the setting of AppBase still supported in Nunit3, as `--basepath` was removed?

Cheers.

**Comment by CharliePoole** [comment]
It looks good to me.

Regarding the AppBase... yes, it is supported in the project format.
