### ISSUE TITLE
NUnit cannot run tests with .nunit project file?

### ISSUE THREAD

**Issue by fubar-coder** [nunit/docs#60]
When a `.nunit` project file is passed to NUnit 3.2.1, I get the following error:

```
Test Files
    D:\buildAgent-1\temp\buildTmp\SDfHu2hL4FX7foQDHXGCHHeJAqo0QsAK.nunit


Errors and Failures

1) Invalid : D:\buildAgent-1\temp\buildTmp\SDfHu2hL4FX7foQDHXGCHHeJAqo0QsAK.nunit
File type is not supported
```

Passing the DLL works, but this problem breaks the NUnit plugin for TeamCity.

The `.nunit` file looks like this:

```xml
<NUnitProject>
<Settings activeconfig="active" appbase="D:\buildAgent-1\work\a7777f86cc8169d9"/>
<Config name="active">
<assembly path="RestSharp.Portable.OAuth2.Tests\bin\Release\RestSharp.Portable.OAuth2.Tests.dll"/>
</Config>
</NUnitProject>
```

It seems that someone else had this problem too on [StackOverflow](http://stackoverflow.com/questions/35261722/teamcity-nunit-3-0-console-runner-not-working).

**Comment by fubar-coder** [comment]
Wrong project :(

**Comment by buzzdan** [comment]
find the correct thread here:
https://github.com/nunit/nunit/issues/1525
