### ISSUE TITLE
No License in this repo

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#608]
Can't believe I somehow missed this.

There's no `LICENSE` file in this repo and we need to fix that ASAP.

I believe it should fall under the MIT license same as NUnit does.

@rprouse I think this is just housekeeping and doesn't require a larger discussion given the spirit of things, but let me know if we need a more official agreement before I add the license. 

I've been operating under the assumption that it's been MIT licensed this whole time; only just realized the documentation for that was missing.

**Comment by mikkelbu** [comment]
I would also think that this repo had a license - and that is was MIT

**Comment by SeanKilleen** [comment]
Thanks for validating that @mikkelbu. 👍

I think I'll do a PR and get everyone's approval just to make it clear.

**Comment by rprouse** [comment]
I think we just missed the license when we moved the docs. The website is a CC license, https://nunit.org/, https://creativecommons.org/licenses/by-nc-sa/4.0/

Probably more appropriate for the docs?

**Comment by SeanKilleen** [comment]
@rprouse I think maybe CC for content and MIT for process? (E.g. the way we have docfx configured, the build process, etc.)

I just want to make sure everything is covered. 👍

**Comment by SeanKilleen** [comment]
In looking into it a little more, it looks like CC-BY-SA 4.0 is largely for content and MIT is largely for software, but MIT is a bit more permissive and CC-BY-SA has some potential extra complexity.

Given this, I'd love to go with the MIT license because I think from a practical perspective it allows everything across content and code and it makes the most sense practically. MIT + CC-BY-SA seems to be considered overkill for sites like ours.

I'm not a lawyer, but MIT seems simple and practical in this case.

I'll open a PR with the MIT license and then will ping @rprouse so that he can direct me on who to request review / approval from.
