### ISSUE TITLE
Not able to run multiple classes or multiple methods or combination at the same time

### ISSUE THREAD

**Issue by nmraog** [nunit/docs#61]
Hi,

Please let me know that if there is any possibility in NUnit3.0 to execute multiple classes or multiple methods or multiple categories at the same time using nunit3-console.If possible please specify the same in Test Selection Language doc.

Thanks,
Eswar

**Comment by CharliePoole** [comment]
Yes, it is possible to select more than one category or class using TSL. The `&&` and `||` operators are provided for that purpose. This is already explained on the doc page under the heading **Compound Expressions** but if you feel it isn't stated clearly enough, please let us know what could be improved.

**Comment by nmraog** [comment]
Hi Charlie,

Thanks for your reply.
As I have tried all the possibilities to run multiple categories or
classes,i couldn't achieve success. All the examples that you have been
provided in the document are related to multiple combinations. But i
couldn't see any example for running multiple classes or categories. Could
you please give me an example to run multiple categories please.

Thanks,
Eswar

**Comment by CharliePoole** [comment]
Sure...

```
  --where "cat == Cat1 || cat == cat2"
```

If that does not help, it may be better if you post the syntax you are trying to use so we can examine it.

Of course, you have to be aware of how the command-line of your OS may treat some characters specially. That's the reason we provide `and` and `or` as operators as well.

**Comment by nmraog** [comment]
Hi Charlie,

Thanks for the reply,

The above given one is working for me. As i have tried with && (and)
conditions, it is not worked for me.

Thanks for the help.
Eswar

**Comment by CharliePoole** [comment]
In what way is && not working? An option like

```
  --where "cat == X && cat == Y"
```

should select only tests that have both categories on them.
