### ISSUE TITLE
NUnit3 Test Adapter disabled automatically in Visual Studio 2015

### ISSUE THREAD

**Issue by labilbe** [nunit/docs#62]
Various times a day, _NUnit3 Test Adapter Version 3.0.10_ extension is automatically disabled on _Visual Studio Enterprise 2015 Version 14.0.25123.00 Update 2_.

In my test project, I am using the following NUnit package
`<package id="NUnit" version="3.2.1" targetFramework="net461" />`

So I have to enable the package and restart Visual Studio again (and then it works).
I couldn't detect when exactly the problem occurs, but it's 3 or 4 times a day.

![sshot-1](https://cloud.githubusercontent.com/assets/54315/15674038/da461c1a-273a-11e6-897c-4711b7073f2d.png)

**Comment by CharliePoole** [comment]
Have you enabled per-user extensions? Since you are able to re-enable it, I doubt that's the problem, but check anyway.

**Comment by labilbe** [comment]
Per-user extensions were enabled in fact.
Problem solved. Thank you very much !
