### ISSUE TITLE
Is it possible to run new Test Console app with nunit3-console.exe?

### ISSUE THREAD

**Issue by patrickjamesbarry** [nunit/docs#63]
I followed the blog post and created a console app to run my tests in. That works great when running with in dnu/dotnet.  But when I take the test project dll and try to run it with nunit3-console, I get this error

C:\repos\test-pub\zip>nunit3-console smoketest.dll
NUnit Console Runner 3.2.1
Copyright (C) 2016 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
  CLR Version: 4.0.30319.42000

Test Files
    smoketest.dll

The NUnit 3.0 driver does not support the portable version of NUnit. Use a platform specific runner.

I am trying to get nunit3-console to run the tests in this dll because we are not allowed to install dnu or dotnet yet on the server this needs to run on.

Our project.json for the test project has this snippet:
```
  "frameworks": {
    "dnx452": {
    }
  },
  "dependencies": {
    "Moq": "4.2.1510.2205",
    "NUnitLite": "3.2.1"
  },
```

**Comment by rprouse** [comment]
You need to get your tests to use the .NET 4.5 version of the NUnit Framework instead of the portable version. Updating to RC2 may help since the framework will match properly.

```json
  "frameworks": {
    "net451": { 
    }
  },
  "dependencies": {
    "Moq": "4.2.1510.2205",
    "NUnitLite": "3.2.1"
  },
```

Let me know if it works for you.

**Comment by patrickjamesbarry** [comment]
I made the change you suggested and still getting same error.

**Comment by patrickjamesbarry** [comment]
When I run the test using dotnet, I can get it to work. When I build the project with dnu, it does not.  Is there a way to make it work with dnu. ( I realize dnu is out of favor now).

**Comment by patrickjamesbarry** [comment]
I was able to make the case for dotnet over dnu. Closing ticket. Thanks!
