### ISSUE TITLE
Addition to the coding standards

### ISSUE THREAD

**Issue by rprouse** [nunit/docs#65]
_From @oznetmaster on November 4, 2014 13:15_

I have noticed that a few of the source files still use qualified names in the actual code where they are either redundant, or unnecessary (e.g. no conflicts).

This is a very bad coding practice, and reduces the maintainability of the code.

ReSharper can automatically fix this, removing the qualifications, and adding using statements as necessary.

As these source files are touched for other reasons, it would be good to remove the qualifications.

Future code should really try to avoid them.

_Copied from original issue: nunit/dev#2_

**Comment by rprouse** [comment]
_From @CharliePoole on November 4, 2014 16:21_

We haven't generally been filing issues against the wiki, but let's try it out for this one and see how many of the devs are tracking it. :-)

I'm OK with adding the statement somewhere that we shouldn't use redundant qualified names. If you have a using statement then qualifying the name is silly.

OTOH, I'm not necessarily in favor of saying "Always use a using rather than qualifying your names" because there are cases when it makes sense to spell out the full name.

For example, when I am trying to distinguish between System.Xml.XmlNode and NUnit.Framework.Internal.XmlNode (I think that's it's name) it may be clearer to spell both of them out in the code. I also have a tendency to spell out the full name of a class if it's only used once in the source file.

So, it may be a matter of how to word it.

**Comment by rprouse** [comment]
_From @CharliePoole on November 4, 2014 16:23_

Slightly off topic, but should we run some sort of rules-based static analysis in our builds? Or separately from time to time? I like the notion that static analysis is a different sort of testing, but still testing. OTOH, I'd want us to have our own rules, not just adopt something from MS or Jetbrains because it's easy.

**Comment by rprouse** [comment]
I think running code analysis is a really good idea. I would suggest we use the Code Analysis built into Visual Studio. We can copy the Microsoft Managed Recommended Rules and adjust them to meet our needs. I turned them on for nunit.framework-4.5 and only got 23 warnings which is pretty good and it did find a few errors like classes that should be disposable.

It would be redundant to run them on every framework build, so we could just enable them on the most full featured projects (4.5).

Would you like me to create an issue, do the work, clean up the code and create a PR? It wouldn't take long.

**Comment by rprouse** [comment]
_From @OsirisTerje on November 4, 2014 20:3_

I have added a filtered rule list in the adapter project.  Take a look at that ruleset, I think that one makes more sense, both in terms of noise and relevance, than the standard MS ones.
https://github.com/nunit/nunit-vs-adapter/blob/master/Osiris.Extended.ruleset

**Comment by rprouse** [comment]
_From @OsirisTerje on November 4, 2014 20:4_

The SCA from MS finds mostly coding issues, and not style issues. oznetmaster's issue is more like a style issue.  Resharper does that while editing, and stylecop does that both on builds and in the editor.

**Comment by rprouse** [comment]
_From @CharliePoole on November 4, 2014 20:9_

Hi Rob,

I think turning on code analysis is a good adhoc approach and I use it
myself. When I work in MonoDevelop I use some features they have.

What I was asking about is something more general, consistent with our
project vision, which can be used by anyone who builds NUnit. I am
specifially refering to our stated goals of **platform neutrality** and
**IDE neutrality**.

I recognize this makes it a bit more complicated. Are you willing to look
into it from that broader angle?

Charlie

**Comment by rprouse** [comment]
_From @CharliePoole on November 4, 2014 20:11_

The adapter is of course a different matter. It makes sense to use MS stuff
pretty much exclusively for the VS adapter.

**Comment by rprouse** [comment]
_From @CharliePoole on November 4, 2014 20:13_

Right. I'm the one who opened up the can of worms here. We should first
deal with the specific issue. When Neil wakes up (he's in Perth, y'know) we
can get back to that. :-)

**Comment by rprouse** [comment]
_From @oznetmaster on November 4, 2014 21:9_

The problem with using qualified names in the actual code is that it makes it difficult to change platforms or to repurpose the names globally.  If they are all handled by using and alias, it isolates all qualifications to a single location.

 

There are occasions where this is impossible, but very few.

**Comment by rprouse** [comment]
_From @CharliePoole on November 5, 2014 1:33_

So is there some specific language you would like to insert?

**Comment by rprouse** [comment]
_From @CharliePoole on May 22, 2016 19:56_

@oznetmaster @rprouse @OsirisTerje 
As we are getting rid of this repo, I'm wondering what to do with this issue, if anything.

**Comment by rprouse** [comment]
This looks like another issue where we had high hopes and many ideas. I think it is worthwhile to carry it forward to a new repo. We could split this into two issues, one for code analysis and one for style. How does that sound? Those issues could be added to the main nunit repo or to the docs repo. My issue with docs is that we need to change the code, so it likely applies to each repo in turn.

Thoughts?

**Comment by rprouse** [comment]
_From @CharliePoole on May 23, 2016 20:28_

I'd prefer to see the style-related issue in the docs repo. Docs items in the nunit repo tend not to be worked on. The code analysis issue may already be in the nunit repo separately. 

Mainly, since this issue would disappear when we remove the repo, I wanted people to put their comments that remain relevant someplace permanent.

**Comment by rprouse** [comment]
_From @CharliePoole on May 23, 2016 20:29_

Alternatively, we could keep this repo and no longer use it. However, old repos seem to attract issues, which we then have to replicate elsewhere. With the small number of remaining issues, it seems we should be able to get rid of it.

**Comment by rprouse** [comment]
_From @OsirisTerje on May 23, 2016 20:35_

Agree, move it over to the docs repo and then close this repo.  Normally I prefer as little documentation as possible - due to the issues with maintaining them, and code styles should be in the form of rulesets and for R#, dotsettings files, which only some explanations  and links in the docs.  My 5 cents....

**Comment by rprouse** [comment]
For no longer maintained repos collecting issues, one thing that I have seen is adding an issue template explaining that the repo is no longer maintained and directing people to the correct repo.

**Comment by rprouse** [comment]
_From @CharliePoole on May 23, 2016 21:30_

We've done that in other cases but this repo had only the wiki. I deleted all the pages to avoid people getting confused by them.

**Comment by SeanKilleen** [comment]
🧹 Cleanup -- I am closing this issue because:

✅ As far as I can tell, it is no longer relevant
✅ The topic had diverged a bit from the stated title
✅ It is more than 4 years old.

I am happy to revisit this if someone would like to comment and clarify the purpose. Thanks!

**Comment by ChrisMaddock** [comment]
Agreed. This dates from a time when we aimed for consistent coding standards across all projects. That sort of stuff should now really be "devolved" to individual projects - the entire "Developer Info" section could really use a refresh here.
