### ISSUE TITLE
Add page about command-line usage

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#66]
This is not really an NUnit issue, but many users have difficulty using the nunit-console or nunitlite command-line because they don't understand how to escape special characters for their OS. The page should have a general explanation of the need and sections for Windows and Linux.

**Comment by SeanKilleen** [comment]
🧹 Cleanup -- closing this issue because:

✅ It is unclear if this is still a large need
✅ The documentation request is only adjacent to NUnit
✅ This issue is 4+ years old.

If this would still be beneficial and we often see users with these questions, feel free to let me know and I'll reopen.
