### ISSUE TITLE
Prepare combined release notes

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#69]
@CharliePoole commented on [Thu Oct 29 2015](https://github.com/nunit/nunit/issues/952)

We currently have separate release notes for each alpha and beta. As we did in the past, we should keep these availabler for those who want them through a link but the primary release notes should actually be cumulative. Ideally, we want to let people see what changed since NUnit 2.6.4.

**Comment by rprouse** [comment]
If people want individual, incremental release notes, they can always view [Changes.txt](https://raw.githubusercontent.com/nunit/nunit/master/CHANGES.txt), so I don't think we need to maintain them on the wiki once we combine.

**Comment by asbjornu** [comment]
I might be misunderstanding the whole discussion and issue here, but can't we just use [GitHub Releases](https://help.github.com/articles/creating-releases/) to document the changes (release notes)?

**Comment by CharliePoole** [comment]
Combined Release Notes may be a misnomer. I wanted something that would tell people the difference between NUnit 2 and NUnit 3. This may be getting too late to bother with but we do still have tons of new people who seem to be surprised that there is as much difference as there is.

**Comment by asbjornu** [comment]
I haven't really noticed much (surprising) difference myself, so that comes as a surprise to me. But okay, I understand. Whatever can be done in code with `[Obsolete]` has probably already been done, I assume? Having a document explaining a migration path from v2 to v3 would probably be useful, but it sounds like a really boring thing to write. 😛

**Comment by rprouse** [comment]
As developers, isn't all code boring to write?

For most developers, the upgrade is fairly seamless, but people often rely on undocumented behaviour or need to rewrite extensions. It is also nice to highlight the new features in one place :smile:

**Comment by CharliePoole** [comment]
Not sure if anyone wants to take this on. If not, I suggest closing it as won't fix.

**Comment by ChrisMaddock** [comment]
I agree

**Comment by rprouse** [comment]
Third vote no, closing 😄
