### ISSUE TITLE
Test Engine API doc: ISettings.cs and IRecentFiles.vs no longer found

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#724]
https://github.com/nunit/docs/blob/master/docs/articles/nunit-engine/Test-Engine-API.md

Refers to `IRecentFiles.cs` and `ISettings.cs`, neither of which seem to exist anymore. Assuming they may just need to be removed, but wanted doublecheck

**Comment by mikkelbu** [comment]
IRecentFiles where removed as part of nunit/nunit-console#874, so this will be removed in version 4 of the NUnit Console. ISettings were removed as part of nunit/nunit-console#873 and will also be gone in version 4.

**Comment by SeanKilleen** [comment]
Thanks @mikkelbu! I'll remove them as part of #723.
