### ISSUE TITLE
Markdownlint not running in our build process currently

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#746]
Oops. Something must have changed with a major version. Fortunately it looks like there's only a few things to clean up once we fix it up.

![image](https://user-images.githubusercontent.com/2148318/224462961-55130711-fa80-4dcd-ba02-d8b6b4f480d0.png)

**Comment by donatocayurin** [comment]
Thank you  ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏
