### ISSUE TITLE
Document software requirements for building NUnit

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#76]
@CharliePoole commented on [Mon Sep 22 2014](https://github.com/nunit/nunit/issues/240)

What compilers and other tools, what versions, etc. 

Alternatives where possible

Document on Wiki?

Process to follow to ensure that we don't break the build for those using older tools... e.g.: always add new projects to the solution using some particular IDE, etc.

---

@CharliePoole commented on [Wed Dec 16 2015](https://github.com/nunit/nunit/issues/240#issuecomment-165201475)

Notes...
- VS2012 and higher will build NUnit solution
- MonoDevelop can build it
- Need to test with SharpDevelop

**Comment by asbjornu** [comment]
Would be nice to have Project Rider on that list as well.

**Comment by CharliePoole** [comment]
@asbjornu Well, I had to google it to see what it is! Since it's a proprietary product not available to me, I won't be writing it up as an option. Of course, anyone who uses it to build NUnit could contribute to the docs.

**Comment by asbjornu** [comment]
I'm sure JetBrains would be happy to give the NUnit team a license to their products. That's a bit off topic, though. I'd be happy to provide the necessary documentation, if Rider needs anything special.

**Comment by CharliePoole** [comment]
It would be great if you did that. Once there's a page out there with the other methods, you'll be able to see the kind of info we want to give people. In particular, we need to give them the limitations of each method, like if you can't do certain builds on some platforms.

**Comment by asbjornu** [comment]
@CharliePoole Sounds good!

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: I am closing this because the [Team Practices](https://docs.nunit.org/articles/developer-info/Team-Practices.html) developer info page mentions that the way to build each project is the `BUILD.md` in each repository, and I agree that's the appropriate place for this information.

Feel free to comment on this and I'm happy to consider reopening.
