### ISSUE TITLE
Add documentation for passing parameters on command line

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#77]
New in 3.4 - will affect the command line options page and TestContext - not sure if it should have it's own page in general?

(Note: I haven't gone 3.4 release notes - just stumbled across this one. Will try and have a look at some point.)

**Comment by CharliePoole** [comment]
@rprouse What's done/not done as part of the 3.4 release?

**Comment by rprouse** [comment]
If by done/not done you mean documentation, I have not updated any documentation yet. From the release notes, the following probably needs documentation;

- [ ] Test case names will only be truncated if the runner requests it or it is overridden on the command line with the `--test-name-format` option
- [ ] The .NET 2.0 version of the framework now includes LINQ. If your tests target .NET 2.0, you can now use LINQ queries in your tests
- [ ] The TeamCity event listener has been separated out into an engine extension
- [ ] There is a new `--params` command line option that allows you to pass parameters to your tests which can be retrieved using `TestContext.Parameters`
- [ ] Another new command line option `--loaduserprofile` causes the User Profile to be loaded into the NUnit Agent process.

**Comment by CharliePoole** [comment]
That's what I meant. I can put in some of them at least. I also think I should subdivide Breaking Changes by release, since we have a few post-3.0 breaking changes.

**Comment by CharliePoole** [comment]
I missed you on Skype. I'll keep mine on for a while.

**Comment by CharliePoole** [comment]
I updated docs for the last two points listed.

**Comment by CharliePoole** [comment]
This was updated on the two relevant pages.
