### ISSUE TITLE
Breaking changes for 3.4

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#78]
The Breaking Changes page is written on the assumption that it's all about 3.0 and that we won't have any further breaking changes. That turns out to be false.

We need sections by version on the page. For 3.4, we have to document at least the following:
* the --teamcity option requires an  extension to be installed
* test case names are no longer  truncated by default
* NUnit.System.Linq is now required by the 2.0 build of the framework.

There may be others and we should check back for any introduced in 3.0.1, 3.2.0 and 3.2.1.

**Comment by SimonCropp** [comment]
> the --teamcity option requires an extension to be installed

can you provide some doco on that?

**Comment by CharliePoole** [comment]
Well of course that's what this issue is for - to make sure we write some docs.

The good news is that the extension is bundled with some packages. At this time, a separate install is only needed if you use the NUnit.ConsoleRunner package. In that case you have to install the NUnit.Extension.TeamCityEventListener package.

**Comment by SimonCropp** [comment]
we moved from 3.2.1 to 3.4 and now TeamCity is not picking up any tests. from looking at the config for the nunit console installed on the agent the .addins is including teamcity-event-listener.dll in a relative dir. 

This seemed to be all configured in the default install of nunit console

we are also passing ` --teamcity` to the command line 

But we do not get any test results being picked up by TC. it seems the test output has changed

in 3.4 the output is 

```
=> ArticleTemplateTest.Simple
6/29/2016 12:41:29 AM ~000005ms Variable: approvalFrame = 'ParticularDocsWeb.Tests.ArticleTemplateTest.Simple()'
6/29/2016 12:41:29 AM ~000062ms Variable: frame = 'ParticularDocsWeb.Tests.ArticleTemplateTest.Simple()'
```

in 3.2.1 the output is

```
 [ParticularDocsWeb.Tests.dll] ArticleTemplateTest.Simple
[12:09:40] :			 [ArticleTemplateTest.Simple] [Test Output]
6/28/2016 12:09:40 PM ~000006ms Variable: approvalFrame = 'ParticularDocsWeb.Tests.ArticleTemplateTest.Simple()'
6/28/2016 12:09:40 PM ~000063ms Variable: frame = 'ParticularDocsWeb.Tests.ArticleTemplateTest.Simple()'
```

TC version is `9.1.6 (build 37459)`

**Comment by CharliePoole** [comment]
This is the nunit documentation repo - take a look at the actual nunit repo for the issue you are most likely running into. I can't get a link for you from my phone but it's the last one we closed. It will be fixed in 3.4.1, probably tomorrow.

**Comment by rprouse** [comment]
@SimonCropp see nunit/nunit#623

As @CharliePoole says, we will hopefully have 3.4.1 out in the next day or so to fix it.

**Comment by SimonCropp** [comment]
@rprouse thanks

**Comment by CharliePoole** [comment]
Another breaking change (since 3.0) that's not noted is that there must be at least one NUnit attribute or assertion in a test assembly for us to recognize it.
