### ISSUE TITLE
NUnit project xml attributes case-sensitive

### ISSUE THREAD

**Issue by jc1001** [nunit/docs#80]
Hi there,

I am trying to specify a configuration file in my NUnit project file.  According to the [documentation](https://github.com/nunit/docs/wiki/NUnit-Project-XML-Format), I can add an attribute named "configFile" to achieve this.  I tried this and it didn't work.  

When checking in the latest NUnit source code, I noticed that it is calling an extension method named [GetAttribute](https://github.com/nunit/nunit/blob/master/src/NUnitEngine/Addins/nunit-project-loader/SafeAttributeAccess.cs) which does a lookup on the attributes.  This lookup is case-sensitive (and in this instance is called like this:
`string configFile = configNode.GetAttribute("configfile");`
from [here](https://github.com/nunit/nunit/blob/master/src/NUnitEngine/Addins/nunit-project-loader/NUnitProject.cs)

When I change my attribute to "configfile", it all works like a charm.  So I am not sure whether the documentation is wrong in this case, or whether the source code should do a case-insensitive lookup on attributes.

**Comment by CharliePoole** [comment]
I'll double check, but I think the lower-case option is correct. I don't think XML attributes should generally be ignoring case in their names.

**Comment by CharliePoole** [comment]
Looks like there are a number of camelCase names on that page. I'll check them all.

**Comment by jc1001** [comment]
Thanks

**Comment by CharliePoole** [comment]
Doc page is updated. Had to fix binpathtype as well as configfile.
