### ISSUE TITLE
NUnit3 Test Adapter not running all tests in VisualStudio 2015

### ISSUE THREAD

**Issue by aspengler** [nunit/docs#81]
Since the latest update of NUnit 3 Test Adapter (3.4.0), when pressing "Run All", only parts of the tests are executed (e.g. only the tests of the first project when grouped "By Project").

**Comment by CharliePoole** [comment]
This is the repository for the NUnit documentation. Issues about the software should be filed in the repository for that software, in this case the NUnit3 Test adapter repo. I'm moving this there.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit3-vs-adapter #202](https://github.com/nunit/nunit3-vs-adapter/issues/202) via [**ZenHub**](https://www.zenhub.com/)
