### ISSUE TITLE
Document improved EqualityComparer

### ISSUE THREAD

**Issue by manfred-brands** [nunit/docs#812]
In NUnit3 when comparing instances of non-standard classes that do not implement `IEquatable` only reference comparison works.

In NUnit4 a `PropertiesComparer` has been added. See  https://github.com/nunit/nunit/issues/4394
This allows comparing simple data types without having to write out separate Asserts for each property or having to add `IEquatable` purely for nunit purposes.

**Comment by manfred-brands** [comment]
Waiting on [PR](https://github.com/nunit/nunit/pull/4516) to be approved, as it changes behaviour

**Comment by OsirisTerje** [comment]
Approved
