### ISSUE TITLE
Examine exact behaviour and correct text about setupfixture and nested namespaces

### ISSUE THREAD

**Issue by mikkelbu** [nunit/docs#819]
It seems like the update in https://github.com/nunit/docs/pull/673/files contradicts the behaviour, so we should examine the exact behaviour and correct the documentation to match the behaviour.

Also see discussion from https://github.com/nunit/docs/issues/327#issuecomment-1505740799

**Comment by OsirisTerje** [comment]
From discussion in #327 

1. We should then add to the docs the explanation that @CharliePoole gave https://github.com/nunit/docs/issues/327#issuecomment-1505755777
2. A code example, added to the snippets, demonstrating the behavior would be nice.  It could also serve as the exploration for #819
