### ISSUE TITLE
Need an ordered collection equivalent constraint

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#82]
The current `CollectionEquivalentConstraint` does an unordered comparison ([docs](https://github.com/nunit/docs/wiki/CollectionEquivalentConstraint)). I need an ordered comparison. I do this a lot; in fact, I can't imagine a scenario in which I would ever want an unordered comparison.

For an `IEnumerable` to be equivalent to (replaceable by) another `IEnumerable`, they should return the same value as each other after each enumerator `MoveNext`. That's just the way the `IEnumerable` contract is.

Expanding to consider lists in general, equivalence doesn't really carry a connotation of being unordered or ordered (that I know if) so I don't like the ambiguity. I think this would probably be better:

```c#
Assert.That(list, Is.EquivalentInThisOrder(new[] { ... }));
Assert.That(list, Is.EquivalentInAnyOrder(new[] { ... }));
```

Or this, which feels more natural and more clear to me:

```c#
Assert.That(list, Has.ItemsInExactOrder(new[] { ... }));
Assert.That(list, Has.ExactItemsInAnyOrder(new[] { ... }));
```

I think it's better than a `bool ordered` parameter added to `Is.EquivalentTo`. What do you think?

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit #1654](https://github.com/nunit/nunit/issues/1654) via [**ZenHub**](https://www.zenhub.com/)
