### ISSUE TITLE
Merge TestAdapter Home pages

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#83]
There is no content on the home page for the NUnit 2 Test Adapter.

The NUnit 3 page at https://github.com/nunit/docs/wiki/Visual-Studio-Test-Adapter needs to be revised so it has information for both adapters.

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: Closing this as we made the decision to not include V2 information in docs.nunit.org. (and per comments on #31).
