### ISSUE TITLE
update lang tag site

### ISSUE THREAD

**Issue by Arhell** [nunit/docs#835]
remove https://github.com/nunit/docs/pull/624/files

**Comment by SeanKilleen** [comment]
@Arhell sorry, I don't understand -- is it because it's no longer required because the template supports it?

**Comment by Arhell** [comment]
> @Arhell sorry, I don't understand -- is it because it's no longer required because the template supports it?

no, just found a better way to add this tag 
https://dotnet.github.io/docfx/docs/template.html?q=_lang&tabs=modern#template-metadata

`_lang`

i update in template
