### ISSUE TITLE
Merge Usage pages

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#85]
Relevant information from https://github.com/nunit/nunit-vs-adapter/wiki/NUnit-Test-Adapter-for-Visual-Studio-2012-and-2013 needs to be merged into https://github.com/nunit/docs/wiki/Usage

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: Closing this as we made the decision to not include V2 information in docs.nunit.org. (and per comments on #31).
