### ISSUE TITLE
The Nunit Console Runner release notes is missing the last two versions of 3.15.x

### ISSUE THREAD

**Issue by hfickes** [nunit/docs#875]
Neither 3.15.4 nor 3.15.5 are shown in the nunit release notes at https://docs.nunit.org/articles/nunit-engine/release-notes.html

They can be found in the repo at https://github.com/nunit/nunit-console

A note as to why nunit-console 3.15 is needed for Nunit 4.0 and why 3.16 won't work would be useful.  Its a bit counter-intuitive that the older version must be used.

Thank you,
Herb

**Comment by SeanKilleen** [comment]
@hfickes thanks for the note on this.

Re: missing notes, @OsirisTerje I'm thinking that given GitHub releases are the canonical source for this information, perhaps we should remove this information from docs entirely and link to the GitHub releases (at least for NUnit console, as a test?) No need for the double-work and possible mis-matches.

Re: Explanation on the versioning -- @OsirisTerje do you think it might make sense to add it as a note to the migration guide?

**Comment by hfickes** [comment]
Thank you for the responses to my questions.  We'll move back to 3.15 for now and I appreciate the explanation for why not to use 3.16.
