### ISSUE TITLE
Merge Tips and Tricks Pages

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#88]
Relevant information from https://github.com/nunit/nunit-vs-adapter/wiki/Tips-And-Tricks needs to be merged into https://github.com/nunit/docs/wiki/Tips-And-Tricks

In addition, the NUnit 3 information has changed and needs to be updated. This could end up being two separate pages or two sections on the page.

Alternatively, we could change how the NUnit 2 version works to match NUnit 3, depending on how soon we expect to eliminate it.

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: Closing this as we made the decision to not include V2 information in docs.nunit.org. (and per comments on #31).
