### ISSUE TITLE
markdownlint-cli2 has changed how to pass configuration

### ISSUE THREAD

**Issue by stevenaw** [nunit/docs#883]
I pushed PR https://github.com/nunit/docs/pull/882 recently and it failed with the error:
```
markdownlint-cli2-config: command not found
```

It looks like a new version of `markdownlint-cli2` package has been published, v0.12.x, which removes the `markdownlint-cli2-config` entry point. It's instead recommended to pass config via the `--config` flag (https://github.com/DavidAnson/markdownlint-cli2/blob/main/CHANGELOG.md#012 ).

I'm unable to experiment with this at the moment but I think this just means changing how we invoke it

```
markdownlint-cli2-config ".github/linters/.markdownlint.yml" "docs/**/*.md"
# Change to ->
markdownlint-cli2 --config ".github/linters/.markdownlint.yml" "docs/**/*.md"
```

**Comment by mikkelbu** [comment]
@stevenaw I had the same problem for the analyzers, so I've supplied a PR, but there seem to be other problems. I'll also take a look at them
