### ISSUE TITLE
Document parameters passed to TestCaseDataSource

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#9]

**Comment by mikkelbu** [comment]
@CharliePoole Is this issue related to nunit/nunit#1230 ?

**Comment by CharliePoole** [comment]
Yes. I added it as a reminder way back when.

**Comment by mikkelbu** [comment]
I've added some text in https://github.com/nunit/docs/wiki/TestCaseSource-Attribute to describe the possibility of passing parameters to the source.

**Comment by mikkelbu** [comment]
@nunit/framework-team Can any of you review the addition?

**Comment by CharliePoole** [comment]
@mikkelbu Sorry, I thought I had reviewed this back when you did it. It looks good to me.
