### ISSUE TITLE
Add notations as to when features were added.

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#91]
Prior to NUnit 3.0, we had separate sets of docs for every release. With NUnit 3.0 we decided to maintain one set.

This continues to look like a good decision, but there's a problem when users see a feature in the docs that isn't present in the version they are using. We should at least add annotations that indicate when a feature was added.

Some features have an entire page that represents them while others take up a particular section on a page. In each case, we can follow the heading with something like **(3.2+)** to indicate when the feature became available.

This recently came up in an SO question related to special formatting of some types in NUnit messages. See https://github.com/nunit/docs/wiki/TestContext#addformatter for how I set it up for that case.

This issue will require going through all the features added since 3.0 to add annotations to the pages affected. In cases where we haven't created the docs yet, the annotation should be added when it is created.

**Comment by CharliePoole** [comment]
BTW, I don't see a need to annotate (3.0)... do others?

**Comment by rprouse** [comment]
No, I think we could just state on a top level page that all features are available in NUnit 3+ unless otherwise noted.

**Comment by SeanKilleen** [comment]
@CharliePoole @rprouse I wanted to follow up on this older issue.

Do we still think there's value in annotating all of the functionality? If so, I think it would entail the docs team:

* Going through the release notes from v3 onward
* Ensuring documentation exists for new features
* Notating the version number of introduction on the docs

I'm not opposed to this at all -- I like the practice. but I'd like to get a sense of what the impact is of this issue currently. Are we fielding questions about feature introduction timelines often, for example?

**Comment by CharliePoole** [comment]
Suggest closing this since nobody took action at the time... it would have been a smaller job when we were on 3.2!

It can still be done on a case-by-case basis as issues come up and as changes are made.
