### ISSUE TITLE
Re-add include and exclude parameters

### ISSUE THREAD

**Issue by MgSam** [nunit/docs#94]
It's super confusing that from v2 -> v3 the `include` and `exclude` parameters disappeared in favor of `where`. I think `where` is valuable, but its still overly verbose to handle the extremely common use case of including/excluding categories.

**Comment by rprouse** [comment]
@MgSam this repository's issues are for NUnit documentation changes. I am moving the issue to the NUnit framework repository.

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit #1715](https://github.com/nunit/nunit/issues/1715) via [**ZenHub**](https://www.zenhub.com/)
