### ISSUE TITLE
Update all pages under Extensibility

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#98]
@CharliePoole commented on [Fri Sep 26 2014](https://github.com/nunit/nunit.org/issues/9)

Document custom attributes, including action attributes and those that replace addins.
Explain how addins have gone away and how to convert from old to new model.
Update custom constraints page

**Comment by SeanKilleen** [comment]
🧹 Housekeeping: Closing this older issue as it appears to be covered by [Custom Attributes](https://docs.nunit.org/articles/nunit/extending-nunit/Custom-Attributes.html), [Addin Replacement in the Framework](https://docs.nunit.org/articles/nunit/technical-notes/usage/Addin-Replacement-in-the-Framework.html), etc.
