### ISSUE TITLE
Update some of the documentation for APIs removed in NUnit 4

### ISSUE THREAD

**Issue by stevenaw** [nunit/docs#986]
I noticed today that the [ListMapper docs](https://docs.nunit.org/articles/nunit/writing-tests/ListMapper.html) have the following warning at the top:

> ListMapper has been deprecated as of NUnit Framework 3.13.2. The functionality will be removed in NUnit Framework 4.0.

We may want to consider changing "will be removed" to present tense "has been removed".

**Comment by SeanKilleen** [comment]
Nice catch - I'll do a quick search for this and get a PR

**Comment by stevenaw** [comment]
Thanks @SeanKilleen !

**Comment by SeanKilleen** [comment]
@stevenaw there are two other spots mentioned -- in the console command line.

> `|`--params=PARAMETER, --p=PARAMETER` | (**NOTE:** _this is deprecated and will be removed in a future release. Please use --testparam instead_.) A test PARAMETER specified in the form NAME=VALUE for consumption by tests. Multiple parameters may be specified, separated by semicolons or by repeating the --params option multiple times. Case-sensitive. |`

And

> `|`--labels=VALUE` | Specify whether to write test case names to the output. Values: Off, OnOutputOnly, Before, After, BeforeAndAfter, On, or All. If not specified, defaults to Off. **Off**: No labeling is used. Both normal and immediate output appear in the order produced - i.e. immediate first. **OnOutputOnly**: A label appears before each sequence of output lines from the same test. Since tests may be run in parallel, output from different tests may be intermixed. **Before**: A label appears at the start of every test, whether it produces output or not. Additional labels are produced as needed if interspersed output takes place, just as for `--labels=OnOutputOnly`. **labels=After**: A label appears at the end of every test, whether it produced output or not. This label includes the pass/fail status of the test in addition to its name. Additional labels are produced as needed if there is any output, just as for `--labels=OnOutputOnly`. **BeforeAndAfter** A label appears at the start and end of every test, whether it produced output or not. The label at the end of the test includes the pass/fail status of the test in addition to its name. Additional labels are produced as needed if interspersed output takes place, just as for `--labels=OnOutputOnly`. **On**. Synonym for `--labels=OnOutputOnly`, now deprecated (will be removed in a future release). **All**: Synonym for `--labels=Before`, now deprecated (will be removed in a future release).|`


Not sure if we removed `--params` or the `On` and `All` values for `--labels`. Can you confirm?

**Comment by stevenaw** [comment]
Thanks for checking for these @SeanKilleen 
I don't have as much working knowledge on the console side but I think those should stay as-is. It looks like those have been identified for restructuring or removal within version 4 of the console runner, which hasn't yet been released (https://github.com/nunit/nunit-console/issues/752#issuecomment-619546354)

Strictly with regards to the `labels` case, I've found the [PR to deprecate those options](https://github.com/nunit/nunit-console/pull/721) but can't find any PR which removes them outright.
