### ISSUE TITLE
Update Action Attributes documentation

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#99]
@CharliePoole commented on [Fri Sep 26 2014](https://github.com/nunit/nunit.org/issues/8)

**Comment by SeanKilleen** [comment]
🧹 Cleanup -- closing this issue because:

✅ It does not have actionable information
✅ It is 3+ years old
✅ The page at <https://docs.nunit.org/articles/nunit/extending-nunit/Action-Attributes.html> appears to have a decent amount of information.
